@extends('layouts.public')

@section('title', 'SIPORA — Temukan Ruang untuk Berkembang')

@section('content')
@php($primaryCta = auth()->check() ? route(\App\Support\Auth\HomeRoute::for(auth()->user())) : route('register'))
<section id="beranda" class="relative overflow-hidden bg-white">
    <div class="pointer-events-none absolute -right-28 -top-36 size-[34rem] rounded-full bg-indigo-50 blur-3xl"></div>
    <div class="mx-auto grid max-w-7xl items-center gap-14 px-5 pb-24 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:pb-32 lg:pt-24">
        <div class="relative z-10">
            <span class="inline-flex items-center gap-2 rounded-full border border-indigo-100 bg-indigo-50 px-4 py-2 text-[11px] font-extrabold uppercase tracking-[0.15em] text-[#3346a8]"><span class="size-2 rounded-full bg-[#f59e0b]"></span> Platform kepemudaan Kabupaten Pemalang</span>
            <h1 class="mt-7 max-w-2xl text-5xl font-black leading-[1.08] tracking-[-0.045em] text-[#18245c] sm:text-6xl lg:text-7xl">Temukan ruang untuk <span class="relative text-[#3346a8]">berkembang.<svg class="absolute -bottom-3 left-0 w-full text-[#f59e0b]" viewBox="0 0 300 14" fill="none" aria-hidden="true"><path d="M3 10C81 1 190 2 297 8" stroke="currentColor" stroke-width="6" stroke-linecap="round"/></svg></span></h1>
            <p class="mt-8 max-w-xl text-lg leading-8 text-slate-600">Jelajahi kegiatan, bergabung dengan komunitas, temukan peluang, dan bangun portofolio terverifikasi bersama ekosistem pemuda Pemalang.</p>
            <div class="mt-9 flex flex-col gap-3 sm:flex-row"><a href="{{ route('activities.index') }}" class="landing-btn-primary">Jelajahi Activity <span aria-hidden="true">→</span></a><a href="{{ route('communities.index') }}" class="landing-btn-secondary">Temukan Community</a></div>
            <div class="mt-8 flex flex-wrap items-center gap-x-6 gap-y-3 text-sm text-slate-500"><span class="font-bold text-[#243378]">Dipercaya pemuda Pemalang</span><span>✓ Gratis untuk bergabung</span><span>✓ Aktivitas terverifikasi</span></div>
        </div>
        <div class="relative mx-auto w-full max-w-xl lg:mx-0">
            <div class="absolute -left-8 top-16 hidden h-32 w-24 rounded-3xl bg-[#f59e0b] lg:block"></div>
            <div class="relative overflow-hidden rounded-[2rem] bg-[#243378] p-3 shadow-2xl shadow-indigo-950/20">
                <img src="https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1100&q=85" alt="Pemuda berkolaborasi dalam kegiatan" class="h-[29rem] w-full rounded-[1.4rem] object-cover" fetchpriority="high">
                <div class="absolute left-8 top-8 rounded-full bg-[#f59e0b] px-4 py-2 text-xs font-black uppercase tracking-wider text-[#18245c]">Kolaborasi Pemuda</div>
                <div class="absolute bottom-8 left-8 right-8 rounded-2xl bg-white/95 p-5 shadow-xl backdrop-blur"><div class="flex items-center gap-4"><span class="grid size-12 place-items-center rounded-xl bg-indigo-50 text-2xl">✓</span><div><strong class="block text-xl text-[#18245c]">100% Terverifikasi</strong><span class="text-sm text-slate-500">Sertifikat digital sah daerah</span></div></div></div>
            </div>
        </div>
    </div>
</section>

<section class="relative z-20 -mt-10 px-5" aria-label="Pencarian publik">
    <form method="GET" action="{{ route('search.index') }}" class="mx-auto max-w-6xl rounded-2xl border border-slate-100 bg-white p-4 shadow-2xl shadow-indigo-950/10 sm:p-6">
        <div class="grid gap-3 lg:grid-cols-[1fr_auto]">
            <label class="relative"><span class="sr-only">Cari Activity, Community, atau Opportunity</span><span class="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-400">⌕</span><input type="search" name="q" maxlength="120" class="landing-search pl-11" placeholder="Cari Activity, Community, atau Opportunity..."></label>
            <button type="submit" class="landing-btn-primary">Cari Sekarang</button>
        </div>
        <div class="mt-4 flex flex-wrap items-center gap-2 text-xs"><span class="font-semibold text-slate-500">Pencarian populer:</span>@foreach (['Pelatihan', 'Volunteer', 'Beasiswa', 'Komunitas olahraga'] as $term)<span class="rounded-full bg-slate-100 px-3 py-1.5 font-semibold text-slate-600">{{ $term }}</span>@endforeach</div>
    </form>
</section>

<section class="bg-[#f6f7ff] px-5 pb-24 pt-28">
    <div class="mx-auto max-w-7xl"><x-public.section-heading eyebrow="Jelajahi Minat" title="Eksplorasi Sesuai Minatmu" description="Mulai dari hal yang kamu sukai dan temukan ruang bertumbuh bersama pemuda lainnya." centered />
        <div class="mt-12 grid grid-cols-2 gap-4 md:grid-cols-4 lg:grid-cols-8">@foreach ($interests as $interest)<article class="group rounded-2xl border border-indigo-100 bg-white p-5 text-center shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><span class="mx-auto grid size-14 place-items-center rounded-2xl bg-indigo-50 text-2xl transition group-hover:scale-110">{{ $interest['icon'] }}</span><h3 class="mt-4 text-sm font-extrabold text-[#18245c]">{{ $interest['name'] }}</h3></article>@endforeach</div>
    </div>
</section>

<section id="kegiatan" class="px-5 py-24"><div class="mx-auto max-w-7xl">
    <div class="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><x-public.section-heading eyebrow="Terjadwal Berikutnya" title="Kegiatan yang Bisa Kamu Ikuti" description="Activity publik diurutkan berdasarkan jadwal terdekat." /><a href="{{ route('activities.index') }}" class="font-bold text-[#3346a8]">Lihat semua Activity →</a></div>
    <div class="mt-12 grid gap-7 lg:grid-cols-3">@forelse ($activities as $activity)<x-discovery.activity-card :activity="$activity" />@empty<p class="col-span-full rounded-3xl border-2 border-dashed border-slate-200 p-10 text-center text-slate-500">Belum ada Activity publik yang akan datang.</p>@endforelse</div>
</div></section>

<section id="komunitas" class="bg-[#f6f7ff] px-5 py-24"><div class="mx-auto max-w-7xl"><x-public.section-heading eyebrow="Tumbuh Bersama" title="Temukan Komunitas" description="Terhubung dengan orang-orang yang berbagi minat dan tujuan yang sama." centered />
    <div class="mt-12 grid gap-6 lg:grid-cols-3">@forelse ($communities as $community)<x-discovery.community-card :community="$community" />@empty<p class="col-span-full rounded-3xl border-2 border-dashed border-slate-200 p-10 text-center text-slate-500">Belum ada Community aktif yang dapat ditampilkan.</p>@endforelse</div><div class="mt-8 text-center"><a href="{{ route('communities.index') }}" class="font-bold text-[#3346a8]">Lihat semua Community →</a></div>
</div></section>

<section id="peluang" class="px-5 py-24"><div class="mx-auto max-w-7xl">
    <div class="flex flex-col justify-between gap-6 md:flex-row md:items-end"><x-public.section-heading eyebrow="Buka Jalanmu" title="Opportunity untuk Pemuda" description="Akses beasiswa, kerelawanan, magang, dan program pengembangan yang dikurasi Admin SIPORA." /><a class="text-sm font-black text-[#3346a8]" href="{{ route('opportunities.index') }}">Lihat semua Opportunity →</a></div>
    <div class="mt-12 grid gap-6 lg:grid-cols-3">@forelse ($opportunities as $opportunity)<x-discovery.opportunity-card :opportunity="$opportunity" />@empty<div class="col-span-full rounded-3xl border-2 border-dashed border-slate-200 p-10 text-center text-sm text-slate-500">Belum ada Opportunity yang dipublikasikan.</div>@endforelse</div>
</div></section>

<section id="program" class="bg-[#f6f7ff] px-5 py-24"><div class="mx-auto max-w-7xl"><x-public.section-heading eyebrow="Program Pemerintah Daerah" title="Program Unggulan Dindikpora Pemalang" description="Program terarah untuk menguatkan kapasitas dan kontribusi pemuda di Kabupaten Pemalang." centered />
    <div class="mt-12 grid gap-6 lg:grid-cols-3">@foreach ($programs as $program)<article class="landing-card"><span class="grid size-12 place-items-center rounded-xl bg-[#243378] text-xl font-black text-white">{{ $program['icon'] }}</span><h3 class="mt-6 text-xl font-extrabold text-[#18245c]">{{ $program['title'] }}</h3><p class="mt-3 leading-7 text-slate-600">{{ $program['description'] }}</p><div class="mt-7 flex items-center justify-between text-sm"><strong class="text-[#3346a8]">{{ $program['participants'] }}</strong><span class="text-slate-500">Tahun 2026</span></div><div class="mt-3 h-2 rounded-full bg-slate-100"><div class="h-full rounded-full bg-[#f59e0b]" style="width: {{ $program['progress'] }}%"></div></div></article>@endforeach</div>
</div></section>

<section id="tentang" class="overflow-hidden px-5 py-24"><div class="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-2">
    <div class="relative mx-auto w-full max-w-lg"><div class="absolute -inset-6 rotate-3 rounded-[2rem] bg-indigo-50"></div><div class="relative rounded-[2rem] border border-indigo-100 bg-white p-7 shadow-xl"><div class="flex items-center gap-4 border-b border-slate-100 pb-6"><span class="grid size-16 place-items-center rounded-full bg-[#243378] text-lg font-black text-white">EK</span><div><h3 class="text-xl font-extrabold text-[#18245c]">Erik Kusuma Rais</h3><p class="text-sm text-slate-500">Pemuda Aktif · Pemalang</p></div><span class="ml-auto rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">✓ Terverifikasi</span></div><div class="grid grid-cols-3 gap-3 py-6 text-center"><div><strong class="block text-2xl text-[#243378]">12</strong><span class="text-xs text-slate-500">Aktivitas</span></div><div><strong class="block text-2xl text-[#243378]">8</strong><span class="text-xs text-slate-500">Sertifikat</span></div><div><strong class="block text-2xl text-[#243378]">4</strong><span class="text-xs text-slate-500">Keahlian</span></div></div><div class="space-y-3">@foreach (['Workshop Web Development', 'Relawan Festival Literasi', 'Pemuda Pelopor Desa'] as $item)<div class="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span class="grid size-9 place-items-center rounded-lg bg-white text-emerald-600">✓</span><span class="text-sm font-bold text-slate-700">{{ $item }}</span></div>@endforeach</div></div></div>
    <div><x-public.section-heading eyebrow="Youth Portfolio" title="Bangun Portofolio Terverifikasi Sejak Dini" description="Catat perjalananmu, kumpulkan bukti pengalaman, dan tampilkan kontribusi nyata dalam satu profil yang terpercaya." /><div class="mt-8 space-y-5">@foreach ([['Riwayat aktivitas yang tercatat', 'Setiap partisipasi terhubung dengan penyelenggara dan proses verifikasi.'], ['Sertifikat digital terintegrasi', 'Simpan capaianmu dalam portofolio yang mudah diakses.'], ['Kendali privasi tetap milikmu', 'Tentukan informasi yang ingin kamu tampilkan kepada publik.']] as [$title, $description])<div class="flex gap-4"><span class="grid size-10 shrink-0 place-items-center rounded-full bg-orange-50 font-black text-[#f59e0b]">✓</span><div><h3 class="font-extrabold text-[#18245c]">{{ $title }}</h3><p class="mt-1 leading-6 text-slate-600">{{ $description }}</p></div></div>@endforeach</div><a href="{{ $primaryCta }}" class="landing-btn-primary mt-9">{{ auth()->check() ? 'Buka Youth Home' : 'Mulai Bangun Portofolio' }}</a></div>
</div></section>

<section class="bg-[#172052] px-5 py-16 text-white" aria-label="Statistik publik SIPORA"><div class="mx-auto max-w-7xl"><p class="mb-10 text-center text-xs font-bold uppercase tracking-[0.18em] text-orange-300">Data ilustrasi tampilan — belum merupakan statistik resmi</p><div class="grid grid-cols-2 gap-10 lg:grid-cols-4">@foreach ($statistics as $stat)<div class="text-center"><strong class="block text-4xl font-black text-white sm:text-5xl">{{ $stat['value'] }}</strong><span class="mt-2 block text-sm text-indigo-200">{{ $stat['label'] }}</span></div>@endforeach</div></div></section>

<section class="bg-[#f6f7ff] px-5 py-24"><div class="mx-auto max-w-7xl"><x-public.section-heading eyebrow="Cerita Pemuda" title="Dari Pemuda, untuk Pemalang" description="Cerita tentang ruang belajar, pertemanan, dan kontribusi yang mereka temukan." centered /><div class="mt-12 grid gap-6 lg:grid-cols-3">@foreach ($stories as $story)<figure class="landing-card"><span class="text-5xl font-black leading-none text-indigo-100">“</span><blockquote class="mt-2 leading-7 text-slate-700">{{ $story['quote'] }}</blockquote><figcaption class="mt-7 flex items-center gap-3 border-t border-slate-100 pt-5"><span class="grid size-11 place-items-center rounded-full bg-[#243378] text-xs font-black text-white">{{ $story['initials'] }}</span><span><strong class="block text-sm text-[#18245c]">{{ $story['name'] }}</strong><small class="text-slate-500">{{ $story['role'] }}</small></span></figcaption></figure>@endforeach</div></div></section>

<section class="relative overflow-hidden bg-[#243378] px-5 py-24 text-center text-white"><div class="absolute inset-0 opacity-10" style="background-image: radial-gradient(circle at 20% 20%, white 0, transparent 25%), radial-gradient(circle at 80% 80%, #f59e0b 0, transparent 24%)"></div><div class="relative mx-auto max-w-3xl"><p class="text-xs font-black uppercase tracking-[0.2em] text-orange-300">Giliranmu untuk bertumbuh</p><h2 class="mt-4 text-4xl font-black tracking-tight sm:text-5xl">Ambil langkah pertamamu bersama SIPORA.</h2><p class="mx-auto mt-5 max-w-2xl text-lg leading-8 text-indigo-100">Bergabung dengan ekosistem pemuda Pemalang dan temukan lebih banyak cara untuk belajar, berkarya, dan berdampak.</p><div class="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><a href="{{ $primaryCta }}" class="landing-btn-primary !bg-[#f59e0b] !text-[#18245c] hover:!bg-amber-400">{{ auth()->check() ? 'Buka Youth Home' : 'Daftar Sebagai Pemuda' }}</a>@guest<a href="{{ route('register') }}" class="landing-btn-secondary !border-white/30 !bg-white/10 !text-white hover:!bg-white/20">Daftarkan Komunitas</a>@endguest</div></div></section>
@endsection

@section('footer')
<footer class="bg-[#11183f] px-5 pb-8 pt-16 text-indigo-100"><div class="mx-auto grid max-w-7xl gap-10 border-b border-white/10 pb-12 md:grid-cols-2 lg:grid-cols-4"><div><div class="flex items-center gap-3"><span class="grid size-10 place-items-center rounded-xl bg-white text-sm font-black text-[#243378]">SP</span><strong class="text-2xl text-white">SIPORA</strong></div><p class="mt-5 max-w-sm text-sm leading-7 text-indigo-200">Sistem Informasi Program Olahraga dan Kepemudaan Kabupaten Pemalang. Ruang kolaborasi untuk pemuda yang aktif dan berdampak.</p></div><div><h2 class="font-extrabold text-white">Jelajahi</h2><div class="mt-5 grid gap-3 text-sm"><a href="{{ route('activities.index') }}">Activity</a><a href="{{ route('communities.index') }}">Community</a><a href="{{ route('search.index') }}">Pencarian</a><a href="{{ route('opportunities.index') }}">Opportunity</a><a href="#program">Program Dindikpora</a></div></div><div><h2 class="font-extrabold text-white">Tentang SIPORA</h2><div class="mt-5 grid gap-3 text-sm"><a href="#tentang">Youth Portfolio</a><a href="#tentang">Tentang kami</a><a href="#tentang">Pusat bantuan</a><a href="#tentang">Kebijakan privasi</a></div></div><div><h2 class="font-extrabold text-white">Dindikpora Pemalang</h2><div class="mt-5 space-y-3 text-sm leading-6 text-indigo-200"><p>Jl. Merbabu No. 2, Pemalang</p><p>dindikpora@pemalangkab.go.id</p><p>(0284) 321357</p></div></div></div><div class="mx-auto flex max-w-7xl flex-col justify-between gap-3 pt-7 text-xs text-indigo-300 sm:flex-row"><p>© {{ date('Y') }} Dindikpora Kabupaten Pemalang. Hak cipta dilindungi.</p><p>Dibuat untuk pemuda Pemalang.</p></div></footer>
@endsection
