@extends('layouts.youth')
@section('title', $organization->name.' · Pengajuan Komunitas')
@section('content')
<div class="space-y-6">
    <a class="text-sm font-bold text-[#243378]" href="{{ route('youth.communities.index') }}">← Semua pengajuan</a>
    <section class="overflow-hidden rounded-3xl bg-[#18245c] text-white shadow-xl"><div class="grid gap-6 p-6 sm:p-8 md:grid-cols-[120px_1fr_auto] md:items-center">
        <div class="grid size-28 place-items-center overflow-hidden rounded-2xl bg-white/10 text-4xl font-extrabold">@if($organization->logo_path)<img class="size-full object-cover" src="{{ route('youth.communities.logo', $organization) }}" alt="Logo {{ $organization->name }}">@else{{ mb_substr($organization->name, 0, 1) }}@endif</div>
        <div><div class="flex flex-wrap items-center gap-2"><span class="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{{ $organization->category->name }}</span><x-community.status-badge :status="$organization->review_status" /></div><h1 class="mt-3 text-3xl font-extrabold sm:text-4xl">{{ $organization->name }}</h1><p class="mt-2 text-indigo-100">{{ $organization->administrativeArea?->name ?? 'Wilayah belum dipilih' }}</p></div>
        @can('update', $organization)<a class="landing-btn-primary" href="{{ route('youth.communities.edit', $organization) }}">Edit draft</a>@endcan
    </div></section>

    @if($organization->review_status === 'pending_review')<div class="rounded-2xl border border-amber-300 bg-amber-50 p-5"><h2 class="font-bold text-amber-900">Sedang menunggu verifikasi</h2><p class="mt-1 text-sm text-amber-800">Data dikunci selama peninjauan agar isi pengajuan tetap konsisten.</p></div>@endif
    @if($organization->review_status === 'revision' && $organization->latestVerificationRequest?->review_notes)<div class="rounded-2xl border border-orange-300 bg-orange-50 p-5"><h2 class="font-bold text-orange-900">Pengajuan perlu direvisi</h2><p class="mt-1 text-sm text-orange-800">{{ $organization->latestVerificationRequest->review_notes }}</p></div>@endif

    <div class="grid gap-6 lg:grid-cols-[1fr_340px]"><section class="sipora-card"><h2 class="text-xl font-bold text-[#243378]">Tentang komunitas</h2><p class="mt-4 whitespace-pre-line text-slate-600">{{ $organization->description ?: 'Deskripsi belum dilengkapi.' }}</p><h3 class="mt-7 font-bold">Alamat</h3><p class="mt-2 text-sm text-slate-600">{{ $organization->address_text ?: 'Belum dilengkapi' }}</p></section>
    <aside class="space-y-6"><section class="sipora-card"><h2 class="font-bold text-[#243378]">Status pengajuan</h2><div class="mt-3"><x-community.status-badge :status="$organization->review_status" /></div><p class="mt-3 text-sm text-slate-500">Status operasional: {{ $organization->operational_status === 'inactive' ? 'Belum aktif' : ucfirst($organization->operational_status) }}</p></section><section class="sipora-card"><h2 class="font-bold text-[#243378]">Kontak</h2><dl class="mt-3 space-y-2 text-sm"><div><dt class="text-slate-500">Email</dt><dd>{{ $organization->contact_email ?: '—' }}</dd></div><div><dt class="text-slate-500">Telepon</dt><dd>{{ $organization->contact_phone ?: '—' }}</dd></div><div><dt class="text-slate-500">Situs</dt><dd class="break-all">{{ $organization->website_url ?: '—' }}</dd></div></dl></section></aside></div>

    @can('submit', $organization)<section class="sipora-card border-indigo-200"><div class="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p class="text-xs font-bold uppercase tracking-wider text-orange-600">Langkah terakhir</p><h2 class="mt-1 text-xl font-bold text-[#243378]">Kirim untuk verifikasi</h2><p class="mt-1 text-sm text-slate-600">Pastikan semua data benar. Setelah dikirim, pengajuan dikunci selama peninjauan.</p></div><form method="post" action="{{ route('youth.communities.submit', $organization) }}" class="w-full max-w-md">@csrf<label class="field-label" for="submission_notes">Catatan pengajuan (opsional)</label><textarea class="field min-h-20" id="submission_notes" name="submission_notes" maxlength="2000"></textarea><button class="btn mt-3 w-full" type="submit">Kirim pengajuan</button></form></div></section>@endcan
</div>
@endsection
