@extends('layouts.verifier')
@section('title','Review E-LPJ')
@section('verifier-content')
<div class="space-y-6"><x-ui.page-header eyebrow="E-LPJ versi {{ $report->version }}" :title="$report->program->title" :description="$report->program->organization->name.' · '.$report->program->creator->name"><x-slot:actions><a class="btn-secondary" href="{{ route('verifier.financial-reports.index') }}">Kembali</a><x-program.financial-status-badge :status="$report->status" /></x-slot:actions></x-ui.page-header>
<x-ui.card><h2 class="text-lg font-bold text-text-primary">Program & Proposal</h2><dl class="mt-4 grid gap-4 rounded-xl bg-surface-soft p-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-text-muted">Kategori</dt><dd class="font-semibold">{{ $report->program->category?->name ?? '—' }}</dd></div><div><dt class="text-text-muted">Periode</dt><dd class="font-semibold">{{ $report->program->start_date?->translatedFormat('d M Y') ?? '—' }} – {{ $report->program->end_date?->translatedFormat('d M Y') ?? '—' }}</dd></div><div><dt class="text-text-muted">Status Program</dt><dd class="font-semibold">{{ str($report->program->execution_status)->title() }}</dd></div><div><dt class="text-text-muted">Proposal</dt><dd class="font-semibold">Versi {{ $report->program->latestProposal?->version ?? '—' }} · {{ $report->program->latestProposal?->status ?? '—' }}</dd></div></dl>@if($report->notes)<p class="mt-4 whitespace-pre-line text-sm text-text-secondary">{{ $report->notes }}</p>@endif</x-ui.card>
<section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Ringkasan keuangan">@foreach([['Anggaran Proposal',$summary['proposal_budget'],'primary'],['Realisasi Pengeluaran',$summary['realization_total'],'accent'],['Total Pemasukan',$summary['income_total'],'success'],['Selisih',$summary['difference'],$summary['over_budget']?'accent':'info']] as [$label,$value,$tone])<x-ui.metric-card :title="$label" :value="$money->rupiah($value)" icon="wallet" :tone="$tone" class="rupiah" />@endforeach</section>
@if($summary['over_budget'])<aside class="rounded-2xl border border-amber-200 bg-warning-soft p-4 text-sm text-text-secondary"><strong class="text-[#8A5A0A]">Perlu perhatian:</strong> realisasi pengeluaran melebihi anggaran Proposal.</aside>@endif
<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><main class="space-y-6"><x-ui.card><h2 class="text-lg font-bold text-text-primary">Ringkasan pelaksanaan</h2><p class="mt-2 text-sm text-text-secondary">{{ $report->program->activities->count() }} Activity terhubung · {{ $report->program->logbooks->where('status','approved')->count() }} Logbook disetujui</p><div class="mt-4 divide-y divide-border">@forelse($report->program->logbooks->take(3) as $logbook)<article class="py-3"><p class="text-xs font-bold text-text-muted">{{ $logbook->log_date->translatedFormat('d M Y') }} · progres {{ $logbook->progress_percent }}%</p><p class="mt-1 text-sm text-text-secondary">{{ $logbook->summary }}</p></article>@empty<p class="text-sm text-text-secondary">Belum ada Logbook.</p>@endforelse</div></x-ui.card>
<section class="table-shell"><div class="border-b border-border p-5"><h2 class="text-lg font-bold text-text-primary">Rincian transaksi</h2><p class="mt-1 text-sm text-text-secondary">{{ $summary['item_count'] }} transaksi · {{ $summary['evidence_count'] }} bukti</p></div><div class="overflow-x-auto"><table class="min-w-[720px]"><thead><tr><th>Tanggal</th><th>Jenis</th><th>Deskripsi</th><th>Nominal</th><th>Bukti</th></tr></thead><tbody>@forelse($report->items as $item)<tr class="border-t border-border"><td>{{ $item->transaction_date->translatedFormat('d M Y') }}</td><td>{{ $item->transaction_type==='expense'?'Belanja':'Pemasukan' }}</td><td class="font-semibold text-text-primary">{{ $item->description }}</td><td class="rupiah">{{ $money->rupiah($item->amount) }}</td><td>@if($item->receipt_path)<a class="font-bold text-primary hover:text-accent" target="_blank" href="{{ route('verifier.financial-reports.items.receipt',[$report,$item]) }}">Buka bukti</a>@else<span class="text-text-muted">—</span>@endif</td></tr>@empty<tr><td colspan="5"><x-ui.empty-state icon="wallet" title="Tidak ada transaksi" /></td></tr>@endforelse</tbody></table></div></section>
@if($report->review_notes)<x-workspace.review-history><article><x-program.financial-status-badge :status="$report->status" /><p class="mt-2 whitespace-pre-line text-sm text-text-secondary">{{ $report->review_notes }}</p></article></x-workspace.review-history>@endif</main>
<aside class="h-fit xl:sticky xl:top-24">@can('review',$report)<x-workspace.decision-panel title="Keputusan E-LPJ" :action="route('verifier.financial-reports.review',$report)" />@else<x-ui.card><h2 class="text-lg font-bold">Review selesai</h2><p class="mt-2 text-sm text-text-secondary">Status E-LPJ ditampilkan pada header.</p></x-ui.card>@endcan</aside></div></div>
@endsection
