@extends('layouts.manager')
@section('title',$logbook->exists?'Edit Logbook':'Tambah Logbook')
@section('manager-content')
<div class="mx-auto max-w-3xl space-y-6"><header><p class="text-sm font-bold text-orange-600">PROGRAM · LOGBOOK</p><h1 class="mt-1 text-3xl font-black text-[#14205c]">{{ $logbook->exists?'Edit catatan pelaksanaan':'Catat pelaksanaan Program' }}</h1><p class="mt-2 text-slate-600">{{ $program->title }}</p></header>
<form method="POST" action="{{ $logbook->exists?route('manager.program-logbooks.update',[$organization,$program,$logbook]):route('manager.program-logbooks.store',[$organization,$program]) }}" class="space-y-5 rounded-2xl bg-white p-6 shadow-sm">@csrf @if($logbook->exists)@method('PATCH')@endif
<div><label class="label" for="log_date">Tanggal laporan</label><input class="field" type="date" id="log_date" name="log_date" value="{{ old('log_date',$logbook->log_date?->format('Y-m-d')) }}"><x-input-error :messages="$errors->get('log_date')" /></div>
<div><label class="label" for="activity_id">Activity terkait (opsional)</label><select class="field" id="activity_id" name="activity_id"><option value="">Keseluruhan Program</option>@foreach($activities as $activity)<option value="{{ $activity->uuid() }}" @selected(old('activity_id',$logbook->activity?->uuid())===$activity->uuid())>{{ $activity->title }}</option>@endforeach</select><x-input-error :messages="$errors->get('activity_id')" /></div>
<div><label class="label" for="summary">Ringkasan pelaksanaan</label><textarea class="field" rows="5" id="summary" name="summary">{{ old('summary',$logbook->summary) }}</textarea><x-input-error :messages="$errors->get('summary')" /></div>
<div class="grid gap-4 sm:grid-cols-2"><div><label class="label" for="obstacles">Hambatan</label><textarea class="field" rows="4" id="obstacles" name="obstacles">{{ old('obstacles',$logbook->obstacles) }}</textarea></div><div><label class="label" for="solutions">Solusi/tindak lanjut</label><textarea class="field" rows="4" id="solutions" name="solutions">{{ old('solutions',$logbook->solutions) }}</textarea></div></div>
<div><label class="label" for="progress_percent">Progres yang dilaporkan (%)</label><input class="field" type="number" min="0" max="100" id="progress_percent" name="progress_percent" value="{{ old('progress_percent',$logbook->progress_percent??0) }}"><p class="mt-1 text-xs text-slate-500">Nilai laporan manager, bukan skor otomatis SIPORA.</p><x-input-error :messages="$errors->get('progress_percent')" /></div>
<div class="flex gap-3"><button class="btn-primary">Simpan draft</button><a class="btn-secondary" href="{{ route('manager.program-logbooks.index',[$organization,$program]) }}">Kembali</a></div></form></div>
@endsection
