@extends('layouts.youth')
@section('title', 'Profil Saya · SIPORA')
@section('content')
<div class="space-y-6">
<section class="sipora-card"><div class="flex flex-col gap-6 sm:flex-row sm:items-center"><div class="grid size-28 shrink-0 place-items-center overflow-hidden rounded-full bg-[#eef0ff] text-3xl font-black text-[#243378]">@if($user->profile?->profile_photo_path)<img class="size-full object-cover" src="{{ route('youth.profile.photo') }}" alt="Foto profil {{ $user->profile->full_name }}">@else{{ str($user->profile?->full_name ?? $user->name)->substr(0,1)->upper() }}@endif</div><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><h1 class="text-3xl font-extrabold">{{ $user->profile?->full_name ?? $user->name }}</h1><span class="rounded-full px-3 py-1 text-xs font-bold {{ $user->identity?->verification_status === 'verified' ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700' }}">{{ $user->identity?->verification_status === 'verified' ? 'Youth terverifikasi' : 'Belum terverifikasi' }}</span></div><p class="mt-2 text-slate-600">{{ $user->profile?->occupation_title ?: 'Tambahkan pekerjaan atau institusi' }} @if($user->primaryDomicile) · {{ $user->primaryDomicile->administrativeArea->name }}@endif</p><div class="mt-4 flex flex-wrap gap-2">@foreach($user->interests as $interest)<span class="interest-chip">{{ $interest->name }}</span>@endforeach</div></div><a class="btn-secondary" href="{{ route('youth.profile.edit') }}">Edit profil</a></div></section>
<x-profile-completion :completion="$completion" />
<div class="grid gap-6 lg:grid-cols-2"><section class="sipora-card"><h2 class="text-xl font-bold">Tentang saya</h2><p class="mt-3 whitespace-pre-line text-slate-600">{{ $user->profile?->bio ?: 'Bio belum diisi.' }}</p><dl class="mt-6 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="font-semibold text-slate-500">Status</dt><dd class="mt-1">{{ $user->profile?->occupation_status ?: 'Belum diisi' }}</dd></div><div><dt class="font-semibold text-slate-500">Kelayakan usia</dt><dd class="mt-1">{{ $eligibility['eligible'] === true ? 'Segmen inti Youth' : ($eligibility['eligible'] === false ? 'Di luar segmen inti' : 'Belum dihitung') }}</dd></div></dl></section>
<section class="sipora-card"><h2 class="text-xl font-bold">Privasi profil</h2><p class="mt-2 text-sm text-slate-600">NIK, dokumen identitas, tanggal lahir lengkap, alamat detail, telepon, dan email selalu privat.</p><form class="mt-5 space-y-3" method="post" action="{{ route('youth.profile.visibility.update') }}">@csrf @method('PUT') @foreach(['is_profile_public'=>'Profil dapat dipublikasikan nanti','show_photo'=>'Tampilkan foto','show_bio'=>'Tampilkan bio','show_interests'=>'Tampilkan minat'] as $key=>$label)<label class="flex items-center justify-between gap-4 rounded-xl border border-slate-200 p-3"><span class="font-medium">{{ $label }}</span><input type="hidden" name="{{ $key }}" value="0"><input class="size-5 accent-[#243378]" type="checkbox" name="{{ $key }}" value="1" @checked($user->profileVisibility?->{$key} ?? true)></label>@endforeach<button class="btn mt-2 w-full" type="submit">Simpan privasi</button></form></section></div>
</div>
@endsection
