@extends('layouts.public')
@section('title', 'Jelajahi Activity · SIPORA')
@section('meta_description', 'Temukan Activity terverifikasi yang dipublikasikan Community di SIPORA Kabupaten Pemalang.')
@section('canonical', route('activities.index'))
@section('content')
<x-public.page-intro eyebrow="Eksplorasi publik" title="Temukan Activity untuk bertumbuh" description="Cari kegiatan terverifikasi yang telah dipublikasikan oleh Community di SIPORA." icon="activity" />
<div class="bg-surface-muted px-5 py-10"><div class="mx-auto max-w-7xl">
    <x-public.filter-panel :action="route('activities.index')" :reset="route('activities.index')" label="Filter Activity"><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label class="xl:col-span-2"><span class="label">Cari Activity</span><input class="field" type="search" name="q" value="{{ $filters['q'] }}" maxlength="120" placeholder="Judul, Community, kategori, atau lokasi"></label><label><span class="label">Kategori</span><select class="field" name="category"><option value="">Semua kategori</option>@foreach($categories as $category)<option value="{{ $category->slug }}" @selected($filters['category']===$category->slug)>{{ $category->name }}</option>@endforeach</select></label><label><span class="label">Kecamatan</span><select class="field" name="location"><option value="">Semua lokasi</option>@foreach($locations as $location)<option value="{{ $location->code }}" @selected($filters['location']===$location->code)>{{ $location->name }}</option>@endforeach</select></label><label><span class="label">Mode</span><select class="field" name="mode"><option value="">Semua mode</option>@foreach(['offline'=>'Offline','online'=>'Online','hybrid'=>'Hybrid'] as $value=>$label)<option value="{{ $value }}" @selected($filters['mode']===$value)>{{ $label }}</option>@endforeach</select></label><label><span class="label">Pendaftaran</span><select class="field" name="registration"><option value="">Semua mekanisme</option><option value="open" @selected($filters['registration']==='open')>Langsung diterima</option><option value="approval_required" @selected($filters['registration']==='approval_required')>Memerlukan persetujuan</option></select></label><label><span class="label">Urutkan</span><select class="field" name="sort"><option value="upcoming" @selected($filters['sort']==='upcoming')>Paling dekat</option><option value="newest" @selected($filters['sort']==='newest')>Terbaru dipublikasikan</option><option value="closing" @selected($filters['sort']==='closing')>Pendaftaran segera tutup</option></select></label><label class="flex min-h-11 items-center gap-3"><input class="size-5 rounded border-slate-300 text-primary focus:ring-orange-400" type="checkbox" name="availability" value="open" @checked($filters['availability']==='open')><span class="text-sm font-semibold text-slate-700">Pendaftaran tersedia</span></label></div></x-public.filter-panel>
    <div class="mt-9 flex flex-wrap items-end justify-between gap-3"><div><p class="text-xs font-extrabold uppercase tracking-wider text-orange-600">Activity publik</p><h2 class="mt-1 text-2xl font-extrabold text-text-primary">{{ $activities->total() }} hasil ditemukan</h2></div><a class="public-link" href="{{ route('communities.index') }}">Jelajahi Community <x-ui.icon name="chevron-right" class="size-4" /></a></div>
    <div class="mt-6 grid gap-6 md:grid-cols-2 xl:grid-cols-3">@forelse($activities as $activity)<x-discovery.activity-card :activity="$activity" />@empty<x-ui.empty-state class="col-span-full" title="Tidak ada Activity yang cocok" description="Ubah kata pencarian atau longgarkan filter untuk melihat pilihan lain." />@endforelse</div>@if($activities->hasPages())<div class="mt-10">{{ $activities->links() }}</div>@endif
</div></div>
@endsection
