@extends('layouts.public')
@section('title', $activity->title.' · SIPORA')
@section('meta_description', str($activity->description ?: 'Activity publik SIPORA.')->squish()->limit(155))
@section('canonical', route('activities.show', $activity))
@section('content')
<article class="bg-surface-muted">
    <section class="bg-primary-dark px-5 py-8 text-white"><div class="mx-auto grid max-w-7xl items-center gap-8 lg:grid-cols-[1fr_1.05fr]"><div><nav class="mb-5 flex items-center gap-2 text-sm text-indigo-200" aria-label="Breadcrumb"><a class="font-bold hover:text-white" href="{{ route('activities.index') }}">Activity</a><span>/</span><span class="truncate" aria-current="page">{{ $activity->title }}</span></nav><div class="flex flex-wrap gap-2"><x-ui.badge tone="orange">{{ $activity->category->name }}</x-ui.badge>@if($publicProgram)<a href="{{ route('programs.show', $publicProgram) }}"><x-ui.badge tone="blue" icon="notebook">Bagian dari {{ $publicProgram->title }}</x-ui.badge></a>@endif</div><h1 class="font-heading mt-4 text-4xl font-bold tracking-tight sm:text-5xl">{{ $activity->title }}</h1><p class="mt-4 text-indigo-100">Diselenggarakan oleh <a class="font-bold text-white underline" href="{{ route('communities.show', $activity->organization) }}">{{ $activity->organization->name }}</a></p><dl class="mt-6 grid gap-3 sm:grid-cols-2"><div class="flex items-center gap-3 rounded-xl bg-white/10 p-3"><x-ui.icon name="calendar" class="text-orange-300" /><div><dt class="text-xs text-indigo-200">Jadwal utama</dt><dd class="font-bold">{{ $activity->start_at->translatedFormat('d M Y, H:i') }}</dd></div></div><div class="flex items-center gap-3 rounded-xl bg-white/10 p-3"><x-ui.icon name="map-pin" class="text-orange-300" /><div><dt class="text-xs text-indigo-200">Lokasi</dt><dd class="font-bold">{{ $activity->venue_name ?: 'Daring' }}</dd></div></div></dl></div><div class="h-72 overflow-hidden rounded-3xl border border-white/15 shadow-2xl sm:h-96">@if($activity->poster_path)<img class="h-full w-full object-cover" src="{{ route('activities.poster',$activity) }}" alt="Poster {{ $activity->title }}">@else<x-public.media-fallback :label="$activity->category->name" icon="activity" />@endif</div></div></section>
    <div class="mx-auto grid max-w-7xl gap-8 px-5 py-10 lg:grid-cols-[minmax(0,1fr)_360px]"><div class="space-y-8"><section><p class="text-xs font-extrabold uppercase tracking-wider text-orange-600">Tentang Activity</p><h2 class="public-section-title mt-1">Deskripsi kegiatan</h2><p class="mt-5 whitespace-pre-line text-base leading-8 text-slate-700">{{ $activity->description }}</p></section><section class="public-panel"><div class="flex items-center gap-3"><span class="grid size-11 place-items-center rounded-xl bg-indigo-50 text-primary"><x-ui.icon name="calendar" /></span><div><p class="text-xs font-extrabold uppercase tracking-wider text-slate-500">Jadwal</p><h2 class="text-xl font-extrabold text-text-primary">Sesi Activity</h2></div></div><div class="mt-5 space-y-3">@forelse($activity->sessions as $session)<article class="grid gap-3 rounded-xl border border-slate-200 p-4 sm:grid-cols-[48px_1fr]"><span class="grid size-12 place-items-center rounded-xl bg-indigo-50 font-mono font-bold text-primary">{{ $session->session_number }}</span><div><h3 class="font-extrabold text-text-primary">{{ $session->title }}</h3><p class="public-meta mt-1"><x-ui.icon name="clock" class="size-4" />{{ $session->start_at->translatedFormat('d M Y, H:i') }}–{{ $session->end_at->format('H:i') }}</p><p class="public-meta mt-1"><x-ui.icon name="map-pin" class="size-4" />{{ $session->venue_name ?: 'Daring' }}</p>@if($session->description)<p class="mt-2 text-sm leading-6 text-slate-600">{{ $session->description }}</p>@endif</div></article>@empty<x-ui.empty-state title="Jadwal belum tersedia" description="Jadwal sesi belum dipublikasikan oleh penyelenggara." />@endforelse</div></section></div>
        <aside class="space-y-5 lg:sticky lg:top-28 lg:self-start"><section class="rounded-2xl border border-orange-200 bg-orange-50 p-6"><p class="text-xs font-extrabold uppercase tracking-wider text-orange-700">Pendaftaran</p><h2 class="mt-1 text-xl font-extrabold text-text-primary">{{ $activity->registration_mode === 'open' ? 'Pendaftaran terbuka' : 'Memerlukan persetujuan' }}</h2><p class="mt-3 text-sm leading-6 text-slate-600">Diterima {{ $acceptedCount }} / {{ $activity->quota ?? 'tanpa batas' }}</p><p class="mt-1 text-xs text-slate-500">Batas {{ $activity->registration_close_at?->translatedFormat('d M Y H:i') ?? $activity->start_at->translatedFormat('d M Y H:i') }}</p>@if($participation)<div class="mt-4"><x-activity.registration-badge :status="$participation->registration_status"/></div>@endif @error('registration')<p class="mt-4 rounded-xl bg-red-100 p-3 text-sm text-red-800">{{ $message }}</p>@enderror @auth @role('youth') @if(!$participation)<form class="mt-5 space-y-3" method="POST" action="{{ route('activities.register',$activity) }}">@csrf<label><span class="label">Catatan pendaftaran (opsional)</span><textarea class="field" name="registration_notes" maxlength="2000" placeholder="Motivasi atau informasi untuk pengelola"></textarea></label><button class="landing-btn-primary w-full">Daftar Activity</button></form>@elseif(in_array($participation->registration_status,['pending','accepted'],true))<form class="mt-5" method="POST" action="{{ route('activities.registration.destroy',$activity) }}">@csrf @method('DELETE')<button class="btn-secondary w-full">Batalkan pendaftaran</button></form>@endif @endrole @else<a class="landing-btn-primary mt-5 w-full" href="{{ route('login') }}">Masuk untuk mendaftar</a>@endauth</section><section class="public-panel"><p class="text-xs font-extrabold uppercase tracking-wider text-slate-500">Penyelenggara</p><a class="mt-3 flex items-center gap-3" href="{{ route('communities.show', $activity->organization) }}"><span class="grid size-11 place-items-center rounded-xl bg-primary text-white"><x-ui.icon name="building" /></span><span><strong class="block text-primary-dark">{{ $activity->organization->name }}</strong><small class="text-slate-500">Lihat profil Community</small></span></a></section></aside>
    </div>
</article>
@endsection
