@extends('layouts.verifier')
@section('title','Review '.$activity->title)
@section('verifier-content')
<div class="space-y-6"><x-ui.page-header eyebrow="Review Activity" :title="$activity->title" :description="$activity->organization->name.' · '.$activity->category->name"><x-slot:actions><a class="btn-secondary" href="{{ route('verifier.activity-verifications.index') }}">Kembali</a><x-activity.status-badge :status="$activity->review_status" /></x-slot:actions></x-ui.page-header>
<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><main class="space-y-6"><x-ui.card class="overflow-hidden !p-0">@if($activity->poster_path)<img class="h-64 w-full object-cover" src="{{ route('verifier.activity-verifications.poster',$activity) }}" alt="Poster {{ $activity->title }}">@else<div class="grid h-48 place-items-center bg-primary-50 text-primary"><x-ui.icon name="calendar" class="size-12" /></div>@endif<div class="p-5 sm:p-6"><h2 class="text-lg font-bold text-text-primary">Informasi Activity</h2><p class="mt-3 whitespace-pre-line leading-7 text-text-secondary">{{ $activity->description }}</p><dl class="mt-5 grid gap-4 rounded-xl bg-surface-soft p-4 text-sm sm:grid-cols-2"><div><dt class="text-text-muted">Waktu</dt><dd class="font-semibold">{{ $activity->start_at->translatedFormat('d M Y H:i') }} – {{ $activity->end_at->translatedFormat('d M Y H:i') }}</dd></div><div><dt class="text-text-muted">Lokasi</dt><dd class="font-semibold">{{ ucfirst($activity->location_type) }} · {{ $activity->venue_name ?: 'Daring' }}</dd></div><div><dt class="text-text-muted">Pendaftaran</dt><dd>{{ $activity->registration_mode==='open'?'Terbuka':'Perlu persetujuan' }}</dd></div><div><dt class="text-text-muted">Kuota</dt><dd>{{ $activity->quota ?: 'Tidak dibatasi' }}</dd></div></dl></div></x-ui.card>
<x-ui.card><h2 class="text-lg font-bold text-text-primary">Penyelenggara & Program</h2><p class="mt-3 font-semibold">{{ $activity->organization->name }}</p><p class="text-sm text-text-secondary">Dibuat oleh {{ $activity->creator->profile?->full_name ?? $activity->creator->name }}</p><p class="mt-3 text-sm text-text-secondary">Relasi Program: {{ $activity->program?->title ?? 'Tidak terhubung' }}</p></x-ui.card>
@if($activity->latestReview?->review_notes)<x-workspace.review-history><p class="text-sm text-text-secondary">{{ $activity->latestReview->review_notes }}</p></x-workspace.review-history>@endif</main>
<aside class="h-fit xl:sticky xl:top-24">@if($activity->review_status==='pending_review')<x-workspace.decision-panel title="Keputusan Activity" :action="route('verifier.activity-verifications.review',$activity)" />@else<x-ui.card><h2 class="text-lg font-bold text-text-primary">Keputusan tersimpan</h2><p class="mt-2 text-sm text-text-secondary">Tindakan ganda tidak diizinkan.</p></x-ui.card>@endif</aside></div></div>
@endsection
