@extends('layouts.verifier')
@section('title', 'Review '.$organization->name.' · SIPORA')
@section('verifier-content')
<div class="space-y-6">
    <a class="text-sm font-bold text-[#243378]" href="{{ route('verifier.community-verifications.index') }}">← Kembali ke antrean</a>
    <section class="overflow-hidden rounded-3xl bg-[#18245c] p-6 text-white shadow-xl sm:p-8"><div class="flex flex-col gap-6 md:flex-row md:items-center"><div class="grid size-24 shrink-0 place-items-center overflow-hidden rounded-2xl bg-white/10 text-3xl font-extrabold">@if($organization->logo_path)<img src="{{ route('verifier.community-verifications.logo', $organization) }}" class="size-full object-cover" alt="Logo {{ $organization->name }}">@else{{ mb_substr($organization->name, 0, 1) }}@endif</div><div class="min-w-0 flex-1"><div class="flex flex-wrap gap-2"><span class="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{{ $organization->category->name }}</span><x-community.status-badge :status="$organization->review_status" /></div><h1 class="mt-3 text-3xl font-extrabold">{{ $organization->name }}</h1><p class="mt-2 text-indigo-100">Diajukan {{ $organization->latestVerificationRequest?->submitted_at?->format('d M Y, H:i') }}</p></div></div></section>

    @if($previousReview)<div class="rounded-2xl border border-orange-300 bg-orange-50 p-5"><p class="font-bold text-orange-900">Catatan keputusan sebelumnya</p><p class="mt-1 text-sm text-orange-800">{{ $previousReview->review_notes }}</p></div>@endif

    <div class="grid gap-6 xl:grid-cols-[1fr_360px]"><div class="space-y-6"><section class="sipora-card"><h2 class="text-xl font-bold text-[#243378]">Profil komunitas</h2><p class="mt-4 whitespace-pre-line text-slate-700">{{ $organization->description ?: 'Deskripsi belum dilengkapi.' }}</p><dl class="mt-6 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-slate-500">Wilayah</dt><dd class="font-semibold">{{ $organization->administrativeArea?->name ?? '—' }}</dd></div><div><dt class="text-slate-500">Alamat</dt><dd class="font-semibold">{{ $organization->address_text ?: '—' }}</dd></div><div><dt class="text-slate-500">Email</dt><dd class="font-semibold">{{ $organization->contact_email ?: '—' }}</dd></div><div><dt class="text-slate-500">Telepon</dt><dd class="font-semibold">{{ $organization->contact_phone ?: '—' }}</dd></div><div><dt class="text-slate-500">Website</dt><dd class="break-all font-semibold">{{ $organization->website_url ?: '—' }}</dd></div></dl>@if($organization->social_links)<h3 class="mt-6 font-bold">Media sosial</h3><ul class="mt-2 space-y-1 text-sm text-[#243378]">@foreach($organization->social_links as $channel => $url)<li><span class="font-semibold capitalize">{{ $channel }}:</span> <span class="break-all">{{ $url }}</span></li>@endforeach</ul>@endif</section>
        <section class="sipora-card"><h2 class="text-xl font-bold text-[#243378]">Metadata pengajuan</h2><dl class="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-slate-500">Catatan pemohon</dt><dd>{{ $organization->latestVerificationRequest?->submission_notes ?: '—' }}</dd></div><div><dt class="text-slate-500">ID pengajuan</dt><dd class="break-all font-mono text-xs">{{ $organization->latestVerificationRequest?->uuid() }}</dd></div></dl></section></div>
        <aside class="space-y-6"><section class="sipora-card"><h2 class="font-bold text-[#243378]">Pemohon</h2><p class="mt-3 font-bold">{{ $organization->creator?->profile?->full_name ?? $organization->creator?->name ?? 'Akun tidak tersedia' }}</p><p class="text-sm text-slate-500">{{ $organization->creator?->email }}</p></section>
        @if($organization->review_status === 'pending_review')<section class="sipora-card border-t-4 border-t-orange-500"><h2 class="text-lg font-bold text-[#243378]">Keputusan Verifier</h2><p class="mt-1 text-sm text-slate-500">Revisi dan penolakan wajib menyertakan catatan.</p><form method="post" action="{{ route('verifier.community-verifications.review', $organization) }}" class="mt-4 space-y-4">@csrf<label class="field-label" for="review_notes">Catatan review</label><textarea class="field min-h-28" id="review_notes" name="review_notes" maxlength="3000">{{ old('review_notes') }}</textarea><x-input-error :messages="$errors->get('review_notes')" /><div class="grid gap-2"><button class="btn !bg-emerald-700 hover:!bg-emerald-800" name="decision" value="approved" type="submit">Setujui & aktifkan</button><button class="btn-secondary !border-orange-300 !text-orange-800" name="decision" value="revision" type="submit">Minta revisi</button><button class="btn-secondary !border-red-300 !text-red-700" name="decision" value="rejected" type="submit">Tolak pengajuan</button></div></form></section>@else<section class="sipora-card"><h2 class="font-bold text-[#243378]">Keputusan tersimpan</h2><div class="mt-3"><x-community.status-badge :status="$organization->review_status" /></div><p class="mt-3 text-sm text-slate-600">{{ $organization->latestVerificationRequest?->review_notes ?: 'Tidak ada catatan tambahan.' }}</p></section>@endif</aside></div>
</div>
@endsection
