@extends('layouts.verifier')
@section('title','Review '.$organization->name.' · SIPORA')
@section('verifier-content')
<div class="space-y-6"><x-ui.page-header eyebrow="Review Community" :title="$organization->name" :description="'Diajukan '.($organization->latestVerificationRequest?->submitted_at?->translatedFormat('d M Y, H:i') ?? '—')"><x-slot:actions><a class="btn-secondary" href="{{ route('verifier.community-verifications.index') }}">Kembali</a><x-community.status-badge :status="$organization->review_status" /></x-slot:actions></x-ui.page-header>
<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><main class="space-y-6"><x-ui.card><div class="flex items-center gap-4"><span class="grid size-16 shrink-0 place-items-center overflow-hidden rounded-2xl bg-primary-50 text-2xl font-bold text-primary">@if($organization->logo_path)<img src="{{ route('verifier.community-verifications.logo',$organization) }}" class="size-full object-cover" alt="Logo {{ $organization->name }}">@else{{ mb_substr($organization->name,0,1) }}@endif</span><div><x-ui.badge tone="primary">{{ $organization->category->name }}</x-ui.badge><h2 class="mt-2 text-xl font-bold text-text-primary">Profil Community</h2></div></div><p class="mt-5 whitespace-pre-line leading-7 text-text-secondary">{{ $organization->description ?: 'Deskripsi belum dilengkapi.' }}</p><dl class="mt-5 grid gap-4 border-t border-border pt-5 text-sm sm:grid-cols-2"><div><dt class="text-text-muted">Wilayah</dt><dd class="font-semibold">{{ $organization->administrativeArea?->name ?? '—' }}</dd></div><div><dt class="text-text-muted">Alamat</dt><dd class="font-semibold">{{ $organization->address_text ?: '—' }}</dd></div><div><dt class="text-text-muted">Email</dt><dd class="font-semibold">{{ $organization->contact_email ?: '—' }}</dd></div><div><dt class="text-text-muted">Telepon</dt><dd class="font-semibold">{{ $organization->contact_phone ?: '—' }}</dd></div></dl></x-ui.card>
<x-ui.card><h2 class="text-lg font-bold text-text-primary">Informasi pengajuan</h2><dl class="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-text-muted">Pemohon</dt><dd class="font-semibold">{{ $organization->creator?->profile?->full_name ?? $organization->creator?->name ?? '—' }}</dd><dd class="text-text-secondary">{{ $organization->creator?->email }}</dd></div><div><dt class="text-text-muted">Catatan pemohon</dt><dd>{{ $organization->latestVerificationRequest?->submission_notes ?: '—' }}</dd></div></dl></x-ui.card>
@if($previousReview)<x-workspace.review-history><article><x-ui.badge tone="warning">Keputusan sebelumnya</x-ui.badge><p class="mt-2 text-sm text-text-secondary">{{ $previousReview->review_notes }}</p></article></x-workspace.review-history>@endif</main>
<aside class="h-fit xl:sticky xl:top-24">@if($organization->review_status==='pending_review')<x-workspace.decision-panel title="Keputusan Verifier" :action="route('verifier.community-verifications.review',$organization)" notes-name="review_notes" approve-label="Setujui & aktifkan" />@else<x-ui.card><h2 class="text-lg font-bold text-text-primary">Keputusan tersimpan</h2><p class="mt-2 text-sm text-text-secondary">{{ $organization->latestVerificationRequest?->review_notes ?: 'Tidak ada catatan tambahan.' }}</p></x-ui.card>@endif</aside></div></div>
@endsection
