@extends('layouts.verifier')
@section('title','Monitoring '.$logbook->program->title)
@section('verifier-content')
<div class="space-y-6"><x-ui.page-header eyebrow="Monitoring Program" :title="$logbook->program->title" :description="'Logbook '.$logbook->log_date->translatedFormat('d F Y').' · '.$logbook->creator->name"><x-slot:actions><a class="btn-secondary" href="{{ route('verifier.program-monitoring.index') }}">Kembali</a><x-program.logbook-status-badge :status="$logbook->status" /></x-slot:actions></x-ui.page-header>
<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><main class="space-y-6"><section class="grid gap-3 sm:grid-cols-3"><x-ui.metric-card title="Activity selesai" :value="$metrics['activity_completed'].'/'.$metrics['activity_total']" icon="clipboard-check" /><x-ui.metric-card title="Total Logbook" :value="$metrics['logbook_total']" icon="notebook" tone="info" /><x-ui.metric-card title="Progres dilaporkan" :value="$logbook->progress_percent.'%'" icon="activity" tone="success" /></section>
<x-ui.card><h2 class="text-lg font-bold text-text-primary">Ringkasan progres</h2><p class="mt-3 whitespace-pre-line leading-7 text-text-secondary">{{ $logbook->summary }}</p><div class="mt-5 grid gap-5 border-t border-border pt-5 lg:grid-cols-2"><div><h3 class="font-bold text-text-primary">Hambatan</h3><p class="mt-2 whitespace-pre-line text-sm text-text-secondary">{{ $logbook->obstacles ?: 'Tidak ada.' }}</p></div><div><h3 class="font-bold text-text-primary">Solusi</h3><p class="mt-2 whitespace-pre-line text-sm text-text-secondary">{{ $logbook->solutions ?: 'Belum dicatat.' }}</p></div></div></x-ui.card>
<x-ui.card><h2 class="text-lg font-bold text-text-primary">Media pelaksanaan</h2><div class="mt-4 grid gap-3 sm:grid-cols-2">@forelse($logbook->media as $media)<x-workspace.file-card :title="$media->caption ?: 'Media Logbook'" :href="route('verifier.program-monitoring.media',[$logbook,$media])" type="Bukti pelaksanaan" />@empty<x-ui.empty-state class="sm:col-span-2" icon="file-text" title="Tidak ada media" description="Logbook ini tidak memiliki media pendukung." />@endforelse</div></x-ui.card>
@if($logbook->review_notes)<x-workspace.review-history><p class="text-sm text-text-secondary">{{ $logbook->review_notes }}</p></x-workspace.review-history>@endif</main>
<aside class="h-fit xl:sticky xl:top-24">@can('review',$logbook)<x-workspace.decision-panel title="Keputusan Logbook" :action="route('verifier.program-monitoring.review',$logbook)" />@else<x-ui.card><h2 class="text-lg font-bold">Review selesai</h2><p class="mt-2 text-sm text-text-secondary">Status Logbook ditampilkan pada header.</p></x-ui.card>@endcan</aside></div></div>
@endsection
