@extends('layouts.manager')
@section('title','Peserta · '.$activity->title)
@section('manager-content')
<x-workspace.page-header eyebrow="Manajemen peserta" title="Peserta Activity" :description="$activity->title"><a class="btn-secondary" href="{{ route('manager.activities.show',[$organization,$activity]) }}">Detail Activity</a><x-activity.status-badge :status="$activity->execution_status" /></x-workspace.page-header>
<p class="mt-3 text-sm text-slate-500">{{ $sessionCount }} sesi terjadwal.</p>
<div class="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach(['pending'=>'Menunggu','accepted'=>'Diterima','rejected'=>'Ditolak','cancelled'=>'Dibatalkan'] as $key=>$label)<div class="rounded-2xl bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase text-slate-500">{{ $label }}</p><p class="mt-2 text-3xl font-black text-[#14205c]">{{ $counts[$key] ?? 0 }}</p></div>@endforeach</div>
<div class="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-white p-4 shadow-sm"><form class="flex flex-wrap gap-2"><select class="field !min-h-10" name="status" onchange="this.form.submit()">@foreach(['all'=>'Semua pendaftaran','pending'=>'Menunggu','accepted'=>'Diterima','rejected'=>'Ditolak','cancelled'=>'Dibatalkan'] as $value=>$label)<option value="{{ $value }}" @selected($status===$value)>{{ $label }}</option>@endforeach</select><select class="field !min-h-10" name="completion" onchange="this.form.submit()">@foreach(['all'=>'Semua penyelesaian','pending'=>'Belum diselesaikan','completed'=>'Selesai','no_show'=>'Tidak hadir'] as $value=>$label)<option value="{{ $value }}" @selected($completion===$value)>{{ $label }}</option>@endforeach</select></form><p class="text-sm text-slate-600">Kuota diterima: <strong>{{ $counts['accepted'] ?? 0 }} / {{ $activity->quota ?? '∞' }}</strong></p></div>
@if($activity->execution_status !== 'completed')<div class="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Keputusan penyelesaian peserta dibuka setelah eksekusi Activity berstatus selesai. Presensi tetap menjadi bukti dan tidak menentukan hasil secara otomatis.</div>@endif
<div class="table-shell mt-5 overflow-x-auto"><table class="min-w-[850px] text-left text-sm"><thead><tr><th scope="col">Peserta</th><th scope="col">Pendaftaran</th><th scope="col">Bukti presensi</th><th scope="col">Penyelesaian</th><th scope="col">Tindakan</th></tr></thead><tbody>
@forelse($participants as $participant)<tr class="border-t border-slate-100 align-top"><td class="p-4"><p class="font-bold text-[#14205c]">{{ $participant->user->profile?->full_name ?: $participant->user->name }}</p><p class="text-xs text-slate-500">{{ $participant->user->email }}</p><p class="mt-1 text-xs text-slate-500">Daftar {{ $participant->requested_at->translatedFormat('d M Y H:i') }}</p></td><td class="p-4"><x-activity.registration-badge :status="$participant->registration_status"/>@if($participant->registration_notes)<p class="mt-2 max-w-xs text-xs text-slate-500">{{ $participant->registration_notes }}</p>@endif</td><td class="p-4"><p class="font-semibold text-emerald-700">{{ $participant->present_count }} hadir</p><p class="text-xs text-slate-500">{{ $participant->absent_count }} absen · {{ $participant->excused_count }} izin · {{ $sessionCount }} sesi</p><p class="mt-1 text-[11px] text-slate-400">Bukti pendukung, bukan keputusan otomatis.</p></td><td class="p-4"><x-activity.completion-badge :status="$participant->completion_status"/>@if($participant->completed_at)<p class="mt-2 text-xs text-slate-500">{{ $participant->completed_at->translatedFormat('d M Y H:i') }}</p>@endif</td><td class="p-4">
@if($participant->registration_status==='pending')<div class="flex flex-wrap gap-2"><form method="POST" action="{{ route('manager.activities.participants.review',[$organization,$activity,$participant]) }}">@csrf<input type="hidden" name="decision" value="accepted"><button class="btn-primary">Terima</button></form><form method="POST" action="{{ route('manager.activities.participants.review',[$organization,$activity,$participant]) }}" class="flex gap-2">@csrf<input type="hidden" name="decision" value="rejected"><input class="field !min-h-10 w-40" name="notes" required maxlength="3000" placeholder="Alasan penolakan"><button class="btn-secondary !text-red-700">Tolak</button></form></div>
@elseif($participant->registration_status==='accepted' && $participant->completion_status==='pending' && $activity->execution_status==='completed')<div class="flex flex-wrap gap-2"><form method="POST" action="{{ route('manager.activities.participants.complete',[$organization,$activity,$participant]) }}">@csrf<input type="hidden" name="decision" value="completed"><button class="btn-primary">Selesaikan</button></form><form method="POST" action="{{ route('manager.activities.participants.complete',[$organization,$activity,$participant]) }}" data-confirm="Tandai peserta ini tidak hadir?">@csrf<input type="hidden" name="decision" value="no_show"><button class="btn-secondary">Tidak hadir</button></form></div>
@elseif($participant->registration_status==='accepted' && $participant->completion_status==='completed')
    @if($participant->certificate)<a class="btn-secondary" href="{{ route('certificates.verify',$participant->certificate->verification_code) }}" target="_blank" rel="noopener">Lihat sertifikat</a>
    @elseif($activity->certificate_enabled)<form method="POST" action="{{ route('manager.activities.participants.certificate',[$organization,$activity,$participant]) }}" data-confirm="Terbitkan sertifikat untuk peserta ini?">@csrf<button class="btn-primary">Terbitkan sertifikat</button></form>
    @else<span class="text-xs text-slate-400">Sertifikat tidak diaktifkan</span>@endif
@else<span class="text-xs text-slate-400">Tidak ada tindakan</span>@endif</td></tr>
@empty<tr><td colspan="5" class="p-10 text-center text-slate-500">Belum ada peserta pada filter ini.</td></tr>@endforelse</tbody></table></div><div class="mt-5">{{ $participants->links() }}</div>
@endsection
