@extends('layouts.manager')
@section('title', 'Activity · '.$organization->name)
@section('manager-content')
<x-workspace.page-header eyebrow="Operasional Community" title="Activity" :description="'Kelola usulan dan publikasi kegiatan '.$organization->name.'.'"><a class="btn-primary" href="{{ route('manager.activities.create', $organization) }}">Buat Activity</a></x-workspace.page-header>
<form method="GET" class="sipora-card mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-[minmax(0,1fr)_repeat(3,minmax(0,150px))_minmax(0,110px)_auto]" aria-label="Filter Activity">
    <div><label class="label" for="activity-search">Cari Activity</label><input id="activity-search" class="field" name="q" value="{{ $filters['q'] }}" maxlength="80" placeholder="Nama Activity"></div>
    @foreach(['review' => ['Review', ['draft' => 'Draft', 'pending_review' => 'Menunggu review', 'revision' => 'Perlu revisi', 'rejected' => 'Ditolak', 'approved' => 'Disetujui']], 'publication' => ['Publikasi', ['unpublished' => 'Belum terbit', 'published' => 'Terbit', 'archived' => 'Diarsipkan']], 'execution' => ['Pelaksanaan', ['scheduled' => 'Terjadwal', 'ongoing' => 'Berlangsung', 'completed' => 'Selesai', 'cancelled' => 'Dibatalkan']]] as $key => [$label, $options])
        <div><label class="label" for="activity-{{ $key }}">{{ $label }}</label><select id="activity-{{ $key }}" class="field" name="{{ $key }}"><option value="">Semua</option>@foreach($options as $value => $option)<option value="{{ $value }}" @selected($filters[$key] === $value)>{{ $option }}</option>@endforeach</select></div>
    @endforeach
    <div><label class="label" for="activity-per-page">Per halaman</label><select id="activity-per-page" class="field" name="per_page">@foreach([5, 15, 30] as $count)<option value="{{ $count }}" @selected($filters['per_page'] === $count)>{{ $count }}</option>@endforeach</select></div>
    <div class="flex items-end gap-2"><button class="btn-primary" type="submit">Terapkan</button><a class="btn-secondary" href="{{ route('manager.activities.index', $organization) }}">Reset</a></div>
</form>
<p class="mt-4 text-sm text-text-secondary">{{ $activities->total() }} Activity ditemukan</p>
<div class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
@forelse($activities as $activity)<a href="{{ route('manager.activities.show', [$organization,$activity]) }}" class="grid min-w-0 gap-3 border-b border-slate-100 p-4 transition hover:bg-slate-50 sm:grid-cols-[48px_1fr_auto] sm:items-center sm:p-5"><span class="grid size-12 shrink-0 place-items-center overflow-hidden rounded-xl bg-indigo-50 text-primary">@if($activity->poster_path)<img data-media-fallback class="size-full object-cover" src="{{ route('manager.activities.poster', [$organization, $activity]) }}" alt="">@else<x-ui.icon name="calendar" />@endif</span><span class="min-w-0"><strong class="block truncate text-primary-dark">{{ $activity->title }}</strong><span class="mt-1 block text-xs text-slate-500">{{ $activity->category?->name }} · {{ $activity->start_at->translatedFormat('d M Y, H:i') }}</span><span class="mt-2 flex flex-wrap gap-2"><x-activity.status-badge :status="$activity->review_status" /><x-activity.status-badge :status="$activity->publication_status" /><x-activity.status-badge :status="$activity->execution_status" /></span></span></a>@empty<div class="p-10 text-center"><p class="font-bold text-[#14205c]">Tidak ada Activity pada filter ini</p><p class="mt-2 text-sm text-slate-500">Coba ubah atau reset filter.</p></div>@endforelse
</div><div class="mt-5">{{ $activities->links() }}</div>
@endsection
