@extends('layouts.youth')
@section('title', 'Ruang Saya · SIPORA')
@section('content')
<div class="space-y-7">
    <x-workspace.page-header eyebrow="Overview" :title="'Selamat datang, '.($user->profile?->full_name ?? $user->name)" description="Kelola identitas, partisipasi, dan rekam pengalaman SIPORA dari satu ruang."><a class="btn-secondary" href="{{ route('home') }}"><x-ui.icon name="globe" />Jelajahi SIPORA</a></x-workspace.page-header>

    @if(! $onboarding['onboardingComplete'])
        @php($finished = collect([$onboarding['emailVerified'], $onboarding['biodataComplete'], $onboarding['identityVerified'], $onboarding['profileComplete'], $onboarding['portfolioBaselineComplete']])->filter()->count())
        <section class="sipora-card">
            <p class="text-xs font-extrabold uppercase tracking-widest text-interactive">Perjalanan Youth</p>
            <h2 class="mt-2 text-2xl font-extrabold text-text-primary">{{ $finished }} dari 5 tahap selesai</h2>
            <p class="mt-2 text-text-secondary">Selesaikan pengaturan akun untuk membuka pendaftaran Activity dan bergabung Community.</p>
            <div class="mt-5 h-3 overflow-hidden rounded-full bg-surface-soft" role="progressbar" aria-valuenow="{{ $finished }}" aria-valuemin="0" aria-valuemax="5" aria-label="Tahap onboarding selesai"><div class="h-full bg-interactive" style="width: {{ $finished * 20 }}%"></div></div>
            <div class="mt-6 flex flex-wrap gap-3"><a class="btn" href="{{ route($onboarding['nextAction']['route']) }}">{{ $onboarding['nextAction']['label'] }}</a><a class="btn-secondary" href="{{ route('youth.onboarding') }}">Lihat semua tahap</a><a class="btn-secondary" href="{{ route('home') }}">Jelajahi publik</a></div>
        </section>
        @if($onboarding['identityStatus'] === 'pending')<p class="rounded-xl border border-warning/30 bg-warning-soft p-4 text-sm text-text-primary">Pengajuan identitas sedang ditinjau Admin. Profil dan Portfolio terbuka setelah disetujui.</p>@endif
    @else

    <div class="media-profile-summary">@if($user->profile?->profile_photo_path)<img data-media-fallback src="{{ route('youth.profile.photo') }}" alt="Foto profil Anda">@endif<div><strong>{{ $user->profile?->full_name ?? $user->name }}</strong><p class="text-sm text-text-muted">Profil pribadi · kelola visibilitas melalui pengaturan privasi</p></div></div><section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3" aria-label="Ringkasan Ruang Saya">
        @foreach([['Profil lengkap',$completion['percentage'].'%','user','bg-indigo-50 text-primary',route('youth.profile.show')],['Pendaftaran aktif',$activeRegistrationCount,'activity','bg-blue-50 text-blue-700',route('youth.activities.index')],['Activity selesai',$passportCount,'badge-check','bg-emerald-50 text-emerald-700',route('youth.passport.index')],['Sertifikat',$certificateCount,'award','bg-orange-50 text-orange-700',route('youth.certificates.index')],['Community aktif',$communityCount,'building','bg-violet-50 text-violet-700',route('youth.communities.index')],['Opportunity tersimpan',$bookmarkCount,'bookmark','bg-amber-50 text-amber-700',route('youth.opportunities.bookmarks')]] as [$label,$value,$icon,$tone,$href])
            <a class="group rounded-2xl border border-indigo-100 bg-white p-4 shadow-card transition hover:-translate-y-0.5 hover:border-indigo-200" href="{{ $href }}"><div class="flex items-center gap-4"><span class="grid size-11 shrink-0 place-items-center rounded-xl {{ $tone }}"><x-ui.icon :name="$icon" /></span><div><p class="font-heading text-2xl font-bold leading-none text-text-primary">{{ $value }}</p><p class="mt-1 text-sm font-semibold text-text-secondary group-hover:text-primary">{{ $label }}</p></div></div></a>
        @endforeach
    </section>

    <div class="grid gap-7 xl:grid-cols-[minmax(0,1.35fr)_minmax(300px,.65fr)]">
        <div class="min-w-0 space-y-7">
            <section><div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-extrabold uppercase tracking-wider text-interactive">Activity</p><h2 class="mt-1 text-xl font-extrabold text-text-primary">Pendaftaran terbaru</h2></div><a class="public-section-link" href="{{ route('youth.activities.index') }}">Lihat semua <x-ui.icon name="chevron-right" class="size-4" /></a></div><div class="mt-4 divide-y divide-slate-100 rounded-2xl border border-indigo-100 bg-white px-5 shadow-card">@forelse($recentParticipations as $participation)<a class="flex min-h-20 items-center justify-between gap-4 py-4" href="{{ route('activities.show', $participation->activity) }}"><div class="min-w-0"><p class="truncate font-bold text-text-primary">{{ $participation->activity->title }}</p><p class="mt-1 truncate text-xs text-text-secondary">{{ $participation->activity->organization->name }} · {{ $participation->requested_at?->diffForHumans() }}</p></div><x-ui.badge :tone="$participation->registration_status === 'accepted' ? 'success' : ($participation->registration_status === 'pending' ? 'warning' : 'neutral')">{{ ucfirst($participation->registration_status) }}</x-ui.badge></a>@empty<div class="py-9 text-center text-sm text-slate-500">Belum ada pendaftaran Activity.</div>@endforelse</div></section>
            <section><div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-extrabold uppercase tracking-wider text-interactive">Verified experience</p><h2 class="mt-1 text-xl font-extrabold text-text-primary">Activity Passport terbaru</h2></div><a class="public-section-link" href="{{ route('youth.passport.index') }}">Buka Passport <x-ui.icon name="chevron-right" class="size-4" /></a></div><div class="mt-4 grid gap-3 sm:grid-cols-3">@forelse($recentPassportEntries as $entry)<a class="rounded-2xl border border-emerald-100 bg-emerald-50/60 p-4" href="{{ route('youth.passport.show', $entry) }}"><x-media.activity :activity="$entry->activity" class="mb-3" /><x-portfolio.provenance-badge verified /><p class="mt-3 font-bold text-text-primary">{{ $entry->activity->title }}</p><p class="mt-1 text-xs text-slate-600">{{ $entry->activity->organization->name }}</p></a>@empty<div class="sm:col-span-3"><x-ui.empty-state title="Passport masih kosong" description="Activity selesai yang telah disahkan akan muncul di sini." icon="badge-check" /></div>@endforelse</div></section>
        </div>
        <aside class="min-w-0 space-y-6">
            <section class="rounded-2xl border border-indigo-100 bg-white p-5 shadow-card"><div class="flex items-center justify-between gap-3"><h2 class="font-extrabold text-text-primary">Kelengkapan profil</h2><span class="font-heading text-2xl font-bold text-primary">{{ $completion['percentage'] }}%</span></div><div class="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-gradient-to-r from-primary to-interactive" style="width: {{ $completion['percentage'] }}%"></div></div>@if($completion['missing'])<p class="mt-4 text-xs leading-5 text-slate-500">Masih perlu: {{ collect($completion['missing'])->take(3)->map(fn($item) => str_replace('_', ' ', $item))->implode(', ') }}.</p>@endif<div class="mt-4 flex gap-2"><a class="btn-secondary !min-h-9 !px-3 text-sm" href="{{ route('youth.profile.show') }}">Lihat profil</a><a class="btn-secondary !min-h-9 !px-3 text-sm" href="{{ route('youth.profile.privacy') }}">Privasi</a></div></section>
            <section><div class="flex items-center justify-between"><h2 class="font-extrabold text-text-primary">Terbaru</h2><a class="text-xs font-bold text-primary" href="{{ route('notifications.index') }}">Semua notifikasi</a></div><div class="mt-3 space-y-2">@forelse($recentNotifications as $notification)<article class="rounded-xl border p-3 {{ $notification->read_at ? 'border-slate-200 bg-white' : 'border-indigo-200 bg-indigo-50' }}"><div class="flex gap-3"><span class="mt-1 size-2 shrink-0 rounded-full {{ $notification->read_at ? 'bg-slate-300' : 'bg-orange-500' }}"></span><div><p class="text-sm font-bold text-text-primary">{{ $notification->title }}</p><p class="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{{ $notification->body }}</p></div></div></article>@empty<p class="rounded-xl border border-dashed border-slate-200 p-5 text-center text-sm text-slate-500">Belum ada notifikasi.</p>@endforelse</div></section>
        </aside>
    </div>
    @endif
</div>
@endsection
