@extends('layouts.youth')
@section('title', 'Beranda Youth · SIPORA')
@section('content')
<div class="space-y-6">
<section class="overflow-hidden rounded-3xl bg-[#243378] p-6 text-white shadow-lg sm:p-8"><div class="max-w-3xl"><p class="text-sm font-semibold text-indigo-200">Beranda Youth</p><h1 class="mt-2 text-3xl font-extrabold sm:text-4xl">Halo, {{ $user->profile?->full_name ?? $user->name }}!</h1><p class="mt-2 text-indigo-100">@if($user->primaryDomicile){{ $user->primaryDomicile->administrativeArea->name }}, Kabupaten Pemalang @else Tambahkan domisili agar pengalamanmu lebih relevan. @endif</p><div class="mt-5 flex flex-wrap gap-2">@forelse($user->interests as $interest)<span class="rounded-full bg-white/15 px-3 py-1.5 text-sm font-semibold">{{ $interest->name }}</span>@empty<span class="rounded-full bg-white/15 px-3 py-1.5 text-sm">Belum ada minat dipilih</span>@endforelse</div></div></section>
<x-profile-completion :completion="$completion" />
<div class="grid gap-6 lg:grid-cols-[1fr_340px]">
<div class="space-y-6">
<section class="sipora-card"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-wider text-orange-600">Mulai dari sini</p><h2 class="mt-1 text-xl font-bold">Langkah berikutnya</h2></div><a class="text-sm font-bold text-[#243378]" href="{{ route('youth.profile.show') }}">Lihat profil →</a></div><div class="mt-5 grid gap-3 sm:grid-cols-3"><a href="{{ route('youth.interests.edit') }}" class="rounded-xl border border-slate-200 p-4 hover:border-indigo-300"><p class="font-bold">Atur minat</p><p class="mt-1 text-sm text-slate-600">Sesuaikan topik yang ingin kamu ikuti.</p></a><a href="{{ route('youth.identity-verification') }}" class="rounded-xl border border-slate-200 p-4 hover:border-indigo-300"><p class="font-bold">Identitas Youth</p><p class="mt-1 text-sm text-slate-600">Pelajari status dan dokumen yang akan diperlukan.</p></a><a href="{{ route('youth.communities.index') }}" class="rounded-xl border border-slate-200 p-4 hover:border-indigo-300"><p class="font-bold">Ajukan komunitas</p><p class="mt-1 text-sm text-slate-600">Buat dan kirim draft komunitas untuk diverifikasi.</p></a></div></section>
<section class="sipora-card"><h2 class="text-xl font-bold">Kegiatan untukmu</h2><div class="mt-5 rounded-2xl border-2 border-dashed border-slate-200 px-5 py-10 text-center"><p class="font-bold text-slate-700">Belum ada kegiatan untuk ditampilkan</p><p class="mx-auto mt-2 max-w-md text-sm text-slate-500">Katalog kegiatan akan hadir pada fase Activity. Data contoh tidak ditampilkan agar pengalamanmu selalu berdasarkan data SIPORA yang nyata.</p></div></section>
</div>
<aside class="space-y-6"><section class="sipora-card"><h2 class="font-bold">Status Youth</h2><div class="mt-4 flex items-center gap-3"><span class="grid size-10 place-items-center rounded-full {{ $user->identity?->verification_status === 'verified' ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700' }}">✓</span><div><p class="font-semibold">{{ ucfirst($user->identity?->verification_status ?? 'unverified') }}</p><p class="text-sm text-slate-500">Terpisah dari verifikasi email</p></div></div></section><section class="sipora-card"><h2 class="font-bold">Kelayakan usia</h2><p class="mt-3 text-sm text-slate-600">@if($eligibility['age'] === null)Lengkapi tanggal lahir untuk melihat status.@elseif($eligibility['eligible'])Usia {{ $eligibility['age'] }} tahun · termasuk segmen inti Youth 16–30.@else Usia {{ $eligibility['age'] }} tahun · di luar segmen inti, akun tetap dapat digunakan.@endif</p></section></aside>
</div></div>
@endsection
