@extends('layouts.youth')
@section('title', 'Lengkapi Profil · SIPORA')
@section('content')
@php($steps = ['profile' => 'Profil dasar', 'domicile' => 'Domisili', 'interests' => 'Minat', 'complete' => 'Selesai'])
<div class="mx-auto max-w-4xl">
<div class="text-center"><p class="text-xs font-bold uppercase tracking-wider text-orange-600">Onboarding Youth</p><h1 class="mt-2 text-3xl font-extrabold">Kenali dirimu lebih baik</h1><p class="mt-2 text-slate-600">Progres tersimpan di setiap langkah. Kamu tetap dapat memakai akun meski belum selesai.</p></div>
<ol class="my-7 grid grid-cols-4 gap-2" aria-label="Progres onboarding">@foreach($steps as $key=>$label)<li><a href="{{ route('youth.onboarding', ['step'=>$key]) }}" class="block rounded-xl border px-2 py-3 text-center text-xs font-semibold sm:text-sm {{ $step === $key ? 'border-[#3346a8] bg-[#eef0ff] text-[#243378]' : 'border-slate-200 bg-white text-slate-500' }}"><span class="hidden sm:inline">{{ $loop->iteration }}. </span>{{ $label }}</a></li>@endforeach</ol>
@if($step === 'profile')<section class="sipora-card"><h2 class="mb-5 text-xl font-bold">Profil dasar</h2><x-youth.profile-form :user="$user" :action="route('youth.onboarding.profile')" button="Simpan & lanjutkan" /></section>
@elseif($step === 'domicile')<section class="sipora-card"><h2 class="text-xl font-bold">Domisili saat ini</h2><p class="mt-2 text-sm text-slate-600">Kecamatan membantu menampilkan informasi lokal. Detail alamat tetap privat.</p><form class="mt-6 space-y-5" method="post" action="{{ route('youth.onboarding.domicile') }}">@csrf @method('PUT')<label><span class="field-label">Kecamatan</span><select class="field" name="administrative_area_id" required><option value="">Pilih kecamatan</option>@foreach($areas as $area)<option value="{{ $area->uuid() }}" @selected(old('administrative_area_id', $user->primaryDomicile?->administrativeArea?->uuid()) === $area->uuid())>{{ $area->name }}</option>@endforeach</select></label><label><span class="field-label">Alamat detail <span class="font-normal text-slate-500">(opsional dan privat)</span></span><textarea class="field" name="address_line" maxlength="500">{{ old('address_line', $user->primaryDomicile?->address_line) }}</textarea></label><div class="grid gap-5 sm:grid-cols-3"><label><span class="field-label">RT</span><input class="field" name="rt" value="{{ old('rt', $user->primaryDomicile?->rt) }}" inputmode="numeric" maxlength="4"></label><label><span class="field-label">RW</span><input class="field" name="rw" value="{{ old('rw', $user->primaryDomicile?->rw) }}" inputmode="numeric" maxlength="4"></label><label><span class="field-label">Kode pos</span><input class="field" name="postal_code" value="{{ old('postal_code', $user->primaryDomicile?->postal_code) }}" inputmode="numeric" maxlength="10"></label></div><div class="flex justify-end"><button class="btn" type="submit">Simpan & lanjutkan</button></div></form></section>
@elseif($step === 'interests')<section class="sipora-card"><h2 class="text-xl font-bold">Pilih minatmu</h2><p class="mt-2 text-sm text-slate-600">Pilih minimal satu minat. Kamu dapat mengubahnya kapan saja.</p><form class="mt-6" method="post" action="{{ route('youth.onboarding.interests') }}">@csrf @method('PUT')<div class="grid gap-3 sm:grid-cols-2">@foreach($interests as $interest)<label class="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-4 has-checked:border-[#3346a8] has-checked:bg-[#eef0ff]"><input class="size-5 accent-[#243378]" type="checkbox" name="interests[]" value="{{ $interest->uuid() }}" @checked(in_array($interest->uuid(), old('interests', $user->interests->map->uuid()->all())))><span class="font-semibold">{{ $interest->name }}</span></label>@endforeach</div><div class="mt-6 flex justify-end"><button class="btn" type="submit">Simpan & lanjutkan</button></div></form></section>
@else<section class="sipora-card text-center"><div class="mx-auto grid size-16 place-items-center rounded-full bg-green-100 text-2xl text-green-700">✓</div><h2 class="mt-4 text-2xl font-extrabold">Profil dasar siap</h2><p class="mx-auto mt-2 max-w-xl text-slate-600">Kamu dapat memperbarui profil, minat, dan privasi kapan saja. Verifikasi identitas Youth tetap merupakan proses terpisah.</p><div class="mt-6 flex flex-wrap justify-center gap-3"><a class="btn" href="{{ route('youth.home') }}">Ke Beranda Youth</a><a class="btn-secondary" href="{{ route('youth.profile.show') }}">Lihat profil</a></div></section>@endif
<div class="mt-6"><x-profile-completion :completion="$completion" /></div>
</div>
@endsection
