<?php

use App\Http\Controllers\Manager\ActivityAttendanceController;
use App\Http\Controllers\Manager\ActivityController;
use App\Http\Controllers\Manager\ActivityParticipantController;
use App\Http\Controllers\Manager\ActivitySessionController;
use App\Http\Controllers\Manager\CommunityMemberController;
use App\Http\Controllers\Manager\CommunityWorkspaceController;
use App\Http\Controllers\Manager\FinancialReportController;
use App\Http\Controllers\Manager\ProgramController;
use App\Http\Controllers\Manager\ProgramLogbookController;
use App\Http\Controllers\Manager\ProgramProposalController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'verified', 'role:youth'])->prefix('manage')->name('manager.')
    ->group(function (): void {
        Route::get('/{organization}', [CommunityWorkspaceController::class, 'show'])->name('dashboard');
        Route::get('/{organization}/profile', [CommunityWorkspaceController::class, 'edit'])->name('profile.edit');
        Route::patch('/{organization}/profile', [CommunityWorkspaceController::class, 'update'])->name('profile.update');
        Route::get('/{organization}/members', [CommunityMemberController::class, 'index'])->name('members.index');
        Route::post('/{organization}/join-requests/{membership}/review', [CommunityMemberController::class, 'review'])->name('join-requests.review');
        Route::patch('/{organization}/members/{membership}/role', [CommunityMemberController::class, 'updateRole'])->name('members.role.update');
        Route::delete('/{organization}/members/{membership}', [CommunityMemberController::class, 'destroy'])->name('members.destroy');
        Route::get('/{organization}/programs', [ProgramController::class, 'index'])->name('programs.index');
        Route::get('/{organization}/programs/create', [ProgramController::class, 'create'])->name('programs.create');
        Route::post('/{organization}/programs', [ProgramController::class, 'store'])->name('programs.store');
        Route::get('/{organization}/programs/{program}', [ProgramController::class, 'show'])->name('programs.show');
        Route::get('/{organization}/programs/{program}/edit', [ProgramController::class, 'edit'])->name('programs.edit');
        Route::patch('/{organization}/programs/{program}', [ProgramController::class, 'update'])->name('programs.update');
        Route::post('/{organization}/programs/{program}/start-execution', [ProgramController::class, 'startExecution'])->name('programs.start-execution');
        Route::get('/{organization}/programs/{program}/proposal/create', [ProgramProposalController::class, 'create'])->name('program-proposals.create');
        Route::post('/{organization}/programs/{program}/proposal', [ProgramProposalController::class, 'store'])->name('program-proposals.store');
        Route::get('/{organization}/programs/{program}/proposals/{proposal}/edit', [ProgramProposalController::class, 'edit'])->name('program-proposals.edit');
        Route::patch('/{organization}/programs/{program}/proposals/{proposal}', [ProgramProposalController::class, 'update'])->name('program-proposals.update');
        Route::post('/{organization}/programs/{program}/proposals/{proposal}/submit', [ProgramProposalController::class, 'submit'])->name('program-proposals.submit');
        Route::post('/{organization}/programs/{program}/proposals/{proposal}/revise', [ProgramProposalController::class, 'revise'])->name('program-proposals.revise');
        Route::get('/{organization}/programs/{program}/proposals/{proposal}/document', [ProgramProposalController::class, 'document'])->name('program-proposals.document');
        Route::get('/{organization}/programs/{program}/logbooks', [ProgramLogbookController::class, 'index'])->name('program-logbooks.index');
        Route::get('/{organization}/programs/{program}/logbooks/create', [ProgramLogbookController::class, 'create'])->name('program-logbooks.create');
        Route::post('/{organization}/programs/{program}/logbooks', [ProgramLogbookController::class, 'store'])->name('program-logbooks.store');
        Route::get('/{organization}/programs/{program}/logbooks/{logbook}', [ProgramLogbookController::class, 'show'])->name('program-logbooks.show');
        Route::get('/{organization}/programs/{program}/logbooks/{logbook}/edit', [ProgramLogbookController::class, 'edit'])->name('program-logbooks.edit');
        Route::patch('/{organization}/programs/{program}/logbooks/{logbook}', [ProgramLogbookController::class, 'update'])->name('program-logbooks.update');
        Route::delete('/{organization}/programs/{program}/logbooks/{logbook}', [ProgramLogbookController::class, 'destroy'])->name('program-logbooks.destroy');
        Route::post('/{organization}/programs/{program}/logbooks/{logbook}/submit', [ProgramLogbookController::class, 'submit'])->name('program-logbooks.submit');
        Route::post('/{organization}/programs/{program}/logbooks/{logbook}/media', [ProgramLogbookController::class, 'storeMedia'])->name('program-logbooks.media.store');
        Route::get('/{organization}/programs/{program}/logbooks/{logbook}/media/{media}', [ProgramLogbookController::class, 'media'])->name('program-logbooks.media.show');
        Route::delete('/{organization}/programs/{program}/logbooks/{logbook}/media/{media}', [ProgramLogbookController::class, 'destroyMedia'])->name('program-logbooks.media.destroy');
        Route::get('/{organization}/programs/{program}/financial-report/create', [FinancialReportController::class, 'create'])->name('financial-reports.create');
        Route::post('/{organization}/programs/{program}/financial-report', [FinancialReportController::class, 'store'])->name('financial-reports.store');
        Route::get('/{organization}/programs/{program}/financial-reports/{report}', [FinancialReportController::class, 'show'])->name('financial-reports.show');
        Route::get('/{organization}/programs/{program}/financial-reports/{report}/edit', [FinancialReportController::class, 'edit'])->name('financial-reports.edit');
        Route::patch('/{organization}/programs/{program}/financial-reports/{report}', [FinancialReportController::class, 'update'])->name('financial-reports.update');
        Route::post('/{organization}/programs/{program}/financial-reports/{report}/revise', [FinancialReportController::class, 'revise'])->name('financial-reports.revise');
        Route::post('/{organization}/programs/{program}/financial-reports/{report}/submit', [FinancialReportController::class, 'submit'])->name('financial-reports.submit');
        Route::post('/{organization}/programs/{program}/financial-reports/{report}/items', [FinancialReportController::class, 'storeItem'])->name('financial-reports.items.store');
        Route::patch('/{organization}/programs/{program}/financial-reports/{report}/items/{item}', [FinancialReportController::class, 'updateItem'])->name('financial-reports.items.update');
        Route::delete('/{organization}/programs/{program}/financial-reports/{report}/items/{item}', [FinancialReportController::class, 'destroyItem'])->name('financial-reports.items.destroy');
        Route::get('/{organization}/programs/{program}/financial-reports/{report}/items/{item}/receipt', [FinancialReportController::class, 'receipt'])->name('financial-reports.items.receipt');
        Route::get('/{organization}/activities', [ActivityController::class, 'index'])->name('activities.index');
        Route::get('/{organization}/activities/create', [ActivityController::class, 'create'])->name('activities.create');
        Route::post('/{organization}/activities', [ActivityController::class, 'store'])->name('activities.store');
        Route::get('/{organization}/activities/{activity}', [ActivityController::class, 'show'])->name('activities.show');
        Route::get('/{organization}/activities/{activity}/edit', [ActivityController::class, 'edit'])->name('activities.edit');
        Route::patch('/{organization}/activities/{activity}', [ActivityController::class, 'update'])->name('activities.update');
        Route::post('/{organization}/activities/{activity}/submit', [ActivityController::class, 'submit'])->name('activities.submit');
        Route::post('/{organization}/activities/{activity}/publish', [ActivityController::class, 'publish'])->name('activities.publish');
        Route::post('/{organization}/activities/{activity}/archive', [ActivityController::class, 'archive'])->name('activities.archive');
        Route::post('/{organization}/activities/{activity}/complete-execution', [ActivityController::class, 'completeExecution'])->name('activities.complete-execution');
        Route::get('/{organization}/activities/{activity}/poster', [ActivityController::class, 'poster'])->name('activities.poster');
        Route::get('/{organization}/activities/{activity}/sessions', [ActivitySessionController::class, 'index'])->name('activities.sessions.index');
        Route::get('/{organization}/activities/{activity}/sessions/create', [ActivitySessionController::class, 'create'])->name('activities.sessions.create');
        Route::post('/{organization}/activities/{activity}/sessions', [ActivitySessionController::class, 'store'])->name('activities.sessions.store');
        Route::get('/{organization}/activities/{activity}/sessions/{session}/edit', [ActivitySessionController::class, 'edit'])->name('activities.sessions.edit');
        Route::patch('/{organization}/activities/{activity}/sessions/{session}', [ActivitySessionController::class, 'update'])->name('activities.sessions.update');
        Route::patch('/{organization}/activities/{activity}/sessions/{session}/move', [ActivitySessionController::class, 'move'])->name('activities.sessions.move');
        Route::delete('/{organization}/activities/{activity}/sessions/{session}', [ActivitySessionController::class, 'destroy'])->name('activities.sessions.destroy');
        Route::get('/{organization}/activities/{activity}/participants', [ActivityParticipantController::class, 'index'])->name('activities.participants.index');
        Route::post('/{organization}/activities/{activity}/participants/{participation}/review', [ActivityParticipantController::class, 'review'])->name('activities.participants.review');
        Route::post('/{organization}/activities/{activity}/participants/{participation}/completion', [ActivityParticipantController::class, 'complete'])->name('activities.participants.complete');
        Route::post('/{organization}/activities/{activity}/participants/{participation}/certificate', [ActivityParticipantController::class, 'issueCertificate'])->name('activities.participants.certificate');
        Route::get('/{organization}/activities/{activity}/sessions/{session}/attendance', [ActivityAttendanceController::class, 'index'])->name('activities.attendance.index');
        Route::put('/{organization}/activities/{activity}/sessions/{session}/attendance/{participation}', [ActivityAttendanceController::class, 'update'])->name('activities.attendance.update');
    });
