@extends('layouts.admin')
@section('title', 'Antrean Verifikasi Identitas · SIPORA')
@section('content')
<div class="mx-auto max-w-7xl">
    <p class="text-sm font-semibold text-slate-500">Beranda Super Admin <span class="mx-2">›</span> Verifikasi Identitas</p>
    <div class="mt-3 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-[#f59e0b]">KYC Pemuda</p><h1 class="mt-2 text-3xl font-black tracking-tight text-[#18245c] sm:text-4xl">Antrean Verifikasi Identitas</h1><p class="mt-3 max-w-2xl text-slate-600">Tinjau data minimum di antrean, lalu buka detail untuk memeriksa dokumen privat.</p></div><span class="rounded-full bg-indigo-100 px-4 py-2 text-sm font-extrabold text-[#243378]">{{ $counts['pending'] ?? 0 }} menunggu</span></div>

    <div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach(['pending' => ['Menunggu', 'amber'], 'revision' => ['Perlu revisi', 'blue'], 'verified' => ['Disetujui', 'emerald'], 'rejected' => ['Ditolak', 'red']] as $key => [$label, $tone])<a href="{{ route('admin.identity-verifications.index', ['status' => $key]) }}" class="sipora-card !p-5"><span class="text-xs font-black uppercase tracking-wider text-slate-400">{{ $label }}</span><strong class="mt-2 block text-3xl text-[#18245c]">{{ $counts[$key] ?? 0 }}</strong></a>@endforeach</div>

    <section class="sipora-card mt-7">
        <form method="get" class="grid gap-3 md:grid-cols-[1fr_220px_auto]"><label><span class="sr-only">Cari nama atau email</span><input class="field" type="search" name="search" value="{{ $search }}" placeholder="Cari nama atau email pemuda"></label><label><span class="sr-only">Filter status</span><select class="field" name="status">@foreach(['pending'=>'Menunggu','revision'=>'Perlu revisi','verified'=>'Disetujui','rejected'=>'Ditolak','all'=>'Semua status'] as $value=>$label)<option value="{{ $value }}" @selected($status === $value)>{{ $label }}</option>@endforeach</select></label><button class="btn" type="submit">Terapkan filter</button></form>
        <div class="mt-6 overflow-x-auto"><table class="w-full min-w-[760px] text-left text-sm"><thead><tr class="border-b border-slate-200 text-xs uppercase tracking-wider text-slate-400"><th class="px-3 py-4">Pemuda</th><th class="px-3 py-4">Dokumen</th><th class="px-3 py-4">Diajukan</th><th class="px-3 py-4">Status</th><th class="px-3 py-4 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($submissions as $submission)@php($applicant = $submission->userIdentity->user)<tr><td class="px-3 py-5"><strong class="block text-[#18245c]">{{ $applicant->profile?->full_name ?? $applicant->name }}</strong><span class="text-slate-500">{{ $applicant->email }}</span></td><td class="px-3 py-5 font-bold uppercase">{{ str_replace('_', ' ', $submission->document_type) }}</td><td class="px-3 py-5 text-slate-600">{{ $submission->submitted_at->format('d M Y, H:i') }}</td><td class="px-3 py-5"><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{{ ucfirst($submission->status) }}</span></td><td class="px-3 py-5 text-right"><a class="font-bold text-[#3346a8]" href="{{ route('admin.identity-verifications.show', $submission) }}">Tinjau →</a></td></tr>@empty<tr><td colspan="5" class="px-3 py-12 text-center text-slate-500">Tidak ada pengajuan untuk filter ini.</td></tr>@endforelse</tbody></table></div>
        <div class="mt-6">{{ $submissions->links() }}</div>
    </section>
</div>
@endsection
