@extends('layouts.admin')
@section('title', 'Tinjau Verifikasi Identitas · SIPORA')
@section('content')
@php($applicant = $submission->userIdentity->user)
<div class="mx-auto max-w-7xl">
    <a href="{{ route('admin.identity-verifications.index') }}" class="text-sm font-bold text-[#3346a8]">← Kembali ke antrean</a>
    <div class="mt-5 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-[#f59e0b]">Detail Pengajuan</p><h1 class="mt-2 text-3xl font-black tracking-tight text-[#18245c]">Tinjau Identitas Pemuda</h1></div><span class="w-fit rounded-full bg-indigo-100 px-4 py-2 text-sm font-extrabold text-[#243378]">{{ ucfirst($submission->status) }}</span></div>
    <div class="mt-7 grid gap-7 xl:grid-cols-[.8fr_1.2fr]">
        <div class="space-y-7">
            <section class="sipora-card"><div class="flex items-center gap-4"><span class="grid size-14 place-items-center rounded-xl bg-[#243378] font-black text-white">{{ str($applicant->name)->substr(0, 2)->upper() }}</span><div><h2 class="text-xl font-extrabold text-[#18245c]">{{ $applicant->profile?->full_name ?? $applicant->name }}</h2><p class="text-sm text-slate-500">{{ $applicant->email }}</p></div></div><dl class="mt-6 grid gap-5 border-t border-slate-100 pt-6 sm:grid-cols-2"><div><dt class="text-xs font-bold uppercase tracking-wider text-slate-400">Jenis dokumen</dt><dd class="mt-1 font-bold uppercase">{{ str_replace('_', ' ', $submission->document_type) }}</dd></div><div><dt class="text-xs font-bold uppercase tracking-wider text-slate-400">Diajukan</dt><dd class="mt-1 font-semibold">{{ $submission->submitted_at->format('d M Y, H:i') }}</dd></div><div class="sm:col-span-2"><dt class="text-xs font-bold uppercase tracking-wider text-slate-400">Nomor dokumen</dt><dd class="mt-1 break-all font-mono font-bold">{{ $documentNumber }}</dd></div>@if($applicant->primaryDomicile)<div class="sm:col-span-2"><dt class="text-xs font-bold uppercase tracking-wider text-slate-400">Domisili profil</dt><dd class="mt-1">{{ $applicant->primaryDomicile->administrativeArea->name }}</dd></div>@endif</dl></section>
            @if($submission->review_notes || $previousReview?->review_notes)<section class="sipora-card"><h2 class="font-extrabold text-[#18245c]">Catatan keputusan sebelumnya</h2><p class="mt-3 whitespace-pre-line text-slate-600">{{ $submission->review_notes ?? $previousReview->review_notes }}</p></section>@endif
        </div>
        <div class="space-y-7">
            <section class="sipora-card"><div class="flex items-center justify-between gap-4"><div><h2 class="text-xl font-extrabold text-[#18245c]">Dokumen Privat</h2><p class="mt-1 text-sm text-slate-500">Hanya tersedia selama sesi Admin yang terotorisasi.</p></div><a href="{{ route('admin.identity-verifications.document', $submission) }}" target="_blank" rel="noopener" class="btn-secondary !min-h-10">Buka penuh</a></div><iframe title="Dokumen identitas pengajuan" class="mt-5 h-[520px] w-full rounded-xl border border-slate-200 bg-slate-100" src="{{ route('admin.identity-verifications.document', $submission) }}"></iframe></section>
            @if($submission->status === 'pending')<section x-data="{ decision: 'verified' }" class="sipora-card"><h2 class="text-xl font-extrabold text-[#18245c]">Keputusan Admin</h2><p class="mt-2 text-sm text-slate-600">Periksa dokumen dan data sebelum menyimpan keputusan. Keputusan terminal tidak dapat diulang.</p><form method="post" action="{{ route('admin.identity-verifications.review', $submission) }}" class="mt-6 space-y-5">@csrf<input type="hidden" name="decision" :value="decision"><div class="grid gap-3 sm:grid-cols-3"><button type="button" @click="decision='verified'" :class="decision === 'verified' ? 'border-emerald-500 bg-emerald-50 text-emerald-800' : 'border-slate-200'" class="rounded-xl border p-4 font-bold">✓ Setujui</button><button type="button" @click="decision='revision'" :class="decision === 'revision' ? 'border-blue-500 bg-blue-50 text-blue-800' : 'border-slate-200'" class="rounded-xl border p-4 font-bold">↻ Minta Revisi</button><button type="button" @click="decision='rejected'" :class="decision === 'rejected' ? 'border-red-500 bg-red-50 text-red-800' : 'border-slate-200'" class="rounded-xl border p-4 font-bold">✕ Tolak</button></div><label><span class="field-label">Catatan keputusan <span x-show="decision !== 'verified'" class="text-red-600">*</span></span><textarea class="field" name="review_notes" rows="4" maxlength="2000" :required="decision !== 'verified'" placeholder="Jelaskan bagian yang perlu diperbaiki atau alasan penolakan.">{{ old('review_notes') }}</textarea></label><button class="btn w-full" type="submit">Simpan keputusan</button></form></section>@else<section class="sipora-card"><h2 class="font-extrabold text-[#18245c]">Keputusan telah disimpan</h2><p class="mt-2 text-slate-600">Ditinjau {{ $submission->reviewed_at?->format('d M Y, H:i') }} oleh {{ $submission->reviewer?->name ?? 'Admin SIPORA' }}.</p></section>@endif
        </div>
    </div>
</div>
@endsection
