@props(['user', 'action', 'button' => 'Simpan profil'])
<form action="{{ $action }}" method="post" enctype="multipart/form-data" class="space-y-5">@csrf @method('PUT')
<div class="grid gap-5 sm:grid-cols-2">
<label><span class="field-label">Nama lengkap</span><input class="field" name="full_name" value="{{ old('full_name', $user->profile?->full_name ?? $user->name) }}" required maxlength="160">@error('full_name')<span class="field-error">{{ $message }}</span>@enderror</label>
<label><span class="field-label">Tempat lahir</span><input class="field" name="birth_place" value="{{ old('birth_place', $user->profile?->birth_place) }}" maxlength="120">@error('birth_place')<span class="field-error">{{ $message }}</span>@enderror</label>
<label><span class="field-label">Tanggal lahir</span><input class="field" type="date" name="birth_date" value="{{ old('birth_date', $user->profile?->birth_date?->format('Y-m-d')) }}" min="1900-01-01" max="{{ now()->format('Y-m-d') }}" required>@error('birth_date')<span class="field-error">{{ $message }}</span>@enderror</label>
<label><span class="field-label">Gender</span><select class="field" name="gender"><option value="">Pilih</option>@foreach(['male'=>'Laki-laki','female'=>'Perempuan','other'=>'Lainnya','prefer_not_to_say'=>'Tidak ingin menyebutkan'] as $value=>$label)<option value="{{ $value }}" @selected(old('gender', $user->profile?->gender)===$value)>{{ $label }}</option>@endforeach</select>@error('gender')<span class="field-error">{{ $message }}</span>@enderror</label>
<label><span class="field-label">Nomor telepon</span><input class="field" type="tel" name="phone" value="{{ old('phone', $user->profile?->phone) }}" placeholder="+62 812 3456 7890">@error('phone')<span class="field-error">{{ $message }}</span>@enderror</label>
<label><span class="field-label">Status saat ini</span><select class="field" name="occupation_status"><option value="">Pilih</option>@foreach(['student'=>'Pelajar','university_student'=>'Mahasiswa','worker'=>'Pekerja','entrepreneur'=>'Wirausaha','unemployed'=>'Belum bekerja','other'=>'Lainnya'] as $value=>$label)<option value="{{ $value }}" @selected(old('occupation_status', $user->profile?->occupation_status)===$value)>{{ $label }}</option>@endforeach</select>@error('occupation_status')<span class="field-error">{{ $message }}</span>@enderror</label>
</div>
<label><span class="field-label">Pekerjaan / institusi</span><input class="field" name="occupation_title" value="{{ old('occupation_title', $user->profile?->occupation_title) }}" maxlength="160"></label>
<label><span class="field-label">Bio singkat</span><textarea class="field min-h-28" name="bio" maxlength="2000" placeholder="Ceritakan minat dan tujuanmu">{{ old('bio', $user->profile?->bio) }}</textarea>@error('bio')<span class="field-error">{{ $message }}</span>@enderror</label>
<label><span class="field-label">Foto profil publik <span class="font-normal text-slate-500">(opsional, maks. 2 MB)</span></span><input class="field file:mr-3 file:rounded-lg file:border-0 file:bg-[#eef0ff] file:px-3 file:py-2 file:font-semibold file:text-[#243378]" type="file" name="profile_photo" accept="image/jpeg,image/png,image/webp">@error('profile_photo')<span class="field-error">{{ $message }}</span>@enderror</label>
<div class="flex justify-end"><button class="btn" type="submit">{{ $button }}</button></div></form>
