@extends('layouts.manager')
@section('title', 'Anggota '.$organization->name.' · SIPORA')
@section('manager-content')
<div class="space-y-6"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-bold text-orange-600">{{ $organization->name }}</p><h1 class="mt-1 text-3xl font-extrabold text-[#142565]">Anggota & permintaan bergabung</h1><p class="mt-2 text-slate-600">Akses Anda: <span class="font-bold capitalize">{{ $actorMembership->access_role }}</span></p></div><a class="btn-secondary" href="{{ route('communities.show', $organization) }}">Lihat halaman publik</a></div>

<section id="permintaan" class="sipora-card scroll-mt-28 border-t-4 border-t-orange-500"><div class="flex items-center justify-between"><h2 class="text-xl font-bold text-[#243378]">Permintaan tertunda</h2><span class="rounded-full bg-orange-100 px-3 py-1 text-sm font-bold text-orange-800">{{ $pending->count() }}</span></div><div class="mt-5 space-y-3">@forelse($pending as $request)<div class="flex flex-col justify-between gap-4 rounded-xl border border-slate-200 p-4 sm:flex-row sm:items-center"><div><p class="font-bold">{{ $request->user->profile?->full_name ?? $request->user->name }}</p><p class="text-sm text-slate-500">{{ $request->user->email }} · {{ $request->requested_at->format('d M Y, H:i') }}</p></div><div class="flex gap-2"><form method="post" action="{{ route('manager.join-requests.review', [$organization, $request]) }}">@csrf<input type="hidden" name="decision" value="accepted"><button class="btn !min-h-9 !bg-emerald-700 !px-4 !py-1.5 text-sm" type="submit">Terima</button></form><form method="post" action="{{ route('manager.join-requests.review', [$organization, $request]) }}">@csrf<input type="hidden" name="decision" value="rejected"><button class="btn-secondary !min-h-9 !border-red-300 !px-4 !py-1.5 text-sm !text-red-700" type="submit">Tolak</button></form></div></div>@empty<p class="rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-500">Tidak ada permintaan tertunda.</p>@endforelse</div></section>

<section class="sipora-card"><h2 class="text-xl font-bold text-[#243378]">Anggota aktif</h2><div class="mt-5 overflow-x-auto"><table class="w-full min-w-[700px] text-left text-sm"><thead class="border-y border-slate-200 bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-4 py-3">Anggota</th><th class="px-4 py-3">Peran</th><th class="px-4 py-3">Bergabung</th><th class="px-4 py-3">Tindakan</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($members as $member)<tr><td class="px-4 py-4"><p class="font-bold">{{ $member->user->profile?->full_name ?? $member->user->name }}</p><p class="text-xs text-slate-500">{{ $member->user->email }}</p></td><td class="px-4 py-4"><span class="rounded-full px-3 py-1 text-xs font-bold {{ $member->access_role === 'leader' ? 'bg-orange-100 text-orange-800' : ($member->access_role === 'manager' ? 'bg-indigo-100 text-indigo-800' : 'bg-slate-100 text-slate-700') }}">{{ ucfirst($member->access_role) }}</span></td><td class="px-4 py-4">{{ $member->approved_at?->format('d M Y') ?? '—' }}</td><td class="px-4 py-4"><div class="flex items-center gap-2">@if($actorMembership->access_role === 'leader' && $member->access_role !== 'leader')<form class="flex gap-2" method="post" action="{{ route('manager.members.role.update', [$organization, $member]) }}">@csrf @method('PATCH')<select class="field !min-h-9 !py-1 text-sm" name="access_role"><option value="member" @selected($member->access_role === 'member')>Member</option><option value="manager" @selected($member->access_role === 'manager')>Manager</option></select><button class="btn-secondary !min-h-9 !px-3 !py-1 text-sm" type="submit">Simpan</button></form>@endif @if($member->access_role !== 'leader' && $member->user_id !== auth()->id())<form method="post" action="{{ route('manager.members.destroy', [$organization, $member]) }}">@csrf @method('DELETE')<button class="text-sm font-bold text-red-700" type="submit">Keluarkan</button></form>@endif</div></td></tr>@endforeach</tbody></table></div><div class="mt-5">{{ $members->links() }}</div></section></div>
@endsection
