@extends('layouts.verifier')
@section('title', 'Verifikasi Proposal Program')
@section('verifier-content')
<div class="space-y-6">
    <header><p class="text-sm font-bold text-orange-600">VERIFIKASI PROGRAM</p><h1 class="mt-1 text-3xl font-black text-[#14205c]">Antrean Proposal</h1><p class="mt-2 text-slate-600">Tinjau dokumen resmi Program yang diajukan komunitas.</p></header>
    <form method="GET" class="grid gap-3 rounded-2xl bg-white p-4 shadow-sm sm:grid-cols-[1fr_200px_auto]"><label class="sr-only" for="search">Cari</label><input class="field" id="search" name="search" value="{{ $search }}" placeholder="Cari Program atau komunitas"><label class="sr-only" for="status">Status</label><select class="field" id="status" name="status"><option value="submitted" @selected($status === 'submitted')>Diajukan</option><option value="under_review" @selected($status === 'under_review')>Sedang ditinjau</option><option value="approved" @selected($status === 'approved')>Disetujui</option><option value="revision" @selected($status === 'revision')>Perlu revisi</option><option value="rejected" @selected($status === 'rejected')>Ditolak</option><option value="all" @selected($status === 'all')>Semua</option></select><button class="btn-primary">Terapkan</button></form>
    <section class="overflow-hidden rounded-2xl bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-left text-sm"><thead class="bg-[#eef0ff] text-xs font-extrabold uppercase text-[#243378]"><tr><th class="px-5 py-4">Program</th><th class="px-5 py-4">Komunitas</th><th class="px-5 py-4">Pengaju</th><th class="px-5 py-4">Versi</th><th class="px-5 py-4">Diajukan</th><th class="px-5 py-4">Status</th><th class="px-5 py-4"></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($proposals as $proposal)<tr><td class="px-5 py-4 font-bold text-[#14205c]">{{ $proposal->program->title }}</td><td class="px-5 py-4 text-slate-600">{{ $proposal->program->organization->name }}</td><td class="px-5 py-4 text-slate-600">{{ $proposal->submissionActivity?->causer?->name ?? '—' }}</td><td class="px-5 py-4">v{{ $proposal->version }}</td><td class="px-5 py-4 text-slate-600">{{ $proposal->submitted_at?->translatedFormat('d M Y, H:i') ?? '—' }}</td><td class="px-5 py-4"><x-program.proposal-status-badge :status="$proposal->status" /></td><td class="px-5 py-4 text-right"><a class="font-bold text-[#243378] hover:underline" href="{{ route('verifier.program-proposals.show', $proposal) }}">Tinjau</a></td></tr>@empty<tr><td colspan="7" class="px-5 py-12 text-center text-slate-500">Tidak ada Proposal pada antrean ini.</td></tr>@endforelse</tbody></table></div></section>
    {{ $proposals->links() }}
</div>
@endsection
