@extends('layouts.verifier')
@section('title', 'Tinjau Proposal '.$proposal->program->title)
@section('verifier-content')
<div class="space-y-6">
    <a class="text-sm font-bold text-[#243378] hover:underline" href="{{ route('verifier.program-proposals.index') }}">← Kembali ke antrean</a>
    <section class="overflow-hidden rounded-2xl bg-white shadow-sm"><div class="border-b border-indigo-100 bg-gradient-to-r from-[#eef0ff] to-white p-6"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-bold text-orange-600">PROPOSAL PROGRAM · VERSI {{ $proposal->version }}</p><h1 class="mt-1 text-3xl font-black text-[#14205c]">{{ $proposal->program->title }}</h1><p class="mt-2 text-slate-600">{{ $proposal->program->organization->name }}</p></div><x-program.proposal-status-badge :status="$proposal->status" /></div></div>
        <div class="space-y-6 p-6"><dl class="grid gap-4 rounded-xl bg-slate-50 p-5 sm:grid-cols-3"><div><dt class="text-xs font-bold uppercase text-slate-500">Kategori</dt><dd class="mt-1 font-semibold text-[#14205c]">{{ $proposal->program->category?->name }}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-500">Anggaran diajukan</dt><dd class="mt-1 font-semibold text-[#14205c]">{{ $proposal->requested_budget !== null ? 'Rp '.number_format((float) $proposal->requested_budget, 0, ',', '.') : 'Tidak dicantumkan' }}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-500">Diajukan</dt><dd class="mt-1 font-semibold text-[#14205c]">{{ $proposal->submitted_at?->translatedFormat('d M Y, H:i') ?? '—' }}</dd></div></dl>
            <p class="text-sm text-slate-600"><span class="font-bold text-[#14205c]">Pengaju:</span> {{ $proposal->submissionActivity?->causer?->name ?? 'Tidak tercatat pada fixture lama' }}</p>
            <div class="grid gap-6 lg:grid-cols-2"><div><h2 class="font-extrabold text-[#14205c]">Deskripsi</h2><p class="mt-2 whitespace-pre-line leading-7 text-slate-600">{{ $proposal->program->description ?: 'Tidak tersedia.' }}</p></div><div><h2 class="font-extrabold text-[#14205c]">Tujuan</h2><p class="mt-2 whitespace-pre-line leading-7 text-slate-600">{{ $proposal->program->objectives ?: 'Tidak tersedia.' }}</p></div></div>
            <div><h2 class="font-extrabold text-[#14205c]">Komposisi Activity ({{ $proposal->program->activities->count() }})</h2><div class="mt-3 space-y-2">@foreach($proposal->program->activities as $activity)<div class="rounded-lg border border-slate-200 px-4 py-3"><p class="font-bold text-[#14205c]">{{ $activity->title }}</p><p class="text-sm text-slate-500">{{ $activity->category?->name }} · {{ $activity->start_at->translatedFormat('d M Y') }}</p></div>@endforeach</div></div>
            <a class="btn-secondary inline-flex" target="_blank" href="{{ route('verifier.program-proposals.document', $proposal) }}">Buka dokumen Proposal</a>
            @if($proposal->review_notes)<div class="rounded-xl border border-orange-200 bg-orange-50 p-4"><p class="text-xs font-bold uppercase text-orange-700">Catatan keputusan</p><p class="mt-1 text-sm text-slate-700">{{ $proposal->review_notes }}</p></div>@endif
        </div>
    </section>
    @can('review', $proposal)<form method="POST" action="{{ route('verifier.program-proposals.review', $proposal) }}" class="rounded-2xl bg-white p-6 shadow-sm" x-data="{ decision: '{{ old('decision', 'approved') }}' }">@csrf<h2 class="text-xl font-black text-[#14205c]">Keputusan Verifier</h2><div class="mt-4 grid gap-3 sm:grid-cols-3">@foreach(['approved' => 'Setujui', 'revision' => 'Minta revisi', 'rejected' => 'Tolak'] as $value => $label)<label class="flex cursor-pointer items-center gap-2 rounded-xl border border-slate-200 p-3"><input type="radio" name="decision" value="{{ $value }}" x-model="decision"><span class="font-bold">{{ $label }}</span></label>@endforeach</div><div class="mt-4"><label for="notes" class="label">Catatan <span class="font-normal text-slate-500" x-show="decision === 'approved'">(opsional)</span></label><textarea id="notes" name="notes" rows="4" class="field">{{ old('notes') }}</textarea><x-input-error :messages="$errors->get('notes')" /></div><button class="btn-primary mt-4">Simpan keputusan</button></form>@endcan
</div>
@endsection
