@extends('layouts.verifier')
@section('title','Tinjau Proposal '.$proposal->program->title)
@section('verifier-content')
<div class="space-y-6"><x-ui.page-header eyebrow="Proposal Program" :title="$proposal->program->title" :description="$proposal->program->organization->name"><x-slot:actions><a class="btn-secondary" href="{{ route('verifier.program-proposals.index') }}">Kembali</a><x-ui.badge tone="primary">Versi {{ $proposal->version }}</x-ui.badge><x-program.proposal-status-badge :status="$proposal->status" /></x-slot:actions></x-ui.page-header>
<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><main class="space-y-6"><x-ui.card><dl class="grid gap-4 rounded-xl bg-surface-soft p-4 text-sm sm:grid-cols-3"><div><dt class="text-text-muted">Diajukan</dt><dd class="font-semibold">{{ $proposal->submitted_at?->translatedFormat('d M Y, H:i') ?? '—' }}</dd></div><div><dt class="text-text-muted">Pengaju</dt><dd class="font-semibold">{{ $proposal->submissionActivity?->causer?->name ?? '—' }}</dd></div><div><dt class="text-text-muted">Anggaran</dt><dd class="rupiah font-semibold">{{ $proposal->requested_budget!==null?'Rp '.number_format((float)$proposal->requested_budget,0,',','.'):'Tidak dicantumkan' }}</dd></div></dl><div class="mt-5 grid gap-5 lg:grid-cols-2"><div><h2 class="font-bold text-text-primary">Deskripsi</h2><p class="mt-2 whitespace-pre-line text-sm leading-6 text-text-secondary">{{ $proposal->program->description ?: 'Tidak tersedia.' }}</p></div><div><h2 class="font-bold text-text-primary">Tujuan</h2><p class="mt-2 whitespace-pre-line text-sm leading-6 text-text-secondary">{{ $proposal->program->objectives ?: 'Tidak tersedia.' }}</p></div></div></x-ui.card>
<x-workspace.file-card :title="'Proposal Program versi '.$proposal->version" description="Dokumen resmi yang diajukan Community" :href="route('verifier.program-proposals.document',$proposal)" type="Dokumen Proposal" />
<x-ui.card><h2 class="text-lg font-bold text-text-primary">Activity terhubung</h2><div class="mt-4 divide-y divide-border">@forelse($proposal->program->activities as $activity)<article class="py-3"><p class="font-semibold text-text-primary">{{ $activity->title }}</p><p class="text-sm text-text-secondary">{{ $activity->category?->name }} · {{ $activity->start_at->translatedFormat('d M Y') }}</p></article>@empty<p class="text-sm text-text-secondary">Tidak ada Activity terhubung.</p>@endforelse</div></x-ui.card>
@if($proposal->review_notes)<x-workspace.review-history><article><x-program.proposal-status-badge :status="$proposal->status" /><p class="mt-2 text-sm text-text-secondary">{{ $proposal->review_notes }}</p></article></x-workspace.review-history>@endif</main>
<aside class="h-fit xl:sticky xl:top-24">@can('review',$proposal)<x-workspace.decision-panel title="Keputusan Proposal" :action="route('verifier.program-proposals.review',$proposal)" />@else<x-ui.card><h2 class="text-lg font-bold">Versi telah ditinjau</h2><p class="mt-2 text-sm text-text-secondary">Status saat ini ditampilkan pada header.</p></x-ui.card>@endcan</aside></div></div>
@endsection
