@extends('layouts.manager')
@section('title', 'Dashboard '.$organization->name.' · SIPORA')
@section('manager-content')
<div class="space-y-6">
<section class="overflow-hidden rounded-3xl bg-[#182b85] p-6 text-white shadow-xl sm:p-8"><div class="flex flex-col justify-between gap-6 md:flex-row md:items-center"><div class="flex items-center gap-5"><div class="grid size-20 shrink-0 place-items-center overflow-hidden rounded-2xl bg-white/10 text-3xl font-black">@if($organization->logo_path)<img class="size-full object-cover" src="{{ route('communities.logo', $organization) }}" alt="">@else{{ mb_substr($organization->name, 0, 1) }}@endif</div><div><p class="text-xs font-extrabold uppercase tracking-[.16em] text-orange-300">Operational dashboard</p><h1 class="mt-2 text-3xl font-black">{{ $organization->name }}</h1><p class="mt-1 text-indigo-100">{{ $organization->category->name }} · {{ ucfirst($organization->operational_status) }}</p></div></div><a href="{{ route('communities.show', $organization) }}" class="btn-secondary !border-white/30 !bg-white/10 !text-white hover:!bg-white/20">Lihat halaman publik</a></div></section>
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="sipora-card"><p class="text-xs font-bold uppercase text-slate-500">Anggota aktif</p><p class="mt-2 text-3xl font-black text-[#182b85]">{{ $counts['members'] }}</p></div><div class="sipora-card"><p class="text-xs font-bold uppercase text-slate-500">Pengelola aktif</p><p class="mt-2 text-3xl font-black text-[#182b85]">{{ $counts['managers'] }}</p></div><div class="sipora-card border-t-4 border-t-orange-500"><p class="text-xs font-bold uppercase text-slate-500">Permintaan gabung</p><p class="mt-2 text-3xl font-black text-orange-700">{{ $counts['pending'] }}</p></div><div class="sipora-card"><p class="text-xs font-bold uppercase text-slate-500">Kelengkapan profil</p><p class="mt-2 text-3xl font-black text-[#182b85]">{{ $completion['percentage'] }}%</p><div class="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-orange-500" style="width: {{ $completion['percentage'] }}%"></div></div></div></section>
<div class="grid gap-6 xl:grid-cols-[1fr_340px]"><section class="sipora-card"><p class="text-xs font-bold uppercase text-orange-600">Akses cepat</p><h2 class="mt-1 text-xl font-bold text-[#243378]">Kelola komunitas</h2><div class="mt-5 grid gap-3 sm:grid-cols-3"><a class="rounded-xl border border-slate-200 p-4 hover:border-indigo-300" href="{{ route('manager.profile.edit', $organization) }}"><p class="font-bold">Profil komunitas</p><p class="mt-1 text-sm text-slate-500">Perbarui identitas publik.</p></a><a class="rounded-xl border border-slate-200 p-4 hover:border-indigo-300" href="{{ route('manager.members.index', $organization) }}"><p class="font-bold">Anggota</p><p class="mt-1 text-sm text-slate-500">Kelola peran dan status.</p></a><a class="rounded-xl border border-orange-200 bg-orange-50 p-4 hover:border-orange-300" href="{{ route('manager.members.index', $organization) }}#permintaan"><p class="font-bold text-orange-900">Permintaan gabung</p><p class="mt-1 text-sm text-orange-700">{{ $counts['pending'] }} menunggu tindakan.</p></a></div></section><aside class="sipora-card"><h2 class="font-bold text-[#243378]">Status Community</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between gap-3"><dt class="text-slate-500">Verifikasi</dt><dd><x-community.status-badge :status="$organization->review_status" /></dd></div><div class="flex justify-between gap-3"><dt class="text-slate-500">Operasional</dt><dd class="font-bold capitalize">{{ $organization->operational_status }}</dd></div></dl></aside></div>
<section class="sipora-card"><div class="flex items-center justify-between"><div><p class="text-xs font-bold uppercase text-slate-500">Phase 8</p><h2 class="mt-1 text-xl font-bold text-[#243378]">Activity komunitas</h2></div><span class="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-[#243378]">Segera hadir</span></div><div class="mt-5 rounded-2xl border-2 border-dashed border-slate-200 px-5 py-10 text-center"><p class="font-bold">Belum ada Activity</p><p class="mt-2 text-sm text-slate-500">Pembuatan dan verifikasi Activity akan tersedia pada fase berikutnya.</p></div></section>
</div>
@endsection
