-- ============================================================================
-- SIPORA v2 - CLEAN BACKEND-DRIVEN DATABASE SCHEMA
-- Target DBMS : MySQL 8.0.30+ / MySQL 8.4 LTS
-- Framework   : Laravel (business workflows live in application services/actions)
-- Engine      : InnoDB
-- Charset     : utf8mb4 / utf8mb4_0900_ai_ci
-- Key policy  : UUIDv7 generated by Laravel, stored as BINARY(16)
-- Time policy : DATETIME(6) in UTC
--
-- ARCHITECTURE POLICY
-- 1. NO database triggers.
-- 2. NO SQL views / materialized read models.
-- 3. Laravel owns workflow transitions, progress calculation, notifications,
--    activity-passport composition, certificate generation, audit writing,
--    eligibility checks, and profile-completion logic.
-- 4. MySQL owns structural integrity: PK, FK, UNIQUE, CHECK, NOT NULL, indexes.
-- 5. Soft-deleted unique business identifiers remain reserved. If a logical
--    relation is reused (membership, bookmark, participation), restore/update
--    the existing row instead of inserting a duplicate row.
--
-- UUID USAGE IN LARAVEL
-- Generate: Str::uuid7()
-- Store   : UUID_TO_BIN(<uuid>, 0) or cast in the application layer
-- Read    : BIN_TO_UUID(id, 0)
-- Do not use UUID_TO_BIN(..., 1) for UUIDv7.
--
-- IMPORTANT
-- This file is intentionally "boring SQL": predictable schema + constraints.
-- Application behavior must be visible and testable in the Laravel codebase.
-- ============================================================================

SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
SET time_zone = '+00:00';
SET sql_mode = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE DATABASE IF NOT EXISTS sipora
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;
USE sipora;

-- =========================================================
-- TABLE: system_roles
-- =========================================================
CREATE TABLE system_roles (

    id BINARY(16) NOT NULL PRIMARY KEY,
    code VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT ck_system_roles_code CHECK (code REGEXP '^[a-z][a-z0-9_]*$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: users
-- =========================================================
CREATE TABLE users (

    id BINARY(16) NOT NULL PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    password VARCHAR(255) NOT NULL,
    remember_token VARCHAR(100),
    account_status VARCHAR(24) NOT NULL DEFAULT 'active',
    email_verified_at DATETIME(6),
    last_login_at DATETIME(6),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT ck_users_account_status CHECK (account_status IN ('active','suspended','deactivated'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: user_system_roles
-- =========================================================
CREATE TABLE user_system_roles (

    id BINARY(16) NOT NULL PRIMARY KEY,
    user_id BINARY(16) NOT NULL,
    role_id BINARY(16) NOT NULL,
    assigned_by BINARY(16),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_usr_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_usr_role FOREIGN KEY (role_id) REFERENCES system_roles(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_usr_assigned_by FOREIGN KEY (assigned_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: user_profiles
-- =========================================================
CREATE TABLE user_profiles (

    id BINARY(16) NOT NULL PRIMARY KEY,
    user_id BINARY(16) NOT NULL UNIQUE,
    public_slug VARCHAR(190) NOT NULL,
    full_name VARCHAR(160) NOT NULL,
    birth_place VARCHAR(120),
    birth_date date NOT NULL,
    gender VARCHAR(24),
    phone VARCHAR(32),
    bio TEXT,
    occupation_status VARCHAR(32),
    occupation_title VARCHAR(160),
    profile_photo_path TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT ck_user_profiles_name CHECK (CHAR_LENGTH(trim(full_name)) >= 2),
    CONSTRAINT ck_user_profiles_birth_date CHECK (birth_date >= '1900-01-01'),
    CONSTRAINT ck_user_profiles_gender CHECK (gender IS NULL OR gender IN ('male','female','other','prefer_not_to_say')),
    CONSTRAINT ck_user_profiles_occupation CHECK (
        occupation_status IS NULL OR occupation_status IN ('student','university_student','worker','entrepreneur','unemployed','other')
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: administrative_areas
-- =========================================================
CREATE TABLE administrative_areas (

    id BINARY(16) NOT NULL PRIMARY KEY,
    parent_id BINARY(16),
    code VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    area_level VARCHAR(24) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_admin_areas_parent FOREIGN KEY (parent_id) REFERENCES administrative_areas(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_admin_areas_level CHECK (area_level IN ('province','regency','city','district','village'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: user_addresses
-- =========================================================
CREATE TABLE user_addresses (

    id BINARY(16) NOT NULL PRIMARY KEY,
    user_id BINARY(16) NOT NULL,
    administrative_area_id BINARY(16) NOT NULL,
    address_type VARCHAR(24) NOT NULL DEFAULT 'domicile',
    address_line TEXT,
    rt VARCHAR(4),
    rw VARCHAR(4),
    postal_code VARCHAR(10),
    is_primary BOOLEAN NOT NULL DEFAULT true,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_user_addresses_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_user_addresses_area FOREIGN KEY (administrative_area_id) REFERENCES administrative_areas(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_user_addresses_type CHECK (address_type IN ('domicile','identity','other'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: user_identities
-- =========================================================
CREATE TABLE user_identities (

    id BINARY(16) NOT NULL PRIMARY KEY,
    user_id BINARY(16) NOT NULL UNIQUE,
    national_id_hash char(64),
    national_id_ciphertext VARBINARY(512),
    verification_status VARCHAR(24) NOT NULL DEFAULT 'unverified',
    verification_method VARCHAR(24),
    verified_at DATETIME(6),
    verified_by BINARY(16),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_user_identities_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_user_identities_verified_by FOREIGN KEY (verified_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT ck_user_identities_status CHECK (verification_status IN ('unverified','pending','revision','rejected','verified')),
    CONSTRAINT ck_user_identities_method CHECK (verification_method IS NULL OR verification_method IN ('ktp','kia','student_card'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: user_identity_verifications
-- =========================================================
CREATE TABLE user_identity_verifications (

    id BINARY(16) NOT NULL PRIMARY KEY,
    user_identity_id BINARY(16) NOT NULL,
    document_type VARCHAR(24) NOT NULL,
    document_number_hash char(64),
    document_number_ciphertext VARBINARY(512),
    document_path TEXT NOT NULL,
    document_sha256 char(64),
    status VARCHAR(24) NOT NULL DEFAULT 'pending',
    submitted_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    reviewed_at DATETIME(6),
    reviewed_by BINARY(16),
    review_notes TEXT,
    metadata JSON NOT NULL DEFAULT (JSON_OBJECT()),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_uiv_identity FOREIGN KEY (user_identity_id) REFERENCES user_identities(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_uiv_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT ck_uiv_document_type CHECK (document_type IN ('ktp','kia','student_card')),
    CONSTRAINT ck_uiv_status CHECK (status IN ('pending','revision','rejected','verified')),
    CONSTRAINT ck_uiv_review_state CHECK (
        status = 'pending' OR reviewed_at IS NOT NULL
    ),
    CONSTRAINT ck_uiv_metadata_object CHECK (JSON_TYPE(metadata) = 'OBJECT')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: interests
-- =========================================================
CREATE TABLE interests (

    id BINARY(16) NOT NULL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(190) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: user_interests
-- =========================================================
CREATE TABLE user_interests (

    id BINARY(16) NOT NULL PRIMARY KEY,
    user_id BINARY(16) NOT NULL,
    interest_id BINARY(16) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_user_interests_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_user_interests_interest FOREIGN KEY (interest_id) REFERENCES interests(id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: skills
-- =========================================================
CREATE TABLE skills (

    id BINARY(16) NOT NULL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(190) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: user_skills
-- =========================================================
CREATE TABLE user_skills (

    id BINARY(16) NOT NULL PRIMARY KEY,
    user_id BINARY(16) NOT NULL,
    skill_id BINARY(16) NOT NULL,
    proficiency_level VARCHAR(24),
    is_self_reported BOOLEAN NOT NULL DEFAULT true,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_user_skills_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_user_skills_skill FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_user_skills_level CHECK (proficiency_level IS NULL OR proficiency_level IN ('beginner','intermediate','advanced','expert'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: hobbies
-- =========================================================
CREATE TABLE hobbies (

    id BINARY(16) NOT NULL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(190) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: user_hobbies
-- =========================================================
CREATE TABLE user_hobbies (

    id BINARY(16) NOT NULL PRIMARY KEY,
    user_id BINARY(16) NOT NULL,
    hobby_id BINARY(16) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_user_hobbies_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_user_hobbies_hobby FOREIGN KEY (hobby_id) REFERENCES hobbies(id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: user_educations
-- =========================================================
CREATE TABLE user_educations (

    id BINARY(16) NOT NULL PRIMARY KEY,
    user_id BINARY(16) NOT NULL,
    education_level VARCHAR(40) NOT NULL,
    institution_name VARCHAR(180) NOT NULL,
    field_of_study VARCHAR(180),
    start_date date,
    end_date date,
    is_current BOOLEAN NOT NULL DEFAULT false,
    description TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_user_educations_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT ck_user_educations_dates CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_user_educations_current CHECK (NOT is_current OR end_date IS NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: organization_experiences
-- =========================================================
CREATE TABLE organization_experiences (

    id BINARY(16) NOT NULL PRIMARY KEY,
    user_id BINARY(16) NOT NULL,
    organization_name VARCHAR(180) NOT NULL,
    role_title VARCHAR(160),
    start_date date,
    end_date date,
    is_current BOOLEAN NOT NULL DEFAULT false,
    description TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_org_exp_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT ck_org_exp_dates CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_org_exp_current CHECK (NOT is_current OR end_date IS NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: user_business_experiences
-- =========================================================
CREATE TABLE user_business_experiences (

    id BINARY(16) NOT NULL PRIMARY KEY,
    user_id BINARY(16) NOT NULL,
    business_name VARCHAR(180) NOT NULL,
    role_title VARCHAR(160),
    business_category VARCHAR(120),
    start_date date,
    end_date date,
    is_current BOOLEAN NOT NULL DEFAULT false,
    description TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_user_business_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT ck_user_business_dates CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_user_business_current CHECK (NOT is_current OR end_date IS NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: user_achievements
-- =========================================================
CREATE TABLE user_achievements (

    id BINARY(16) NOT NULL PRIMARY KEY,
    user_id BINARY(16) NOT NULL,
    title VARCHAR(180) NOT NULL,
    issuer_name VARCHAR(180),
    achievement_date date,
    description TEXT,
    evidence_path TEXT,
    verification_status VARCHAR(24) NOT NULL DEFAULT 'self_reported',
    verified_by BINARY(16),
    verified_at DATETIME(6),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_user_achievements_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_user_achievements_verifier FOREIGN KEY (verified_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT ck_user_achievements_status CHECK (verification_status IN ('self_reported','pending','verified','rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: user_profile_visibility
-- =========================================================
CREATE TABLE user_profile_visibility (

    id BINARY(16) NOT NULL PRIMARY KEY,
    user_id BINARY(16) NOT NULL UNIQUE,
    is_profile_public BOOLEAN NOT NULL DEFAULT true,
    show_photo BOOLEAN NOT NULL DEFAULT true,
    show_bio BOOLEAN NOT NULL DEFAULT true,
    show_interests BOOLEAN NOT NULL DEFAULT true,
    show_skills BOOLEAN NOT NULL DEFAULT true,
    show_education BOOLEAN NOT NULL DEFAULT true,
    show_organization_experience BOOLEAN NOT NULL DEFAULT true,
    show_community_membership BOOLEAN NOT NULL DEFAULT true,
    show_activity_passport BOOLEAN NOT NULL DEFAULT true,
    show_certificates BOOLEAN NOT NULL DEFAULT true,
    show_achievements BOOLEAN NOT NULL DEFAULT true,
    show_business_experience BOOLEAN NOT NULL DEFAULT true,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_user_visibility_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: organization_categories
-- =========================================================
CREATE TABLE organization_categories (

    id BINARY(16) NOT NULL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(190) NOT NULL,
    description TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: organizations
-- =========================================================
CREATE TABLE organizations (

    id BINARY(16) NOT NULL PRIMARY KEY,
    created_by_user_id BINARY(16),
    category_id BINARY(16) NOT NULL,
    administrative_area_id BINARY(16),
    name VARCHAR(180) NOT NULL,
    slug VARCHAR(190) NOT NULL,
    description TEXT,
    logo_path TEXT,
    contact_email VARCHAR(254),
    contact_phone VARCHAR(32),
    website_url TEXT,
    address_text TEXT,
    social_links JSON NOT NULL DEFAULT (JSON_OBJECT()),
    review_status VARCHAR(24) NOT NULL DEFAULT 'draft',
    operational_status VARCHAR(24) NOT NULL DEFAULT 'inactive',
    approved_at DATETIME(6),
    approved_by BINARY(16),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_organizations_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT fk_organizations_category FOREIGN KEY (category_id) REFERENCES organization_categories(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_organizations_area FOREIGN KEY (administrative_area_id) REFERENCES administrative_areas(id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT fk_organizations_approver FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT ck_organizations_review_status CHECK (review_status IN ('draft','pending_review','revision','rejected','approved')),
    CONSTRAINT ck_organizations_operational_status CHECK (operational_status IN ('inactive','active','suspended','archived')),
    CONSTRAINT ck_organizations_social_links CHECK (JSON_TYPE(social_links) = 'OBJECT'),
    CONSTRAINT ck_organizations_approved CHECK (review_status <> 'approved' OR approved_at IS NOT NULL),
    CONSTRAINT ck_organizations_active_requires_approval CHECK (operational_status <> 'active' OR review_status = 'approved')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: organization_documents
-- =========================================================
CREATE TABLE organization_documents (

    id BINARY(16) NOT NULL PRIMARY KEY,
    organization_id BINARY(16) NOT NULL,
    document_type VARCHAR(48) NOT NULL,
    document_name VARCHAR(180),
    document_path TEXT NOT NULL,
    document_sha256 char(64),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_org_documents_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: organization_verification_requests
-- =========================================================
CREATE TABLE organization_verification_requests (

    id BINARY(16) NOT NULL PRIMARY KEY,
    organization_id BINARY(16) NOT NULL,
    submitted_by BINARY(16) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'pending',
    submission_notes TEXT,
    submitted_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    reviewed_by BINARY(16),
    reviewed_at DATETIME(6),
    review_notes TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_org_verify_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_org_verify_submitter FOREIGN KEY (submitted_by) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_org_verify_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT ck_org_verify_status CHECK (status IN ('pending','revision','rejected','approved')),
    CONSTRAINT ck_org_verify_review CHECK (status = 'pending' OR reviewed_at IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: organization_memberships
-- =========================================================
CREATE TABLE organization_memberships (

    id BINARY(16) NOT NULL PRIMARY KEY,
    organization_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    access_role VARCHAR(24) NOT NULL DEFAULT 'member',
    position_title VARCHAR(160),
    membership_status VARCHAR(24) NOT NULL DEFAULT 'pending',
    requested_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    approved_at DATETIME(6),
    approved_by BINARY(16),
    ended_at DATETIME(6),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_org_membership_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_org_membership_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_org_membership_approver FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT ck_org_membership_role CHECK (access_role IN ('leader','manager','member')),
    CONSTRAINT ck_org_membership_status CHECK (membership_status IN ('pending','active','rejected','left','removed')),
    CONSTRAINT ck_org_membership_approval CHECK (membership_status <> 'active' OR approved_at IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: program_categories
-- =========================================================
CREATE TABLE program_categories (

    id BINARY(16) NOT NULL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(190) NOT NULL,
    description TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: programs
-- =========================================================
CREATE TABLE programs (

    id BINARY(16) NOT NULL PRIMARY KEY,
    organization_id BINARY(16) NOT NULL,
    category_id BINARY(16) NOT NULL,
    created_by_user_id BINARY(16) NOT NULL,
    title VARCHAR(220) NOT NULL,
    slug VARCHAR(190) NOT NULL,
    description TEXT,
    objectives TEXT,
    start_date date,
    end_date date,
    execution_status VARCHAR(24) NOT NULL DEFAULT 'planned',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_programs_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_programs_category FOREIGN KEY (category_id) REFERENCES program_categories(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_programs_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_programs_dates CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_programs_execution_status CHECK (execution_status IN ('planned','running','completed','cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: activity_categories
-- =========================================================
CREATE TABLE activity_categories (

    id BINARY(16) NOT NULL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(190) NOT NULL,
    description TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: activities
-- =========================================================
CREATE TABLE activities (

    id BINARY(16) NOT NULL PRIMARY KEY,
    organization_id BINARY(16) NOT NULL,
    program_id BINARY(16),
    category_id BINARY(16) NOT NULL,
    created_by_user_id BINARY(16) NOT NULL,
    title VARCHAR(220) NOT NULL,
    slug VARCHAR(190) NOT NULL,
    description TEXT,
    poster_path TEXT,
    location_type VARCHAR(16) NOT NULL DEFAULT 'offline',
    venue_name VARCHAR(180),
    administrative_area_id BINARY(16),
    address_text TEXT,
    meeting_url TEXT,
    start_at DATETIME(6) NOT NULL,
    end_at DATETIME(6) NOT NULL,
    registration_open_at DATETIME(6),
    registration_close_at DATETIME(6),
    quota INT,
    registration_mode VARCHAR(24) NOT NULL DEFAULT 'open',
    min_age SMALLINT,
    max_age SMALLINT,
    requires_identity_verification BOOLEAN NOT NULL DEFAULT false,
    members_only BOOLEAN NOT NULL DEFAULT false,
    eligibility_notes TEXT,
    certificate_enabled BOOLEAN NOT NULL DEFAULT false,
    review_status VARCHAR(24) NOT NULL DEFAULT 'draft',
    publication_status VARCHAR(24) NOT NULL DEFAULT 'unpublished',
    execution_status VARCHAR(24) NOT NULL DEFAULT 'scheduled',
    published_at DATETIME(6),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_activities_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_activities_program FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_activities_category FOREIGN KEY (category_id) REFERENCES activity_categories(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_activities_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_activities_area FOREIGN KEY (administrative_area_id) REFERENCES administrative_areas(id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT ck_activities_location_type CHECK (location_type IN ('offline','online','hybrid')),
    CONSTRAINT ck_activities_dates CHECK (end_at > start_at),
    CONSTRAINT ck_activities_registration_dates CHECK (
        registration_close_at IS NULL OR registration_open_at IS NULL OR registration_close_at >= registration_open_at
    ),
    CONSTRAINT ck_activities_quota CHECK (quota IS NULL OR quota > 0),
    CONSTRAINT ck_activities_registration_mode CHECK (registration_mode IN ('open','approval_required')),
    CONSTRAINT ck_activities_age CHECK (
        (min_age IS NULL OR min_age BETWEEN 0 AND 100)
        AND (max_age IS NULL OR max_age BETWEEN 0 AND 100)
        AND (min_age IS NULL OR max_age IS NULL OR max_age >= min_age)
    ),
    CONSTRAINT ck_activities_review_status CHECK (review_status IN ('draft','pending_review','revision','rejected','approved')),
    CONSTRAINT ck_activities_publication_status CHECK (publication_status IN ('unpublished','published','archived')),
    CONSTRAINT ck_activities_execution_status CHECK (execution_status IN ('scheduled','ongoing','completed','cancelled')),
    CONSTRAINT ck_activities_publish_state CHECK (
        publication_status <> 'published' OR (review_status = 'approved' AND published_at IS NOT NULL)
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: activity_reviews
-- =========================================================
CREATE TABLE activity_reviews (

    id BINARY(16) NOT NULL PRIMARY KEY,
    activity_id BINARY(16) NOT NULL,
    reviewer_id BINARY(16) NOT NULL,
    decision VARCHAR(24) NOT NULL,
    review_notes TEXT,
    reviewed_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_activity_reviews_activity FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_activity_reviews_reviewer FOREIGN KEY (reviewer_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_activity_reviews_decision CHECK (decision IN ('approved','revision','rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: activity_sessions
-- One Activity has one or more real attendance sessions.
-- A simple one-day Activity normally has a single default session.
-- =========================================================
CREATE TABLE activity_sessions (

    id BINARY(16) NOT NULL PRIMARY KEY,
    activity_id BINARY(16) NOT NULL,
    session_number SMALLINT UNSIGNED NOT NULL,
    title VARCHAR(180) NOT NULL,
    description TEXT,
    start_at DATETIME(6) NOT NULL,
    end_at DATETIME(6) NOT NULL,
    venue_name VARCHAR(180),
    address_text TEXT,
    meeting_url TEXT,
    notes TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_activity_sessions_activity FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT ck_activity_sessions_number CHECK (session_number > 0),
    CONSTRAINT ck_activity_sessions_dates CHECK (end_at > start_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: activity_participations
-- =========================================================
CREATE TABLE activity_participations (

    id BINARY(16) NOT NULL PRIMARY KEY,
    activity_id BINARY(16) NOT NULL,
    user_id BINARY(16) NOT NULL,
    activity_role VARCHAR(24) NOT NULL DEFAULT 'participant',
    registration_status VARCHAR(24) NOT NULL DEFAULT 'pending',
    completion_status VARCHAR(24) NOT NULL DEFAULT 'pending',
    registration_notes TEXT,
    requested_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    reviewed_at DATETIME(6),
    reviewed_by BINARY(16),
    completed_at DATETIME(6),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_activity_participation_activity FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_activity_participation_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_activity_participation_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT ck_activity_participation_role CHECK (activity_role IN ('participant','volunteer','committee','speaker','organizer')),
    CONSTRAINT ck_activity_participation_registration CHECK (registration_status IN ('pending','accepted','rejected','cancelled')),
    CONSTRAINT ck_activity_participation_completion CHECK (completion_status IN ('pending','completed','no_show')),
    CONSTRAINT ck_activity_participation_completed_at CHECK (completion_status <> 'completed' OR completed_at IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: activity_attendances
-- Attendance is recorded per Activity Session, not only per Activity.
-- =========================================================
CREATE TABLE activity_attendances (

    id BINARY(16) NOT NULL PRIMARY KEY,
    activity_session_id BINARY(16) NOT NULL,
    participation_id BINARY(16) NOT NULL,
    attendance_status VARCHAR(24) NOT NULL,
    checked_in_at DATETIME(6),
    checked_out_at DATETIME(6),
    recorded_by BINARY(16) NOT NULL,
    notes TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_activity_attendance_session FOREIGN KEY (activity_session_id) REFERENCES activity_sessions(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_activity_attendance_participation FOREIGN KEY (participation_id) REFERENCES activity_participations(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_activity_attendance_recorder FOREIGN KEY (recorded_by) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_activity_attendance_status CHECK (attendance_status IN ('present','absent','excused')),
    CONSTRAINT ck_activity_attendance_times CHECK (checked_out_at IS NULL OR checked_in_at IS NULL OR checked_out_at >= checked_in_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: activity_media
-- =========================================================
CREATE TABLE activity_media (

    id BINARY(16) NOT NULL PRIMARY KEY,
    activity_id BINARY(16) NOT NULL,
    uploaded_by BINARY(16) NOT NULL,
    media_type VARCHAR(24) NOT NULL DEFAULT 'image',
    file_path TEXT NOT NULL,
    caption TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_activity_media_activity FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_activity_media_uploader FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_activity_media_type CHECK (media_type IN ('image','video','document')),
    CONSTRAINT ck_activity_media_sort CHECK (sort_order >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: activity_bookmarks
-- =========================================================
CREATE TABLE activity_bookmarks (

    id BINARY(16) NOT NULL PRIMARY KEY,
    user_id BINARY(16) NOT NULL,
    activity_id BINARY(16) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_activity_bookmark_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_activity_bookmark_activity FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: user_certificates
-- =========================================================
CREATE TABLE user_certificates (

    id BINARY(16) NOT NULL PRIMARY KEY,
    user_id BINARY(16) NOT NULL,
    participation_id BINARY(16),
    source_type VARCHAR(24) NOT NULL,
    name VARCHAR(220) NOT NULL,
    issuer_name VARCHAR(180) NOT NULL,
    certificate_number VARCHAR(120),
    verification_code VARCHAR(120),
    issued_at date NOT NULL,
    expires_at date,
    file_path TEXT,
    external_url TEXT,
    verification_status VARCHAR(24) NOT NULL DEFAULT 'self_reported',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_user_certificates_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_user_certificates_participation FOREIGN KEY (participation_id) REFERENCES activity_participations(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_user_certificates_source CHECK (source_type IN ('sipora','external')),
    CONSTRAINT ck_user_certificates_status CHECK (verification_status IN ('self_reported','pending','verified','rejected')),
    CONSTRAINT ck_user_certificates_dates CHECK (expires_at IS NULL OR expires_at >= issued_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: program_proposals
-- =========================================================
CREATE TABLE program_proposals (

    id BINARY(16) NOT NULL PRIMARY KEY,
    program_id BINARY(16) NOT NULL,
    version INT NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'draft',
    requested_budget DECIMAL(18,2),
    proposal_document_path TEXT,
    submitted_at DATETIME(6),
    reviewed_at DATETIME(6),
    reviewed_by BINARY(16),
    review_notes TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_program_proposals_program FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_program_proposals_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT uq_program_proposals_version UNIQUE (program_id, version),
    CONSTRAINT ck_program_proposals_version CHECK (version > 0),
    CONSTRAINT ck_program_proposals_budget CHECK (requested_budget IS NULL OR requested_budget >= 0),
    CONSTRAINT ck_program_proposals_status CHECK (status IN ('draft','submitted','under_review','revision','rejected','approved')),
    CONSTRAINT ck_program_proposals_submitted CHECK (status = 'draft' OR submitted_at IS NOT NULL),
    CONSTRAINT ck_program_proposals_reviewed CHECK (status NOT IN ('revision','rejected','approved') OR reviewed_at IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: program_logbooks
-- =========================================================
CREATE TABLE program_logbooks (

    id BINARY(16) NOT NULL PRIMARY KEY,
    program_id BINARY(16) NOT NULL,
    activity_id BINARY(16),
    created_by_user_id BINARY(16) NOT NULL,
    log_date date NOT NULL,
    summary TEXT NOT NULL,
    obstacles TEXT,
    solutions TEXT,
    progress_percent SMALLINT NOT NULL DEFAULT 0,
    status VARCHAR(24) NOT NULL DEFAULT 'draft',
    submitted_at DATETIME(6),
    reviewed_at DATETIME(6),
    reviewed_by BINARY(16),
    review_notes TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_program_logbooks_program FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_program_logbooks_activity FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_program_logbooks_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_program_logbooks_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT ck_program_logbooks_progress CHECK (progress_percent BETWEEN 0 AND 100),
    CONSTRAINT ck_program_logbooks_status CHECK (status IN ('draft','submitted','revision','approved')),
    CONSTRAINT ck_program_logbooks_submitted CHECK (status = 'draft' OR submitted_at IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: program_logbook_media
-- =========================================================
CREATE TABLE program_logbook_media (

    id BINARY(16) NOT NULL PRIMARY KEY,
    logbook_id BINARY(16) NOT NULL,
    uploaded_by BINARY(16) NOT NULL,
    file_path TEXT NOT NULL,
    caption TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_logbook_media_logbook FOREIGN KEY (logbook_id) REFERENCES program_logbooks(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_logbook_media_uploader FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: financial_reports
-- =========================================================
CREATE TABLE financial_reports (

    id BINARY(16) NOT NULL PRIMARY KEY,
    program_id BINARY(16) NOT NULL,
    version INT NOT NULL DEFAULT 1,
    status VARCHAR(24) NOT NULL DEFAULT 'draft',
    notes TEXT,
    submitted_at DATETIME(6),
    reviewed_at DATETIME(6),
    reviewed_by BINARY(16),
    review_notes TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_financial_reports_program FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_financial_reports_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT uq_financial_reports_version UNIQUE(program_id, version),
    CONSTRAINT ck_financial_reports_version CHECK (version > 0),
    CONSTRAINT ck_financial_reports_status CHECK (status IN ('draft','submitted','under_review','revision','rejected','approved')),
    CONSTRAINT ck_financial_reports_submitted CHECK (status = 'draft' OR submitted_at IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: financial_items
-- =========================================================
CREATE TABLE financial_items (

    id BINARY(16) NOT NULL PRIMARY KEY,
    financial_report_id BINARY(16) NOT NULL,
    transaction_type VARCHAR(16) NOT NULL,
    transaction_date date NOT NULL,
    description TEXT NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    receipt_path TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_financial_items_report FOREIGN KEY (financial_report_id) REFERENCES financial_reports(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT ck_financial_items_type CHECK (transaction_type IN ('income','expense')),
    CONSTRAINT ck_financial_items_amount CHECK (amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: program_evaluations
-- =========================================================
CREATE TABLE program_evaluations (

    id BINARY(16) NOT NULL PRIMARY KEY,
    program_id BINARY(16) NOT NULL,
    verifier_id BINARY(16) NOT NULL,
    decision VARCHAR(24) NOT NULL,
    evaluation_notes TEXT,
    evaluated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_program_evaluations_program FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_program_evaluations_verifier FOREIGN KEY (verifier_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_program_evaluations_decision CHECK (decision IN ('approved','revision','rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: opportunity_categories
-- =========================================================
CREATE TABLE opportunity_categories (

    id BINARY(16) NOT NULL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(190) NOT NULL,
    description TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: opportunities
-- =========================================================
CREATE TABLE opportunities (

    id BINARY(16) NOT NULL PRIMARY KEY,
    category_id BINARY(16) NOT NULL,
    organization_id BINARY(16),
    created_by_user_id BINARY(16),
    title VARCHAR(220) NOT NULL,
    slug VARCHAR(190) NOT NULL,
    provider_name VARCHAR(180) NOT NULL,
    description TEXT NOT NULL,
    administrative_area_id BINARY(16),
    location_text VARCHAR(220),
    external_url TEXT NOT NULL,
    deadline_at DATETIME(6),
    starts_at DATETIME(6),
    ends_at DATETIME(6),
    publication_status VARCHAR(24) NOT NULL DEFAULT 'draft',
    published_at DATETIME(6),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_opportunities_category FOREIGN KEY (category_id) REFERENCES opportunity_categories(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_opportunities_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT fk_opportunities_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT fk_opportunities_area FOREIGN KEY (administrative_area_id) REFERENCES administrative_areas(id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT ck_opportunities_dates CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at >= starts_at),
    CONSTRAINT ck_opportunities_status CHECK (publication_status IN ('draft','published','archived')),
    CONSTRAINT ck_opportunities_published CHECK (publication_status <> 'published' OR published_at IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: opportunity_bookmarks
-- =========================================================
CREATE TABLE opportunity_bookmarks (

    id BINARY(16) NOT NULL PRIMARY KEY,
    user_id BINARY(16) NOT NULL,
    opportunity_id BINARY(16) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_opportunity_bookmark_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_opportunity_bookmark_opportunity FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: notifications
-- =========================================================
CREATE TABLE notifications (

    id BINARY(16) NOT NULL PRIMARY KEY,
    user_id BINARY(16) NOT NULL,
    notification_type VARCHAR(80) NOT NULL,
    title VARCHAR(220) NOT NULL,
    body TEXT NOT NULL,
    data JSON NOT NULL DEFAULT (JSON_OBJECT()),
    read_at DATETIME(6),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT ck_notifications_data_object CHECK (JSON_TYPE(data) = 'OBJECT')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;

-- =========================================================
-- TABLE: audit_logs
-- =========================================================
CREATE TABLE audit_logs (

    id BINARY(16) NOT NULL PRIMARY KEY,
    actor_user_id BINARY(16),
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(120) NOT NULL,
    entity_id BINARY(16),
    request_id BINARY(16),
    ip_address VARCHAR(45),
    user_agent TEXT,
    before_data JSON,
    after_data JSON,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_audit_logs_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT ck_audit_logs_before CHECK (before_data IS NULL OR JSON_TYPE(before_data) = 'OBJECT'),
    CONSTRAINT ck_audit_logs_after CHECK (after_data IS NULL OR JSON_TYPE(after_data) = 'OBJECT')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;



-- ============================================================================
-- BUSINESS UNIQUENESS
-- ============================================================================
-- MySQL has no PostgreSQL-style partial unique index. To keep the schema simple
-- and backend-driven, unique identifiers remain reserved after soft deletion.
-- For relationship rows, Laravel should restore/update the existing record.

ALTER TABLE users
    ADD CONSTRAINT uq_users_email UNIQUE (email);

ALTER TABLE user_system_roles
    ADD CONSTRAINT uq_user_system_roles UNIQUE (user_id, role_id);

ALTER TABLE user_profiles
    ADD CONSTRAINT uq_user_profiles_public_slug UNIQUE (public_slug);

ALTER TABLE user_identities
    ADD CONSTRAINT uq_user_identities_national_id_hash UNIQUE (national_id_hash);

ALTER TABLE interests
    ADD CONSTRAINT uq_interests_slug UNIQUE (slug);

ALTER TABLE user_interests
    ADD CONSTRAINT uq_user_interests UNIQUE (user_id, interest_id);

ALTER TABLE skills
    ADD CONSTRAINT uq_skills_slug UNIQUE (slug);

ALTER TABLE user_skills
    ADD CONSTRAINT uq_user_skills UNIQUE (user_id, skill_id);

ALTER TABLE hobbies
    ADD CONSTRAINT uq_hobbies_slug UNIQUE (slug);

ALTER TABLE user_hobbies
    ADD CONSTRAINT uq_user_hobbies UNIQUE (user_id, hobby_id);

ALTER TABLE organization_categories
    ADD CONSTRAINT uq_organization_categories_slug UNIQUE (slug);

ALTER TABLE organizations
    ADD CONSTRAINT uq_organizations_slug UNIQUE (slug);

ALTER TABLE organization_memberships
    ADD CONSTRAINT uq_organization_memberships UNIQUE (organization_id, user_id);

ALTER TABLE program_categories
    ADD CONSTRAINT uq_program_categories_slug UNIQUE (slug);

ALTER TABLE programs
    ADD CONSTRAINT uq_programs_slug UNIQUE (slug);

ALTER TABLE activity_categories
    ADD CONSTRAINT uq_activity_categories_slug UNIQUE (slug);

ALTER TABLE activities
    ADD CONSTRAINT uq_activities_slug UNIQUE (slug);

ALTER TABLE activity_sessions
    ADD CONSTRAINT uq_activity_sessions_number UNIQUE (activity_id, session_number);

ALTER TABLE activity_participations
    ADD CONSTRAINT uq_activity_participations UNIQUE (activity_id, user_id);

ALTER TABLE activity_attendances
    ADD CONSTRAINT uq_activity_attendances_session_participation UNIQUE (activity_session_id, participation_id);

ALTER TABLE activity_bookmarks
    ADD CONSTRAINT uq_activity_bookmarks UNIQUE (user_id, activity_id);

ALTER TABLE user_certificates
    ADD CONSTRAINT uq_user_certificates_verification_code UNIQUE (verification_code);

ALTER TABLE opportunity_categories
    ADD CONSTRAINT uq_opportunity_categories_slug UNIQUE (slug);

ALTER TABLE opportunities
    ADD CONSTRAINT uq_opportunities_slug UNIQUE (slug);

ALTER TABLE opportunity_bookmarks
    ADD CONSTRAINT uq_opportunity_bookmarks UNIQUE (user_id, opportunity_id);


-- =========================================================
-- PERFORMANCE INDEXES
-- =========================================================
-- InnoDB secondary indexes are B-Tree unless FULLTEXT is specified.
-- deleted_at is included where useful for common soft-delete filters.

CREATE INDEX idx_administrative_areas_parent ON administrative_areas(parent_id, deleted_at);
CREATE INDEX idx_administrative_areas_level_name ON administrative_areas(area_level, name, deleted_at);
CREATE INDEX idx_user_addresses_area ON user_addresses(administrative_area_id, deleted_at);
CREATE INDEX idx_uiv_status_submitted ON user_identity_verifications(status, deleted_at, submitted_at);
CREATE INDEX idx_user_interests_interest ON user_interests(interest_id, deleted_at);
CREATE INDEX idx_user_skills_skill ON user_skills(skill_id, deleted_at);
CREATE INDEX idx_user_educations_user ON user_educations(user_id, deleted_at, start_date DESC);
CREATE INDEX idx_org_exp_user ON organization_experiences(user_id, deleted_at, start_date DESC);
CREATE INDEX idx_org_documents_org ON organization_documents(organization_id, deleted_at);
CREATE INDEX idx_org_verification_queue ON organization_verification_requests(status, deleted_at, submitted_at);
CREATE INDEX idx_organizations_review_operational ON organizations(review_status, operational_status, deleted_at);
CREATE INDEX idx_org_membership_user ON organization_memberships(user_id, membership_status, deleted_at);
CREATE INDEX idx_org_membership_org_status ON organization_memberships(organization_id, membership_status, deleted_at);
CREATE INDEX idx_programs_org_status ON programs(organization_id, execution_status, deleted_at);
CREATE INDEX idx_programs_dates ON programs(start_date, end_date, deleted_at);
CREATE INDEX idx_activities_org_status ON activities(organization_id, execution_status, deleted_at);
CREATE INDEX idx_activities_program ON activities(program_id, deleted_at);
CREATE INDEX idx_activities_category_start ON activities(category_id, deleted_at, start_at);
CREATE INDEX idx_activities_public_upcoming ON activities(publication_status, review_status, execution_status, deleted_at, start_at);
CREATE INDEX idx_activities_area_start ON activities(administrative_area_id, deleted_at, start_at);
CREATE INDEX idx_activity_reviews_activity_date ON activity_reviews(activity_id, deleted_at, reviewed_at DESC);
CREATE INDEX idx_activity_sessions_activity_start ON activity_sessions(activity_id, deleted_at, start_at);
CREATE INDEX idx_activity_participation_activity_status ON activity_participations(activity_id, registration_status, completion_status, deleted_at);
CREATE INDEX idx_activity_participation_user ON activity_participations(user_id, deleted_at, requested_at DESC);
CREATE INDEX idx_activity_attendance_session_status ON activity_attendances(activity_session_id, attendance_status, deleted_at);
CREATE INDEX idx_activity_attendance_participation ON activity_attendances(participation_id, deleted_at);
CREATE INDEX idx_activity_media_activity_sort ON activity_media(activity_id, deleted_at, sort_order);
CREATE INDEX idx_user_certificates_user ON user_certificates(user_id, deleted_at, issued_at DESC);
CREATE INDEX idx_program_proposals_queue ON program_proposals(status, deleted_at, submitted_at);
CREATE INDEX idx_program_proposals_program_latest ON program_proposals(program_id, deleted_at, version DESC);
CREATE INDEX idx_program_logbooks_program_date ON program_logbooks(program_id, deleted_at, log_date DESC, created_at DESC);
CREATE INDEX idx_program_logbooks_queue ON program_logbooks(status, deleted_at, submitted_at);
CREATE INDEX idx_logbook_media_logbook ON program_logbook_media(logbook_id, deleted_at);
CREATE INDEX idx_financial_reports_queue ON financial_reports(status, deleted_at, submitted_at);
CREATE INDEX idx_financial_reports_program_latest ON financial_reports(program_id, deleted_at, version DESC);
CREATE INDEX idx_financial_items_report_date ON financial_items(financial_report_id, deleted_at, transaction_date);
CREATE INDEX idx_program_evaluations_program_date ON program_evaluations(program_id, deleted_at, evaluated_at DESC);
CREATE INDEX idx_opportunities_category_deadline ON opportunities(category_id, deleted_at, deadline_at);
CREATE INDEX idx_opportunities_published_deadline ON opportunities(publication_status, deleted_at, deadline_at);
CREATE INDEX idx_notifications_user_created ON notifications(user_id, deleted_at, created_at DESC);
CREATE INDEX idx_notifications_unread ON notifications(user_id, read_at, deleted_at, created_at DESC);
CREATE INDEX idx_audit_logs_actor_date ON audit_logs(actor_user_id, created_at DESC);
CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_type, entity_id, created_at DESC);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);

-- MySQL replacement for PostgreSQL GIN/tsvector/trigram search.
ALTER TABLE organizations ADD FULLTEXT INDEX ftx_organizations_search (name, description);
ALTER TABLE activities ADD FULLTEXT INDEX ftx_activities_search (title, description, venue_name);
ALTER TABLE opportunities ADD FULLTEXT INDEX ftx_opportunities_search (title, provider_name, description);


-- =========================================================
-- BASE SEED DATA
-- =========================================================
INSERT IGNORE INTO system_roles(id, code, name, description) VALUES
    (UUID_TO_BIN('019948f0-0000-7000-8000-000000000001', 0), 'youth', 'Youth', 'Pemuda / pengguna utama SIPORA'),
    (UUID_TO_BIN('019948f0-0000-7000-8000-000000000002', 0), 'verifier', 'Verifier', 'Verifikator Dindikpora untuk community, activity, dan program'),
    (UUID_TO_BIN('019948f0-0000-7000-8000-000000000003', 0), 'admin', 'Administrator', 'Administrator Dindikpora');



-- ============================================================================
-- BACKEND-OWNED RULES (DOCUMENTATION ONLY - NOT DATABASE TRIGGERS)
-- ============================================================================
-- Laravel service/action layer MUST enforce at least these cross-table rules:
--
-- COMMUNITY
-- - Youth submits community application; verifier approves/revises/rejects.
-- - organizations.review_status tracks review lifecycle; operational_status tracks active/suspended/archive state.
-- - Only review_status='approved' + operational_status='active' organizations may publish operational content.
-- - Multiple managers are allowed; leader uniqueness is enforced by service logic.
--
-- ACTIVITY
-- - Activity must be reviewed by verifier before publication.
-- - If activity.program_id is set, activity.organization_id must match program.organization_id.
-- - Registration eligibility: dates, quota, age, identity verification, members_only.
-- - Every Activity must have >= 1 Activity Session before it can start; create one default session for simple events.
-- - Session times must fall within the Activity start_at/end_at window; enforce this in Laravel.
-- - Attendance is recorded per session using UNIQUE(activity_session_id, participation_id).
-- - Completion requires valid participation/attendance according to application rules. Attendance itself is evidence, not automatic completion.
-- - Activity Passport is composed from completed verified participations at query time.
--
-- PROGRAM
-- - Draft program may exist without activities.
-- - Proposal submission requires active organization and >= 1 linked activity.
-- - Program progress is calculated in Laravel; do not persist a mutable progress column.
-- - Final completion requires approved proposal, required logbook progress,
--   approved financial report, and approved final evaluation.
--
-- IDENTITY
-- - Admin owns personal-identity verification workflow.
-- - Verification documents remain private; never expose identity data in public portfolio.
--
-- PORTFOLIO
-- - Public by default at the portfolio level, with user-controlled section visibility.
-- - Sensitive identity/contact/address/document fields are always private by design.
--
-- AUDIT / NOTIFICATIONS
-- - Write audit_logs and notifications from the same Laravel DB transaction as
--   the state-changing command whenever atomicity is required.
--
-- TIMESTAMPS
-- - Laravel/Eloquent owns updated_at. There is deliberately no ON UPDATE clause.
-- - Laravel SoftDeletes owns deleted_at where the model uses soft deletion.
-- ============================================================================
