@extends('layouts.manager')
@section('title', $program->title)
@section('manager-content')
<div class="space-y-6">
    <section class="overflow-hidden rounded-2xl bg-white shadow-sm"><div class="border-b border-indigo-100 bg-gradient-to-r from-[#eef0ff] to-white p-6"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-bold text-orange-600">{{ $program->category?->name }}</p><h1 class="mt-1 text-3xl font-black text-[#14205c]">{{ $program->title }}</h1><p class="mt-2 text-sm font-semibold text-slate-600">{{ $organization->name }}</p></div><x-program.status-badge :status="$program->execution_status" /></div></div>
        <div class="p-6"><dl class="grid gap-4 rounded-xl bg-slate-50 p-5 sm:grid-cols-3"><div><dt class="text-xs font-bold uppercase text-slate-500">Periode</dt><dd class="mt-1 font-semibold text-[#14205c]">{{ $program->start_date?->translatedFormat('d M Y') ?? 'Belum ditentukan' }}@if($program->end_date) – {{ $program->end_date->translatedFormat('d M Y') }}@endif</dd></div><div><dt class="text-xs font-bold uppercase text-slate-500">Activity terhubung</dt><dd class="mt-1 font-semibold text-[#14205c]">{{ $program->activities->count() }}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-500">Dibuat oleh</dt><dd class="mt-1 font-semibold text-[#14205c]">{{ $program->creator->name }}</dd></div></dl>
            <div class="mt-6 grid gap-6 lg:grid-cols-2"><div><h2 class="font-extrabold text-[#14205c]">Deskripsi Program</h2><p class="mt-3 whitespace-pre-line leading-7 text-slate-600">{{ $program->description ?: 'Belum ada deskripsi.' }}</p></div><div><h2 class="font-extrabold text-[#14205c]">Maksud & Tujuan</h2><p class="mt-3 whitespace-pre-line leading-7 text-slate-600">{{ $program->objectives ?: 'Belum ada tujuan yang dicatat.' }}</p></div></div>
            <div class="mt-6 flex flex-wrap gap-3">@can('update', $program)<a class="btn-secondary" href="{{ route('manager.programs.edit', [$organization, $program]) }}">Edit rencana</a>@endcan @if($program->execution_status!=='completed')<a class="btn-primary" href="{{ route('manager.activities.create', ['organization' => $organization, 'program_id' => $program->uuid()]) }}">+ Tambah Activity</a>@endif</div>
        </div>
    </section>
    <section class="rounded-2xl bg-white p-6 shadow-sm"><div class="flex flex-wrap items-end justify-between gap-3"><div><p class="text-sm font-bold text-orange-600">ACTIVITY TERKAIT</p><h2 class="mt-1 text-xl font-black text-[#14205c]">Rangkaian kegiatan resmi</h2></div><a class="text-sm font-bold text-[#243378] hover:underline" href="{{ route('manager.activities.index', $organization) }}">Lihat semua Activity</a></div>
        <div class="mt-5 space-y-3">@forelse($program->activities as $activity)<a href="{{ route('manager.activities.show', [$organization, $activity]) }}" class="grid gap-3 rounded-xl border border-slate-200 p-4 transition hover:border-indigo-300 hover:bg-indigo-50/30 sm:grid-cols-[1fr_auto] sm:items-center"><div><h3 class="font-extrabold text-[#14205c]">{{ $activity->title }}</h3><p class="mt-1 text-sm text-slate-500">{{ $activity->category?->name }} · {{ $activity->start_at->translatedFormat('d M Y, H:i') }}</p></div><div class="flex flex-wrap gap-2"><x-activity.status-badge :status="$activity->review_status" /><x-activity.status-badge :status="$activity->publication_status" /></div></a>@empty<div class="rounded-xl border border-dashed border-slate-300 p-8 text-center"><p class="font-bold text-[#14205c]">Belum ada Activity</p><p class="mt-2 text-sm text-slate-500">Tambahkan minimal satu Activity sebelum Program dapat diajukan pada fase Proposal.</p></div>@endforelse</div>
    </section>
    @include('manager.programs._proposal')
    @include('manager.programs._monitoring')
    @include('manager.programs._financial')
    @include('manager.programs._evaluation')
</div>
@endsection
