@extends('layouts.public')
@section('title', 'Program Pemuda · SIPORA')
@section('meta_description', 'Jelajahi Program pemuda yang sedang berjalan atau telah selesai melalui ekosistem SIPORA Kabupaten Pemalang.')
@section('canonical', route('programs.index'))
@section('content')
<section class="bg-[#18245c] px-5 py-14 text-white"><div class="mx-auto max-w-7xl"><p class="text-xs font-black uppercase tracking-[.18em] text-orange-300">Program publik</p><h1 class="mt-3 text-4xl font-black sm:text-5xl">Program untuk pengembangan pemuda</h1><p class="mt-4 max-w-2xl text-lg leading-8 text-indigo-100">Program yang sedang berjalan atau telah selesai, memiliki Proposal disetujui, dan diselenggarakan Community aktif.</p></div></section>
<div class="mx-auto max-w-7xl px-5 py-10">
    <form method="GET" action="{{ route('programs.index') }}" class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm" aria-label="Filter Program"><div class="grid gap-4 md:grid-cols-3"><label><span class="label">Cari Program</span><input class="field" type="search" name="q" value="{{ $filters['q'] }}" maxlength="120" placeholder="Judul, Community, kategori, atau tujuan"></label><label><span class="label">Kategori</span><select class="field" name="category"><option value="">Semua kategori</option>@foreach($categories as $category)<option value="{{ $category->slug }}" @selected($filters['category'] === $category->slug)>{{ $category->name }}</option>@endforeach</select></label><label><span class="label">Status</span><select class="field" name="status"><option value="">Berjalan dan selesai</option><option value="running" @selected($filters['status'] === 'running')>Berjalan</option><option value="completed" @selected($filters['status'] === 'completed')>Selesai</option></select></label></div><div class="mt-5 flex flex-wrap gap-3"><button class="landing-btn-primary" type="submit">Terapkan filter</button><a class="landing-btn-secondary" href="{{ route('programs.index') }}">Reset</a></div></form>
    <div class="mt-8"><p class="text-xs font-black uppercase tracking-wider text-orange-600">Program terverifikasi</p><h2 class="mt-1 text-2xl font-black text-[#18245c]">{{ $programs->total() }} hasil ditemukan</h2></div>
    <div class="mt-6 grid gap-6 md:grid-cols-2 xl:grid-cols-3">@forelse($programs as $program)<x-discovery.program-card :program="$program" />@empty<div class="col-span-full rounded-3xl border-2 border-dashed border-slate-200 bg-white p-12 text-center"><h2 class="text-xl font-black text-[#18245c]">Belum ada Program yang cocok</h2><p class="mt-2 text-slate-500">Ubah kata pencarian atau filter untuk melihat Program lain.</p></div>@endforelse</div>
    @if($programs->hasPages())<div class="mt-10">{{ $programs->links() }}</div>@endif
</div>
@endsection
