@extends('layouts.public')
@section('title', $program->title.' · SIPORA')
@section('meta_description', str($program->description ?: 'Program pengembangan pemuda di SIPORA.')->squish()->limit(155))
@section('canonical', route('programs.show', $program))
@section('content')
<article>
    <header class="bg-[#18245c] px-5 py-14 text-white"><div class="mx-auto max-w-5xl"><nav class="text-sm text-indigo-200" aria-label="Breadcrumb"><a class="hover:text-white" href="{{ route('programs.index') }}">Program</a><span aria-hidden="true"> / </span><span>{{ $program->title }}</span></nav><div class="mt-6 flex flex-wrap gap-2"><span class="rounded-full bg-white/10 px-3 py-1 text-xs font-black">{{ $program->category->name }}</span><span class="rounded-full {{ $program->execution_status === 'completed' ? 'bg-emerald-400/20 text-emerald-200' : 'bg-orange-400/20 text-orange-200' }} px-3 py-1 text-xs font-black">{{ $program->execution_status === 'completed' ? 'Selesai' : 'Berjalan' }}</span></div><h1 class="mt-4 text-4xl font-black sm:text-5xl">{{ $program->title }}</h1><p class="mt-4 text-lg text-indigo-100">Diselenggarakan oleh <a class="font-bold text-white underline" href="{{ route('communities.show', $program->organization) }}">{{ $program->organization->name }}</a></p></div></header>
    <div class="mx-auto max-w-5xl px-5 py-10"><section class="grid gap-4 rounded-2xl bg-[#eef0ff] p-6 sm:grid-cols-3"><div><p class="text-xs font-black uppercase text-slate-500">Status</p><p class="mt-1 font-black text-[#18245c]">{{ $program->execution_status === 'completed' ? 'Program telah selesai' : 'Program sedang berjalan' }}</p></div><div><p class="text-xs font-black uppercase text-slate-500">Mulai</p><p class="mt-1 font-black text-[#18245c]">{{ $program->start_date?->translatedFormat('d M Y') ?? 'Belum ditentukan' }}</p></div><div><p class="text-xs font-black uppercase text-slate-500">Selesai</p><p class="mt-1 font-black text-[#18245c]">{{ $program->end_date?->translatedFormat('d M Y') ?? 'Belum ditentukan' }}</p></div></section>
        <section class="mt-8 landing-card"><p class="text-xs font-black uppercase tracking-wider text-orange-600">Tentang Program</p><h2 class="mt-2 text-2xl font-black text-[#18245c]">Deskripsi</h2><p class="mt-4 whitespace-pre-line leading-7 text-slate-700">{{ $program->description ?: 'Deskripsi Program belum tersedia.' }}</p>@if($program->objectives)<h3 class="mt-7 font-black text-[#18245c]">Tujuan</h3><p class="mt-2 whitespace-pre-line leading-7 text-slate-700">{{ $program->objectives }}</p>@endif</section>
        <section class="mt-8"><div class="flex flex-wrap items-end justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-wider text-orange-600">Rangkaian publik</p><h2 class="mt-1 text-2xl font-black text-[#18245c]">Activity dalam Program</h2></div><a class="text-sm font-bold text-[#3346a8]" href="{{ route('communities.show', $program->organization) }}">Lihat Community →</a></div><div class="mt-5 grid gap-5 md:grid-cols-2">@forelse($activities as $activity)<x-discovery.activity-card :activity="$activity" compact />@empty<div class="col-span-full rounded-2xl border-2 border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">Belum ada Activity publik yang ditautkan ke Program ini.</div>@endforelse</div></section>
    </div>
</article>
@endsection
