@extends('layouts.manager')
@section('title', 'Profil '.$organization->name.' · SIPORA')
@section('manager-content')
@php($social = $organization->social_links ?? [])
<div class="mx-auto max-w-4xl space-y-6"><x-workspace.page-header :eyebrow="$organization->name" title="Profil Community" description="Perbarui informasi publik tanpa mengubah hasil verifikasi." />
<section class="rounded-2xl border border-indigo-200 bg-indigo-50 p-5"><h2 class="font-bold text-[#243378]">Data terlindungi</h2><div class="mt-3 grid gap-3 text-sm sm:grid-cols-3"><div><p class="text-slate-500">Kategori</p><p class="font-bold">{{ $organization->category->name }}</p></div><div><p class="text-slate-500">Status review</p><p class="font-bold capitalize">{{ $organization->review_status }}</p></div><div><p class="text-slate-500">Status operasional</p><p class="font-bold capitalize">{{ $organization->operational_status }}</p></div></div></section>
<form method="post" action="{{ route('manager.profile.update', $organization) }}" enctype="multipart/form-data" class="space-y-6">@csrf @method('PATCH')
<section class="sipora-card"><h2 class="text-xl font-bold text-[#243378]">Informasi publik</h2><div class="mt-5 grid gap-5 md:grid-cols-2"><div class="md:col-span-2"><label class="field-label" for="name">Nama komunitas</label><input class="field" id="name" name="name" required maxlength="180" value="{{ old('name', $organization->name) }}"><x-input-error :messages="$errors->get('name')" /></div><div class="md:col-span-2"><label class="field-label" for="description">Deskripsi</label><textarea class="field min-h-36" id="description" name="description" maxlength="5000">{{ old('description', $organization->description) }}</textarea><x-input-error :messages="$errors->get('description')" /></div><div class="md:col-span-2"><label class="field-label" for="logo">Logo baru</label><input class="field" id="logo" name="logo" type="file" accept="image/jpeg,image/png,image/webp"><p class="mt-1 text-xs text-slate-500">JPG, PNG, atau WebP; maksimal 2 MB.</p><x-input-error :messages="$errors->get('logo')" /></div></div></section>
<section class="sipora-card"><h2 class="text-xl font-bold text-[#243378]">Kontak dan lokasi publik</h2><div class="mt-5 grid gap-5 md:grid-cols-2"><div><label class="field-label" for="contact_email">Email publik</label><input class="field" id="contact_email" name="contact_email" type="email" value="{{ old('contact_email', $organization->contact_email) }}"></div><div><label class="field-label" for="contact_phone">Telepon publik</label><input class="field" id="contact_phone" name="contact_phone" value="{{ old('contact_phone', $organization->contact_phone) }}"></div><div class="md:col-span-2"><label class="field-label" for="address_text">Alamat publik</label><textarea class="field min-h-24" id="address_text" name="address_text">{{ old('address_text', $organization->address_text) }}</textarea></div><div><label class="field-label" for="website_url">Website</label><input class="field" id="website_url" name="website_url" type="url" value="{{ old('website_url', $organization->website_url) }}"></div><div><label class="field-label" for="social_instagram">Instagram</label><input class="field" id="social_instagram" name="social_instagram" type="url" value="{{ old('social_instagram', $social['instagram'] ?? '') }}"></div><div><label class="field-label" for="social_facebook">Facebook</label><input class="field" id="social_facebook" name="social_facebook" type="url" value="{{ old('social_facebook', $social['facebook'] ?? '') }}"></div><div><label class="field-label" for="social_tiktok">TikTok</label><input class="field" id="social_tiktok" name="social_tiktok" type="url" value="{{ old('social_tiktok', $social['tiktok'] ?? '') }}"></div></div></section>
<div class="flex justify-end gap-3"><a class="btn-secondary" href="{{ route('manager.dashboard', $organization) }}">Batal</a><button class="btn" type="submit">Simpan profil</button></div></form></div>
@endsection
