@extends('layouts.verifier')
@section('title','Evaluasi '.$program->title)
@section('verifier-content')
<div class="space-y-6"><x-ui.page-header eyebrow="Evaluasi akhir Program" :title="$program->title" :description="$program->organization->name.' · '.$program->category?->name"><x-slot:actions><a class="btn-secondary" href="{{ route('verifier.program-evaluations.index') }}">Kembali</a><x-program.status-badge :status="$program->execution_status" /></x-slot:actions></x-ui.page-header>
<x-workspace.eligibility-panel :eligible="$assessment['eligible']" :reasons="$assessment['reasons']" />
<section class="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><x-ui.metric-card title="Proposal terbaru" :value="'v'.($assessment['latest_proposal']?->version ?? '—')" icon="file-text" /><x-ui.metric-card title="Activity selesai" :value="$metrics['activity_completed'].'/'.$metrics['activity_total']" icon="clipboard-check" tone="info" /><x-ui.metric-card title="Logbook disetujui" :value="$program->logbooks->where('status','approved')->count()" icon="notebook" tone="success" /><x-ui.metric-card title="Progres terbaru" :value="($metrics['latest_reported_progress'] ?? '—').'%' " icon="activity" tone="accent" /></section>
<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><main class="space-y-6"><x-ui.card><h2 class="text-lg font-bold text-text-primary">Bukti pelaksanaan</h2><div class="mt-4 divide-y divide-border">@forelse($program->activities as $activity)<article class="flex flex-wrap items-center justify-between gap-2 py-3"><div><p class="font-semibold text-text-primary">{{ $activity->title }}</p><p class="text-xs text-text-secondary">{{ $activity->category?->name }}</p></div><x-activity.status-badge :status="$activity->execution_status" /></article>@empty<p class="text-sm text-text-secondary">Tidak ada Activity terhubung.</p>@endforelse</div></x-ui.card>
<x-ui.card><h2 class="text-lg font-bold text-text-primary">Ringkasan E-LPJ</h2>@if($financial)<dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between gap-4"><dt>Anggaran</dt><dd class="rupiah font-bold">{{ $money->rupiah($financial['proposal_budget']) }}</dd></div><div class="flex justify-between gap-4"><dt>Realisasi</dt><dd class="rupiah font-bold">{{ $money->rupiah($financial['realization_total']) }}</dd></div><div class="flex justify-between gap-4"><dt>Selisih</dt><dd class="rupiah font-bold">{{ $money->rupiah($financial['difference']) }}</dd></div></dl>@else<p class="mt-3 text-sm text-text-secondary">Belum ada E-LPJ.</p>@endif</x-ui.card>
<x-workspace.review-history title="Riwayat evaluasi">@forelse($program->evaluations as $evaluation)<article class="relative pb-5 last:pb-0"><span class="absolute -left-[27px] top-1 size-3 rounded-full bg-primary ring-4 ring-white"></span><div class="flex flex-wrap justify-between gap-2"><x-program.evaluation-decision-badge :decision="$evaluation->decision" /><span class="text-xs text-text-muted">{{ $evaluation->evaluated_at->translatedFormat('d M Y H:i') }} · {{ $evaluation->verifier->name }}</span></div><p class="mt-2 text-sm text-text-secondary">{{ $evaluation->evaluation_notes ?: 'Tidak ada catatan tambahan.' }}</p></article>@empty<p class="text-sm text-text-secondary">Belum ada evaluasi.</p>@endforelse</x-workspace.review-history></main>
<aside class="h-fit xl:sticky xl:top-24">@can('create',[App\Models\ProgramEvaluation::class,$program])<section class="sipora-card"><h2 class="text-xl font-bold text-text-primary">Keputusan final</h2><p class="mt-1 text-sm text-text-secondary">Keputusan menggunakan seluruh bukti Program yang tersedia.</p><form class="mt-5 space-y-4" method="POST" action="{{ route('verifier.program-evaluations.store',$program) }}">@csrf<input type="hidden" name="expected_latest_evaluation_id" value="{{ $program->latestEvaluation?->uuid() }}"><label><span class="label">Keputusan</span><select class="field" name="decision"><option value="approved">Setujui dan selesaikan Program</option><option value="revision">Minta tindak lanjut</option><option value="rejected">Tolak evaluasi akhir</option></select></label><label><span class="label">Catatan evaluasi</span><textarea class="field min-h-32" name="evaluation_notes" placeholder="Wajib untuk tindak lanjut atau penolakan">{{ old('evaluation_notes') }}</textarea></label><x-input-error :messages="$errors->get('evaluation_notes')" /><x-input-error :messages="$errors->get('evaluation')" /><button class="btn-primary">Finalkan evaluasi</button></form></section>@else<x-ui.card><h2 class="text-lg font-bold">Evaluasi tersimpan</h2><p class="mt-2 text-sm text-text-secondary">Riwayat keputusan tersedia pada panel utama.</p></x-ui.card>@endcan</aside></div></div>
@endsection
