@extends('layouts.public')
@section('title', $organization->name.' · SIPORA')
@section('content')
<section class="bg-[#18245c] text-white"><div class="mx-auto grid max-w-7xl gap-8 px-5 py-14 md:grid-cols-[140px_1fr_auto] md:items-center"><div class="grid size-32 place-items-center overflow-hidden rounded-3xl bg-white/10 text-5xl font-black">@if($organization->logo_path)<img class="size-full object-cover" src="{{ route('communities.logo', $organization) }}" alt="Logo {{ $organization->name }}">@else{{ mb_substr($organization->name, 0, 1) }}@endif</div><div><div class="flex flex-wrap gap-2"><span class="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">{{ $organization->category->name }}</span><span class="rounded-full bg-emerald-400/20 px-3 py-1 text-xs font-bold text-emerald-200">Terverifikasi · Aktif</span></div><h1 class="mt-4 text-4xl font-black">{{ $organization->name }}</h1><p class="mt-2 text-indigo-100">{{ $organization->administrativeArea?->name ?? 'Kabupaten Pemalang' }}</p></div><div class="min-w-52">
    @guest<a class="landing-btn-primary w-full" href="{{ route('login') }}">Masuk untuk bergabung</a>@else
        @if(auth()->user()->hasRole('youth'))
            @if(!$membership)<form method="post" action="{{ route('communities.join', $organization) }}">@csrf<button class="landing-btn-primary w-full" type="submit">Gabung Komunitas</button></form>
            @elseif($membership->membership_status === 'pending')<span class="block rounded-xl bg-amber-300 px-5 py-3 text-center font-bold text-amber-950">Permintaan menunggu</span>
            @elseif($membership->membership_status === 'active')<div class="space-y-2"><span class="block rounded-xl bg-emerald-300 px-5 py-3 text-center font-bold text-emerald-950">Anggota · {{ ucfirst($membership->access_role) }}</span>@if(in_array($membership->access_role, ['leader','manager'], true))<a href="{{ route('manager.members.index', $organization) }}" class="block text-center text-sm font-bold text-white underline">Kelola anggota</a>@endif<form method="post" action="{{ route('communities.membership.destroy', $organization) }}">@csrf @method('DELETE')<button class="w-full text-sm font-semibold text-indigo-100 underline" type="submit">Tinggalkan komunitas</button></form></div>
            @else<form method="post" action="{{ route('communities.join', $organization) }}">@csrf<button class="landing-btn-primary w-full" type="submit">Ajukan bergabung kembali</button></form>@endif
        @endif
    @endguest
</div></div></section>
<div class="mx-auto max-w-7xl px-5 pt-8"><section class="grid gap-4 rounded-2xl bg-[#eef0ff] p-5 sm:grid-cols-3"><div><p class="text-xs font-bold uppercase text-slate-500">Anggota aktif</p><p class="mt-1 text-2xl font-black text-[#243378]">{{ $organization->active_members_count }}</p></div><div><p class="text-xs font-bold uppercase text-slate-500">Status</p><p class="mt-1 text-lg font-black text-emerald-700">Terverifikasi</p></div><div><p class="text-xs font-bold uppercase text-slate-500">Kategori</p><p class="mt-1 text-lg font-black text-[#243378]">{{ $organization->category->name }}</p></div></section></div>
<div class="mx-auto grid max-w-7xl gap-6 px-5 py-10 lg:grid-cols-[1fr_340px]"><div class="space-y-6"><section class="landing-card"><p class="text-xs font-extrabold uppercase tracking-wider text-orange-600">Tentang komunitas</p><h2 class="mt-2 text-2xl font-bold text-[#243378]">Profil & deskripsi komunitas</h2><p class="mt-5 whitespace-pre-line leading-7 text-slate-600">{{ $organization->description ?: 'Deskripsi komunitas belum tersedia.' }}</p></section><section class="landing-card"><div class="flex items-center justify-between"><div><p class="text-xs font-bold uppercase text-slate-500">Phase 8</p><h2 class="mt-1 text-xl font-bold text-[#243378]">Kegiatan komunitas</h2></div><span class="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-[#243378]">Segera hadir</span></div><div class="mt-5 rounded-2xl border-2 border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">Belum ada Activity yang ditampilkan.</div></section></div><aside class="space-y-5"><section class="landing-card"><h2 class="font-bold text-[#243378]">Kontak komunitas</h2><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-slate-500">Email</dt><dd class="font-semibold">{{ $organization->contact_email ?: '—' }}</dd></div><div><dt class="text-slate-500">Telepon</dt><dd class="font-semibold">{{ $organization->contact_phone ?: '—' }}</dd></div><div><dt class="text-slate-500">Alamat</dt><dd class="font-semibold">{{ $organization->address_text ?: '—' }}</dd></div><div><dt class="text-slate-500">Website</dt><dd class="break-all font-semibold">{{ $organization->website_url ?: '—' }}</dd></div></dl>@if($organization->social_links)<div class="mt-4 border-t border-slate-100 pt-4">@foreach($organization->social_links as $channel => $url)<p class="break-all text-sm"><span class="font-bold capitalize">{{ $channel }}:</span> {{ $url }}</p>@endforeach</div>@endif</section><section class="landing-card"><h2 class="font-bold text-[#243378]">Keanggotaan</h2><p class="mt-2 text-sm text-slate-600">Bergabung menggunakan permintaan. Pengelola komunitas akan meninjau permintaanmu.</p></section></aside></div>
@endsection
