@extends('layouts.admin')
@section('title','Dashboard Admin · SIPORA')
@section('content')
<div class="space-y-7"><x-ui.page-header eyebrow="Government Workspace" title="Dashboard Tata Kelola SIPORA" description="Ringkasan faktual ekosistem SIPORA untuk pekerjaan administratif Dindikpora."><x-slot:actions><a class="btn-primary" href="{{ route('admin.identity-verifications.index') }}"><x-ui.icon name="shield-check" class="size-4" />Tinjau identitas</a><a class="btn-secondary" href="{{ route('admin.opportunities.index') }}">Kelola Opportunity</a></x-slot:actions></x-ui.page-header>
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Metrik utama"><x-ui.metric-card title="Youth terdaftar" :value="number_format($analytics['youth']['registered'])" icon="users" /><x-ui.metric-card title="Community aktif" :value="number_format($analytics['communities']['active'])" icon="building" tone="info" /><x-ui.metric-card title="Activity publik" :value="number_format($analytics['activities']['published'])" icon="clipboard-check" tone="accent" /><x-ui.metric-card title="Opportunity terbuka" :value="number_format($analytics['opportunities']['open_deadlines'])" icon="briefcase" tone="success" /></section>
<div class="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><x-ui.card><div class="flex items-center gap-3"><span class="grid size-10 place-items-center rounded-xl bg-warning-soft text-warning"><x-ui.icon name="shield-check" /></span><div><h2 class="text-lg font-bold text-text-primary">Perlu perhatian</h2><p class="text-sm text-text-secondary">Antrean faktual tanpa skor atau tren rekaan.</p></div></div><div class="mt-5 divide-y divide-border"><a class="flex items-center justify-between gap-3 py-4" href="{{ route('admin.identity-verifications.index') }}"><span><strong class="block text-text-primary">Verifikasi Identitas Pemuda</strong><span class="text-sm text-text-secondary">Buka antrean pengajuan identitas</span></span><x-ui.icon name="chevron-right" class="text-primary" /></a><a class="flex items-center justify-between gap-3 py-4" href="{{ route('admin.opportunities.index',['status'=>'draft']) }}"><span><strong class="block text-text-primary">Draft Opportunity</strong><span class="text-sm text-text-secondary">Tinjau konten sebelum publikasi</span></span><x-ui.icon name="chevron-right" class="text-primary" /></a></div></x-ui.card>
<x-ui.card><h2 class="text-lg font-bold text-text-primary">Status ekosistem</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between rounded-xl bg-surface-soft px-4 py-3"><dt>Profil Youth tersedia</dt><dd class="font-bold text-primary">{{ number_format($analytics['youth']['with_profile']) }}</dd></div><div class="flex justify-between rounded-xl bg-surface-soft px-4 py-3"><dt>Community menunggu</dt><dd class="font-bold text-primary">{{ number_format($analytics['communities']['pending']) }}</dd></div><div class="flex justify-between rounded-xl bg-surface-soft px-4 py-3"><dt>Activity mendatang</dt><dd class="font-bold text-primary">{{ number_format($analytics['activities']['upcoming']) }}</dd></div><div class="flex justify-between rounded-xl bg-surface-soft px-4 py-3"><dt>Registrasi Activity</dt><dd class="font-bold text-primary">{{ number_format($analytics['activities']['registrations']) }}</dd></div></dl></x-ui.card></div>
<x-ui.card><h2 class="text-lg font-bold text-text-primary">Status Program</h2><p class="mt-1 text-sm text-text-secondary">Distribusi sesuai status eksekusi yang tersimpan.</p><div class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@forelse($analytics['programs'] as $status=>$total)<div class="rounded-xl bg-surface-soft p-4"><span class="text-sm font-semibold text-text-secondary">{{ str($status)->replace('_',' ')->title() }}</span><strong class="mt-2 block text-2xl text-primary">{{ number_format($total) }}</strong></div>@empty<x-ui.empty-state class="sm:col-span-2" title="Belum ada Program" />@endforelse</div></x-ui.card>
<x-ui.card>
    <div class="flex flex-wrap items-end justify-between gap-3"><div><h2 class="text-lg font-bold text-text-primary">Statistik Pemuda SIPORA</h2><p class="mt-1 text-sm text-text-secondary">Berdasarkan pemuda yang terdaftar di SIPORA. Angka operasional dapat mencakup kelompok kecil.</p></div><a class="btn-secondary" href="{{ route('statistics.index') }}">Lihat tampilan publik</a></div>
    <div class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        @foreach([['registered', 'Pemuda Terdaftar'], ['identity_verified', 'Identitas Terverifikasi'], ['public_portfolio', 'Portfolio Publik'], ['activity_participated', 'Pernah Mengikuti Activity']] as [$key, $label])
            <div class="rounded-xl border border-border bg-surface-soft p-4"><p class="text-sm text-text-secondary">{{ $label }}</p><strong class="mt-2 block text-2xl text-text-primary">{{ number_format($youthStatistics['totals'][$key]) }}</strong></div>
        @endforeach
    </div>
    <h3 class="mt-7 font-bold text-text-primary">Tahapan partisipasi</h3>
    <div class="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">@foreach($youthStatistics['funnel'] as $step)<div class="flex justify-between gap-2 rounded-lg bg-surface-soft px-4 py-3 text-sm"><span>{{ $step['label'] }}</span><strong>{{ number_format($step['count']) }}</strong></div>@endforeach</div>
    <div class="mt-7 grid gap-5 lg:grid-cols-2 xl:grid-cols-3">
        @foreach([['growth_monthly', 'Pendaftaran per bulan'], ['growth_yearly', 'Pendaftaran per tahun'], ['age', 'Rentang usia'], ['gender', 'Gender'], ['districts', 'Kecamatan'], ['interests', 'Top Interest'], ['skills', 'Top Skill']] as [$key, $title])
            <section class="rounded-xl border border-border p-4"><h3 class="font-bold text-text-primary">{{ $title }}</h3><dl class="mt-3 space-y-2 text-sm">@forelse($youthStatistics[$key] as $row)<div class="flex justify-between gap-3"><dt class="min-w-0 truncate text-text-secondary">{{ $key === 'gender' ? (['male' => 'Laki-laki', 'female' => 'Perempuan', 'other' => 'Lainnya', 'prefer_not_to_say' => 'Memilih tidak menyebutkan', 'unknown' => 'Belum diisi'][$row['label']] ?? $row['label']) : $row['label'] }}</dt><dd class="font-bold text-text-primary">{{ number_format($row['count']) }}</dd></div>@empty<p class="text-text-muted">Belum ada data.</p>@endforelse</dl></section>
        @endforeach
    </div>
    <h3 class="mt-8 font-bold text-text-primary">Keterlibatan nyata</h3>
    <p class="mt-1 text-sm text-text-secondary">Setiap metrik menghitung Youth unik. Tidak semua metrik merupakan tahap berurutan.</p>
    <div class="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">@foreach($youthStatistics['participation'] as $row)<div class="flex justify-between gap-3 border border-border bg-surface-soft p-4 text-sm"><span>{{ $row['label'] }}</span><strong class="text-text-primary">{{ number_format($row['count']) }}</strong></div>@endforeach</div>
    <h3 class="mt-8 font-bold text-text-primary">Cakupan per kecamatan</h3>
    <p class="mt-1 text-sm text-text-secondary">Domisili Youth, Youth dengan pendaftaran Activity diterima, lokasi Activity terbit, Community aktif, dan Program publik. Record tanpa kecamatan tidak dihitung di tabel ini.</p>
    <div class="mt-3 overflow-x-auto"><table class="min-w-[46rem] w-full text-sm"><thead class="bg-surface-soft text-left"><tr><th class="p-3">Kecamatan</th><th class="p-3 text-right">Youth</th><th class="p-3 text-right">Ikut Activity</th><th class="p-3 text-right">Partisipasi</th><th class="p-3 text-right">Community</th><th class="p-3 text-right">Activity</th><th class="p-3 text-right">Program</th></tr></thead><tbody>@foreach($youthStatistics['coverage'] as $row)<tr class="border-b border-border"><th scope="row" class="p-3 text-left font-semibold">{{ $row['district'] }}</th><td class="p-3 text-right tabular-nums">{{ number_format($row['youth']) }}</td><td class="p-3 text-right tabular-nums">{{ number_format($row['participated']) }}</td><td class="p-3 text-right tabular-nums">{{ $row['youth'] ? number_format(100 * $row['participated'] / $row['youth'], 1).'%' : '—' }}</td>@foreach(['community','activity','program'] as $key)<td class="p-3 text-right tabular-nums">{{ number_format($row[$key]) }}</td>@endforeach</tr>@endforeach</tbody></table></div>
    <div class="mt-8 grid gap-5 xl:grid-cols-2">
        @foreach([['interest_by_district','Minat per kecamatan','district'],['skill_by_age','Keahlian per rentang usia','age']] as [$key,$title,$dimension])
            <section class="rounded-xl border border-border p-4"><h3 class="font-bold text-text-primary">{{ $title }}</h3><p class="mt-1 text-xs text-text-secondary">20 kombinasi dengan jumlah tertinggi. Kelompok kecil disamarkan.</p><div class="mt-3 max-h-80 overflow-auto"><table class="w-full text-sm"><thead><tr class="text-left"><th class="py-2">{{ $dimension === 'age' ? 'Usia' : 'Kecamatan' }}</th><th>Minat/keahlian</th><th class="text-right">Youth</th></tr></thead><tbody>@forelse($youthStatistics['cross_insights'][$key] as $row)<tr class="border-t border-border"><td class="py-2">{{ $row[$dimension] }}</td><td>{{ $row['label'] }}</td><td class="text-right tabular-nums">{{ $row['count'] < 5 && $row['count'] > 0 ? '<5' : number_format($row['count']) }}</td></tr>@empty<tr><td colspan="3" class="py-3 text-text-secondary">Belum ada data.</td></tr>@endforelse</tbody></table></div></section>
        @endforeach
    </div>
    <section class="mt-5 rounded-xl border border-border p-4"><h3 class="font-bold text-text-primary">Penyelesaian Activity per kategori</h3><p class="mt-1 text-xs text-text-secondary">Youth unik dengan pendaftaran diterima dan Youth unik yang menyelesaikan Activity pada kategori tersebut.</p><div class="mt-3 overflow-x-auto"><table class="w-full min-w-[32rem] text-sm"><thead><tr class="text-left"><th class="py-2">Kategori</th><th class="text-right">Diterima</th><th class="text-right">Selesai</th></tr></thead><tbody>@forelse($youthStatistics['cross_insights']['completion_by_category'] as $row)<tr class="border-t border-border"><th scope="row" class="py-2 text-left font-medium">{{ $row['label'] }}</th><td class="text-right tabular-nums">{{ number_format($row['accepted']) }}</td><td class="text-right tabular-nums">{{ number_format($row['completed']) }}</td></tr>@empty<tr><td colspan="3" class="py-3 text-text-secondary">Belum ada data.</td></tr>@endforelse</tbody></table></div></section>
</x-ui.card></div>
@endsection
