@extends('layouts.admin')
@section('title','Dashboard Admin · SIPORA')
@section('content')
<div class="space-y-7"><x-ui.page-header eyebrow="Government Workspace" title="Dashboard Tata Kelola SIPORA" description="Ringkasan faktual ekosistem SIPORA untuk pekerjaan administratif Dindikpora."><x-slot:actions><a class="btn-primary" href="{{ route('admin.identity-verifications.index') }}"><x-ui.icon name="shield-check" class="size-4" />Tinjau identitas</a><a class="btn-secondary" href="{{ route('admin.opportunities.index') }}">Kelola Opportunity</a></x-slot:actions></x-ui.page-header>
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Metrik utama"><x-ui.metric-card title="Youth terdaftar" :value="number_format($analytics['youth']['registered'])" icon="users" /><x-ui.metric-card title="Community aktif" :value="number_format($analytics['communities']['active'])" icon="building" tone="info" /><x-ui.metric-card title="Activity publik" :value="number_format($analytics['activities']['published'])" icon="clipboard-check" tone="accent" /><x-ui.metric-card title="Opportunity terbuka" :value="number_format($analytics['opportunities']['open_deadlines'])" icon="briefcase" tone="success" /></section>
<div class="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><x-ui.card><div class="flex items-center gap-3"><span class="grid size-10 place-items-center rounded-xl bg-warning-soft text-warning"><x-ui.icon name="shield-check" /></span><div><h2 class="text-lg font-bold text-text-primary">Perlu perhatian</h2><p class="text-sm text-text-secondary">Antrean faktual tanpa skor atau tren rekaan.</p></div></div><div class="mt-5 divide-y divide-border"><a class="flex items-center justify-between gap-3 py-4" href="{{ route('admin.identity-verifications.index') }}"><span><strong class="block text-text-primary">Verifikasi Identitas Pemuda</strong><span class="text-sm text-text-secondary">Buka antrean pengajuan identitas</span></span><x-ui.icon name="chevron-right" class="text-primary" /></a><a class="flex items-center justify-between gap-3 py-4" href="{{ route('admin.opportunities.index',['status'=>'draft']) }}"><span><strong class="block text-text-primary">Draft Opportunity</strong><span class="text-sm text-text-secondary">Tinjau konten sebelum publikasi</span></span><x-ui.icon name="chevron-right" class="text-primary" /></a></div></x-ui.card>
<x-ui.card><h2 class="text-lg font-bold text-text-primary">Status ekosistem</h2><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between rounded-xl bg-surface-soft px-4 py-3"><dt>Profil Youth tersedia</dt><dd class="font-bold text-primary">{{ number_format($analytics['youth']['with_profile']) }}</dd></div><div class="flex justify-between rounded-xl bg-surface-soft px-4 py-3"><dt>Community menunggu</dt><dd class="font-bold text-primary">{{ number_format($analytics['communities']['pending']) }}</dd></div><div class="flex justify-between rounded-xl bg-surface-soft px-4 py-3"><dt>Activity mendatang</dt><dd class="font-bold text-primary">{{ number_format($analytics['activities']['upcoming']) }}</dd></div><div class="flex justify-between rounded-xl bg-surface-soft px-4 py-3"><dt>Registrasi Activity</dt><dd class="font-bold text-primary">{{ number_format($analytics['activities']['registrations']) }}</dd></div></dl></x-ui.card></div>
<x-ui.card><h2 class="text-lg font-bold text-text-primary">Status Program</h2><p class="mt-1 text-sm text-text-secondary">Distribusi sesuai status eksekusi yang tersimpan.</p><div class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@forelse($analytics['programs'] as $status=>$total)<div class="rounded-xl bg-surface-soft p-4"><span class="text-sm font-semibold text-text-secondary">{{ str($status)->replace('_',' ')->title() }}</span><strong class="mt-2 block text-2xl text-primary">{{ number_format($total) }}</strong></div>@empty<x-ui.empty-state class="sm:col-span-2" title="Belum ada Program" />@endforelse</div></x-ui.card></div>
@endsection
